<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://xmlns.oracle.com/bpm/bpmobject/Data/CategoryBO" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:bpmo="http://xmlns.oracle.com/bpm/bpmobject/" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns0 bpmo xsd bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/CategoryBO.xsd"/>
            <oracle-xsl-mapper:rootElement name="CategoryBO" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/CategoryBO"/>
            <oracle-xsl-mapper:param name="Category"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/CategoryBO.xsd"/>
            <oracle-xsl-mapper:rootElement name="CategoryBO" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/CategoryBO"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 12:18:03 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns0:CategoryBO>
      <xsl:choose>
        <xsl:when test="contains(/ns0:CategoryBO/ns0:outcome,&quot;SUBMIT&quot;)">
          <ns0:category>
            <xsl:text disable-output-escaping="no">BVM-Submitted</xsl:text>
          </ns0:category>
        </xsl:when>
        <xsl:when test="contains(/ns0:CategoryBO/ns0:outcome,&quot;CANCEL&quot;)">
          <ns0:category>
            <xsl:text disable-output-escaping="no">BVM-Cancelled</xsl:text>
          </ns0:category>
        </xsl:when>
        <xsl:when test="contains(/ns0:CategoryBO/ns0:outcome,&quot;InitiatorFYI&quot;)">
          <ns0:category>
            <xsl:text disable-output-escaping="no">BVM-Processed</xsl:text>
          </ns0:category>
        </xsl:when>
        <xsl:when test="contains(/ns0:CategoryBO/ns0:outcome,&quot;ErrorFYI&quot;)">
          <ns0:category>
            <xsl:text disable-output-escaping="no">BVM-Errored</xsl:text>
          </ns0:category>
        </xsl:when>
        <xsl:when test="contains(/ns0:CategoryBO/ns0:outcome,&quot;APPROVE&quot;)">
          <ns0:category>
            <xsl:text disable-output-escaping="no">BVM-Approved</xsl:text>
          </ns0:category>
        </xsl:when>
        <xsl:when test="contains(/ns0:CategoryBO/ns0:outcome,&quot;ASSIGN&quot;)">
          <ns0:category>
            <xsl:text disable-output-escaping="no">BVM-Assigned</xsl:text>
          </ns0:category>
        </xsl:when>
        <xsl:when test="contains(/ns0:CategoryBO/ns0:outcome,&quot;REJECT&quot;)">
          <ns0:category>
            <xsl:text disable-output-escaping="no">BVM-Rejected</xsl:text>
          </ns0:category>
        </xsl:when>
        <xsl:otherwise>
          <ns0:category>
            <xsl:text disable-output-escaping="no">BVM-Withdrawn</xsl:text>
          </ns0:category>
        </xsl:otherwise>
      </xsl:choose>
    </ns0:CategoryBO>
  </xsl:template>
</xsl:stylesheet>