<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:bpmo="http://xmlns.oracle.com/bpm/bpmobject/" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns0="http://xmlns.oracle.com/bpm/bpmobject/Data/ProcessRoutingBO" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl bpmo xsd ns0 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/ProcessRoutingBO.xsd"/>
            <oracle-xsl-mapper:rootElement name="ProcessRoutingBO" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/ProcessRoutingBO"/>
            <oracle-xsl-mapper:param name="ProcessRoutingPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/ProcessRoutingBO.xsd"/>
            <oracle-xsl-mapper:rootElement name="ProcessRoutingBO" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/ProcessRoutingBO"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 12:18:03 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns0:ProcessRoutingBO>
      <ns0:submitBYE_Outcome>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:submitBYE_Outcome/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:submitBYE_Outcome/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:submitBYE_Outcome"/>
      </ns0:submitBYE_Outcome>
      <ns0:manageBYE_Outcome>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:manageBYE_Outcome/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:manageBYE_Outcome/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:manageBYE_Outcome"/>
      </ns0:manageBYE_Outcome>
      <ns0:manageBYE_PA_Outcome>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:manageBYE_PA_Outcome/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:manageBYE_PA_Outcome/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:manageBYE_PA_Outcome"/>
      </ns0:manageBYE_PA_Outcome>
      <ns0:reviewBYE_Outcome>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:reviewBYE_Outcome/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:reviewBYE_Outcome/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:reviewBYE_Outcome"/>
      </ns0:reviewBYE_Outcome>
      <ns0:reviewBYE_PA_Otcome>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:reviewBYE_PA_Otcome/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:reviewBYE_PA_Otcome/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:reviewBYE_PA_Otcome"/>
      </ns0:reviewBYE_PA_Otcome>
      <ns0:approveBYE_Outcome>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:approveBYE_Outcome/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:approveBYE_Outcome/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:approveBYE_Outcome"/>
      </ns0:approveBYE_Outcome>
      <ns0:fyiOutcome>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:fyiOutcome/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:fyiOutcome/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:fyiOutcome"/>
      </ns0:fyiOutcome>
      <ns0:assignTo_AppraiserId>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:assignTo_AppraiserId/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignTo_AppraiserId/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignTo_AppraiserId"/>
      </ns0:assignTo_AppraiserId>
      <ns0:supervisorId>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:supervisorId/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:supervisorId/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:supervisorId"/>
      </ns0:supervisorId>
      <ns0:principalAppraiserId>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:principalAppraiserId/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:principalAppraiserId/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:principalAppraiserId"/>
      </ns0:principalAppraiserId>
      <ns0:chiefAppraiserId>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:chiefAppraiserId/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:chiefAppraiserId/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:chiefAppraiserId"/>
      </ns0:chiefAppraiserId>
      <ns0:assignTo_SupervisorId>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:assignTo_SupervisorId/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignTo_SupervisorId/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignTo_SupervisorId"/>
      </ns0:assignTo_SupervisorId>
      <ns0:assignTo_SupervisorGroupId>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:assignTo_SupervisorGroupId/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignTo_SupervisorGroupId/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignTo_SupervisorGroupId"/>
      </ns0:assignTo_SupervisorGroupId>
      <ns0:assignedToAppraiserBy>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:assignedToAppraiserBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignedToAppraiserBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignedToAppraiserBy"/>
      </ns0:assignedToAppraiserBy>
      <ns0:assignedToSupervisorBy>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:assignedToSupervisorBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignedToSupervisorBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignedToSupervisorBy"/>
      </ns0:assignedToSupervisorBy>
      <ns0:assignedToPABy>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:assignedToPABy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignedToPABy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignedToPABy"/>
      </ns0:assignedToPABy>
      <ns0:assignedToChiefBy>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:assignedToChiefBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignedToChiefBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignedToChiefBy"/>
      </ns0:assignedToChiefBy>
      <ns0:submitTaskTitle>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:submitTaskTitle/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:submitTaskTitle/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:submitTaskTitle"/>
      </ns0:submitTaskTitle>
      <ns0:supervisorTaskTitle>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:supervisorTaskTitle/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:supervisorTaskTitle/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:supervisorTaskTitle"/>
      </ns0:supervisorTaskTitle>
      <ns0:pATaskTitle>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:pATaskTitle/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:pATaskTitle/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:pATaskTitle"/>
      </ns0:pATaskTitle>
      <ns0:supervisorGroupTaskTitle>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:supervisorGroupTaskTitle/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:supervisorGroupTaskTitle/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:supervisorGroupTaskTitle"/>
      </ns0:supervisorGroupTaskTitle>
      <ns0:pAGroupTaskTitle>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:pAGroupTaskTitle/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:pAGroupTaskTitle/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:pAGroupTaskTitle"/>
      </ns0:pAGroupTaskTitle>
      <ns0:submitBy>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:submitBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:submitBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:submitBy"/>
      </ns0:submitBy>
      <ns0:approvedBy>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:approvedBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:approvedBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:approvedBy"/>
      </ns0:approvedBy>
      <ns0:approvedByRole>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:approvedByRole/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:approvedByRole/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:approvedByRole"/>
      </ns0:approvedByRole>
      <ns0:pAAssigningToSupervisor>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:pAAssigningToSupervisor/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:pAAssigningToSupervisor/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:pAAssigningToSupervisor"/>
      </ns0:pAAssigningToSupervisor>
      <ns0:chiefAssigningToPA>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:chiefAssigningToPA/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:chiefAssigningToPA/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:chiefAssigningToPA"/>
      </ns0:chiefAssigningToPA>
      <ns0:chiefAssigningToSupervisor>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:chiefAssigningToSupervisor/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:chiefAssigningToSupervisor/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:chiefAssigningToSupervisor"/>
      </ns0:chiefAssigningToSupervisor>
      <ns0:pAAssigningToPA>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:pAAssigningToPA/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:pAAssigningToPA/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:pAAssigningToPA"/>
      </ns0:pAAssigningToPA>
      <ns0:accquiredBy_SupervisorId>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:accquiredBy_SupervisorId/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:accquiredBy_SupervisorId/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:accquiredBy_SupervisorId"/>
      </ns0:accquiredBy_SupervisorId>
      <ns0:accquiredBy_PAID>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:accquiredBy_PAID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:accquiredBy_PAID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:accquiredBy_PAID"/>
      </ns0:accquiredBy_PAID>
      <ns0:accquiredBy_ChiefID>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:accquiredBy_ChiefID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:accquiredBy_ChiefID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:accquiredBy_ChiefID"/>
      </ns0:accquiredBy_ChiefID>
      <ns0:selfAssign>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:selfAssign/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:selfAssign/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:selfAssign"/>
      </ns0:selfAssign>
      <ns0:pAAccquired>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:pAAccquired/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:pAAccquired/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:pAAccquired"/>
      </ns0:pAAccquired>
      <ns0:supervisorAccquired>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:supervisorAccquired/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:supervisorAccquired/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:supervisorAccquired"/>
      </ns0:supervisorAccquired>
      <ns0:chiefAccquired>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:chiefAccquired/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:chiefAccquired/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:chiefAccquired"/>
      </ns0:chiefAccquired>
      <ns0:escalateTo>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:escalateTo/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:escalateTo/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:escalateTo"/>
      </ns0:escalateTo>
      <ns0:escalationPath>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:escalationPath/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:escalationPath/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:escalationPath"/>
      </ns0:escalationPath>
      <ns0:isProcessEscalated>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:isProcessEscalated/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:isProcessEscalated/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:isProcessEscalated"/>
      </ns0:isProcessEscalated>
      <ns0:approvedByUserId>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:approvedByUserId/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:approvedByUserId/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:approvedByUserId"/>
      </ns0:approvedByUserId>
      <ns0:assignedToDirectorBy>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:assignedToDirectorBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignedToDirectorBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignedToDirectorBy"/>
      </ns0:assignedToDirectorBy>
      <ns0:assignedToAssistantAssessorBy>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:assignedToAssistantAssessorBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignedToAssistantAssessorBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assignedToAssistantAssessorBy"/>
      </ns0:assignedToAssistantAssessorBy>
      <ns0:directorId>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:directorId/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:directorId/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:directorId"/>
      </ns0:directorId>
      <ns0:assistantAssessorId>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:assistantAssessorId/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assistantAssessorId/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:assistantAssessorId"/>
      </ns0:assistantAssessorId>
      <ns0:noOfUserModifiedEvents>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:noOfUserModifiedEvents/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:noOfUserModifiedEvents/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:noOfUserModifiedEvents"/>
      </ns0:noOfUserModifiedEvents>
      <ns0:pAAssigningToAppraiser>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:pAAssigningToAppraiser/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:pAAssigningToAppraiser/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:pAAssigningToAppraiser"/>
      </ns0:pAAssigningToAppraiser>
      <ns0:chiefAssigningToAppraiser>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:chiefAssigningToAppraiser/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:chiefAssigningToAppraiser/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:chiefAssigningToAppraiser"/>
      </ns0:chiefAssigningToAppraiser>
      <ns0:isProcessCancelled>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:isProcessCancelled/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:isProcessCancelled/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:isProcessCancelled"/>
      </ns0:isProcessCancelled>
      <ns0:isInvalid>
        <xsl:if test="/ns0:ProcessRoutingBO/ns0:isInvalid/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:isInvalid/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:ProcessRoutingBO/ns0:isInvalid"/>
      </ns0:isInvalid>
    </ns0:ProcessRoutingBO>
  </xsl:template>
</xsl:stylesheet>