<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns6="http://assessor.lacounty.gov/amp/type/common/ResponseHeader/v1.0" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:bpmo="http://xmlns.oracle.com/bpm/bpmobject/" xmlns:ns5="http://assessor.lacounty.gov/amp/type/common/RequestHeader/v1.0" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns2="http://xmlns.oracle.com/bpm/bpmobject/Data/SortBYEBO" xmlns:ns3="http://xmlns.oracle.com/bpm/bpmobject/Data/AssignToUserOrGroupBO" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns1="http://assessor.lacounty.gov/amp/data/bvm/RetrieveBYE/v1.0" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns0="http://xmlns.oracle.com/bpm/bpmobject/Data/RetriveBYEDetails" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns4="http://assessor.lacounty.gov/amp/type/bvm/BaseYearEvent/v1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns6 bpmo ns5 ns2 ns3 ns1 ns0 ns4 xsd xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/RetriveBYEDetails.xsd"/>
            <oracle-xsl-mapper:rootElement name="RetriveBYEDetails" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/RetriveBYEDetails"/>
            <oracle-xsl-mapper:param name="RetriveBYE_PDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/RetriveBYEDetails.xsd"/>
            <oracle-xsl-mapper:rootElement name="RetriveBYEDetails" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/RetriveBYEDetails"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 12:18:03 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns0:RetriveBYEDetails>
      <ns1:RetrieveBYEDetails>
        <ns1:BYEDetailsOriginal>
          <ns1:header>
            <ns6:operationStatus>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:header/ns6:operationStatus"/>
            </ns6:operationStatus>
            <ns6:instanceId>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:header/ns6:instanceId"/>
            </ns6:instanceId>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:header/ns6:requestId">
              <ns6:requestId>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:header/ns6:requestId"/>
              </ns6:requestId>
            </xsl:if>
          </ns1:header>
          <ns1:ain>
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:ain"/>
          </ns1:ain>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:processStatus">
            <ns1:processStatus>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:processStatus"/>
            </ns1:processStatus>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:dbLockStatus">
            <ns1:dbLockStatus>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:dbLockStatus"/>
            </ns1:dbLockStatus>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:lockedByUserId">
            <ns1:lockedByUserId>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:lockedByUserId"/>
            </ns1:lockedByUserId>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:district">
            <ns1:district>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:district"/>
            </ns1:district>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:region">
            <ns1:region>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:region"/>
            </ns1:region>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:clusterNumber">
            <ns1:clusterNumber>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:clusterNumber"/>
            </ns1:clusterNumber>
          </xsl:if>
          <ns1:baseYearEventList>
            <xsl:for-each select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:baseYearEventList/ns1:baseYearEvent">
              <ns1:baseYearEvent>
                <ns4:ain>
                  <xsl:value-of select="ns4:ain"/>
                </ns4:ain>
                <ns4:byeId>
                  <xsl:value-of select="ns4:byeId"/>
                </ns4:byeId>
                <xsl:if test="ns4:ownershipCode">
                  <ns4:ownershipCode>
                    <xsl:value-of select="ns4:ownershipCode"/>
                  </ns4:ownershipCode>
                </xsl:if>
                <xsl:if test="ns4:percentOwnership">
                  <ns4:percentOwnership>
                    <xsl:value-of select="ns4:percentOwnership"/>
                  </ns4:percentOwnership>
                </xsl:if>
                <xsl:if test="ns4:eventName">
                  <ns4:eventName>
                    <xsl:value-of select="ns4:eventName"/>
                  </ns4:eventName>
                </xsl:if>
                <xsl:if test="ns4:eventDescription">
                  <ns4:eventDescription>
                    <xsl:value-of select="ns4:eventDescription"/>
                  </ns4:eventDescription>
                </xsl:if>
                <xsl:if test="ns4:eventDate">
                  <ns4:eventDate>
                    <xsl:value-of select="ns4:eventDate"/>
                  </ns4:eventDate>
                </xsl:if>
                <xsl:if test="ns4:recordingDate">
                  <ns4:recordingDate>
                    <xsl:value-of select="ns4:recordingDate"/>
                  </ns4:recordingDate>
                </xsl:if>
                <xsl:if test="ns4:documentNumber">
                  <ns4:documentNumber>
                    <xsl:value-of select="ns4:documentNumber"/>
                  </ns4:documentNumber>
                </xsl:if>
                <xsl:if test="ns4:sequenceNumber">
                  <ns4:sequenceNumber>
                    <xsl:value-of select="ns4:sequenceNumber"/>
                  </ns4:sequenceNumber>
                </xsl:if>
                <xsl:if test="ns4:baseYear">
                  <ns4:baseYear>
                    <xsl:value-of select="ns4:baseYear"/>
                  </ns4:baseYear>
                </xsl:if>
                <xsl:if test="ns4:subUnitNumber">
                  <ns4:subUnitNumber>
                    <xsl:value-of select="ns4:subUnitNumber"/>
                  </ns4:subUnitNumber>
                </xsl:if>
                <xsl:if test="ns4:subUnitDescription">
                  <ns4:subUnitDescription>
                    <xsl:value-of select="ns4:subUnitDescription"/>
                  </ns4:subUnitDescription>
                </xsl:if>
                <xsl:if test="ns4:partiallyCompleteNumber">
                  <ns4:partiallyCompleteNumber>
                    <xsl:value-of select="ns4:partiallyCompleteNumber"/>
                  </ns4:partiallyCompleteNumber>
                </xsl:if>
                <xsl:if test="ns4:blendedValueFlag">
                  <ns4:blendedValueFlag>
                    <xsl:value-of select="ns4:blendedValueFlag"/>
                  </ns4:blendedValueFlag>
                </xsl:if>
                <xsl:if test="ns4:percentageAppliedToValue">
                  <ns4:percentageAppliedToValue>
                    <xsl:value-of select="ns4:percentageAppliedToValue"/>
                  </ns4:percentageAppliedToValue>
                </xsl:if>
                <xsl:if test="ns4:landValue">
                  <ns4:landValue>
                    <xsl:value-of select="ns4:landValue"/>
                  </ns4:landValue>
                </xsl:if>
                <xsl:if test="ns4:improvementValue">
                  <ns4:improvementValue>
                    <xsl:value-of select="ns4:improvementValue"/>
                  </ns4:improvementValue>
                </xsl:if>
                <xsl:if test="ns4:landReasonCode">
                  <ns4:landReasonCode>
                    <xsl:value-of select="ns4:landReasonCode"/>
                  </ns4:landReasonCode>
                </xsl:if>
                <xsl:if test="ns4:improvementReasonCode">
                  <ns4:improvementReasonCode>
                    <xsl:value-of select="ns4:improvementReasonCode"/>
                  </ns4:improvementReasonCode>
                </xsl:if>
                <xsl:if test="ns4:fixtureValue">
                  <ns4:fixtureValue>
                    <xsl:value-of select="ns4:fixtureValue"/>
                  </ns4:fixtureValue>
                </xsl:if>
                <xsl:if test="ns4:retainedLandValue">
                  <ns4:retainedLandValue>
                    <xsl:value-of select="ns4:retainedLandValue"/>
                  </ns4:retainedLandValue>
                </xsl:if>
                <xsl:if test="ns4:retainedImprovementValue">
                  <ns4:retainedImprovementValue>
                    <xsl:value-of select="ns4:retainedImprovementValue"/>
                  </ns4:retainedImprovementValue>
                </xsl:if>
                <xsl:if test="ns4:retainedFixtureValue">
                  <ns4:retainedFixtureValue>
                    <xsl:value-of select="ns4:retainedFixtureValue"/>
                  </ns4:retainedFixtureValue>
                </xsl:if>
                <xsl:if test="ns4:ppAssessmentNumber">
                  <ns4:ppAssessmentNumber>
                    <xsl:value-of select="ns4:ppAssessmentNumber"/>
                  </ns4:ppAssessmentNumber>
                </xsl:if>
                <xsl:if test="ns4:personalPropertyType">
                  <ns4:personalPropertyType>
                    <xsl:value-of select="ns4:personalPropertyType"/>
                  </ns4:personalPropertyType>
                </xsl:if>
                <xsl:if test="ns4:ppDescription">
                  <ns4:ppDescription>
                    <xsl:value-of select="ns4:ppDescription"/>
                  </ns4:ppDescription>
                </xsl:if>
                <xsl:if test="ns4:totalAdjAcquisitionCost">
                  <ns4:totalAdjAcquisitionCost>
                    <xsl:value-of select="ns4:totalAdjAcquisitionCost"/>
                  </ns4:totalAdjAcquisitionCost>
                </xsl:if>
                <xsl:if test="ns4:percentageFixture">
                  <ns4:percentageFixture>
                    <xsl:value-of select="ns4:percentageFixture"/>
                  </ns4:percentageFixture>
                </xsl:if>
                <xsl:if test="ns4:effectiveBeginDate">
                  <ns4:effectiveBeginDate>
                    <xsl:value-of select="ns4:effectiveBeginDate"/>
                  </ns4:effectiveBeginDate>
                </xsl:if>
                <xsl:if test="ns4:effectiveEndDate">
                  <ns4:effectiveEndDate>
                    <xsl:value-of select="ns4:effectiveEndDate"/>
                  </ns4:effectiveEndDate>
                </xsl:if>
                <xsl:if test="ns4:verificationDate">
                  <ns4:verificationDate>
                    <xsl:value-of select="ns4:verificationDate"/>
                  </ns4:verificationDate>
                </xsl:if>
                <xsl:if test="ns4:eventSource">
                  <ns4:eventSource>
                    <xsl:value-of select="ns4:eventSource"/>
                  </ns4:eventSource>
                </xsl:if>
                <xsl:if test="ns4:verifiedBy">
                  <ns4:verifiedBy>
                    <xsl:value-of select="ns4:verifiedBy"/>
                  </ns4:verifiedBy>
                </xsl:if>
                <xsl:if test="ns4:byeLegacySourceSystem">
                  <ns4:byeLegacySourceSystem>
                    <xsl:value-of select="ns4:byeLegacySourceSystem"/>
                  </ns4:byeLegacySourceSystem>
                </xsl:if>
                <xsl:if test="ns4:originalAIN">
                  <ns4:originalAIN>
                    <xsl:value-of select="ns4:originalAIN"/>
                  </ns4:originalAIN>
                </xsl:if>
                <xsl:if test="ns4:originalBYEId">
                  <ns4:originalBYEId>
                    <xsl:value-of select="ns4:originalBYEId"/>
                  </ns4:originalBYEId>
                </xsl:if>
                <xsl:if test="ns4:rollType">
                  <ns4:rollType>
                    <xsl:value-of select="ns4:rollType"/>
                  </ns4:rollType>
                </xsl:if>
                <xsl:if test="ns4:transactionType">
                  <ns4:transactionType>
                    <xsl:value-of select="ns4:transactionType"/>
                  </ns4:transactionType>
                </xsl:if>
                <xsl:if test="ns4:userId">
                  <ns4:userId>
                    <xsl:value-of select="ns4:userId"/>
                  </ns4:userId>
                </xsl:if>
                <xsl:if test="ns4:newConstructionDate">
                  <ns4:newConstructionDate>
                    <xsl:value-of select="ns4:newConstructionDate"/>
                  </ns4:newConstructionDate>
                </xsl:if>
                <xsl:if test="ns4:createBy">
                  <ns4:createBy>
                    <xsl:value-of select="ns4:createBy"/>
                  </ns4:createBy>
                </xsl:if>
                <xsl:if test="ns4:createdDate">
                  <ns4:createdDate>
                    <xsl:value-of select="ns4:createdDate"/>
                  </ns4:createdDate>
                </xsl:if>
                <xsl:if test="ns4:modifiedBy">
                  <ns4:modifiedBy>
                    <xsl:value-of select="ns4:modifiedBy"/>
                  </ns4:modifiedBy>
                </xsl:if>
                <xsl:if test="ns4:inactiveDate">
                  <ns4:inactiveDate>
                    <xsl:value-of select="ns4:inactiveDate"/>
                  </ns4:inactiveDate>
                </xsl:if>
                <xsl:if test="ns4:modifiedDate">
                  <ns4:modifiedDate>
                    <xsl:value-of select="ns4:modifiedDate"/>
                  </ns4:modifiedDate>
                </xsl:if>
                <xsl:if test="ns4:currentOnClose">
                  <ns4:currentOnClose>
                    <xsl:value-of select="ns4:currentOnClose"/>
                  </ns4:currentOnClose>
                </xsl:if>
              </ns1:baseYearEvent>
            </xsl:for-each>
          </ns1:baseYearEventList>
        </ns1:BYEDetailsOriginal>
        <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified">
          <ns1:BYEDetailsUserModified>
            <ns1:header>
              <ns6:operationStatus>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:header/ns6:operationStatus"/>
              </ns6:operationStatus>
              <ns6:instanceId>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:header/ns6:instanceId"/>
              </ns6:instanceId>
              <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:header/ns6:requestId">
                <ns6:requestId>
                  <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:header/ns6:requestId"/>
                </ns6:requestId>
              </xsl:if>
            </ns1:header>
            <ns1:ain>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:ain"/>
            </ns1:ain>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:processStatus">
              <ns1:processStatus>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:processStatus"/>
              </ns1:processStatus>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:dbLockStatus">
              <ns1:dbLockStatus>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:dbLockStatus"/>
              </ns1:dbLockStatus>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:lockedByUserId">
              <ns1:lockedByUserId>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:lockedByUserId"/>
              </ns1:lockedByUserId>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:district">
              <ns1:district>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:district"/>
              </ns1:district>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:region">
              <ns1:region>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:region"/>
              </ns1:region>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:clusterNumber">
              <ns1:clusterNumber>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:clusterNumber"/>
              </ns1:clusterNumber>
            </xsl:if>
            <ns1:baseYearEventList>
              <xsl:for-each select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:baseYearEventList/ns1:baseYearEvent">
                <ns1:baseYearEvent>
                  <ns4:ain>
                    <xsl:value-of select="ns4:ain"/>
                  </ns4:ain>
                  <ns4:byeId>
                    <xsl:value-of select="ns4:byeId"/>
                  </ns4:byeId>
                  <xsl:if test="ns4:ownershipCode">
                    <ns4:ownershipCode>
                      <xsl:value-of select="ns4:ownershipCode"/>
                    </ns4:ownershipCode>
                  </xsl:if>
                  <xsl:if test="ns4:percentOwnership">
                    <ns4:percentOwnership>
                      <xsl:value-of select="ns4:percentOwnership"/>
                    </ns4:percentOwnership>
                  </xsl:if>
                  <xsl:if test="ns4:eventName">
                    <ns4:eventName>
                      <xsl:value-of select="ns4:eventName"/>
                    </ns4:eventName>
                  </xsl:if>
                  <xsl:if test="ns4:eventDescription">
                    <ns4:eventDescription>
                      <xsl:value-of select="ns4:eventDescription"/>
                    </ns4:eventDescription>
                  </xsl:if>
                  <xsl:if test="ns4:eventDate">
                    <ns4:eventDate>
                      <xsl:value-of select="ns4:eventDate"/>
                    </ns4:eventDate>
                  </xsl:if>
                  <xsl:if test="ns4:recordingDate">
                    <ns4:recordingDate>
                      <xsl:value-of select="ns4:recordingDate"/>
                    </ns4:recordingDate>
                  </xsl:if>
                  <xsl:if test="ns4:documentNumber">
                    <ns4:documentNumber>
                      <xsl:value-of select="ns4:documentNumber"/>
                    </ns4:documentNumber>
                  </xsl:if>
                  <xsl:if test="ns4:sequenceNumber">
                    <ns4:sequenceNumber>
                      <xsl:value-of select="ns4:sequenceNumber"/>
                    </ns4:sequenceNumber>
                  </xsl:if>
                  <xsl:if test="ns4:baseYear">
                    <ns4:baseYear>
                      <xsl:value-of select="ns4:baseYear"/>
                    </ns4:baseYear>
                  </xsl:if>
                  <xsl:if test="ns4:subUnitNumber">
                    <ns4:subUnitNumber>
                      <xsl:value-of select="ns4:subUnitNumber"/>
                    </ns4:subUnitNumber>
                  </xsl:if>
                  <xsl:if test="ns4:subUnitDescription">
                    <ns4:subUnitDescription>
                      <xsl:value-of select="ns4:subUnitDescription"/>
                    </ns4:subUnitDescription>
                  </xsl:if>
                  <xsl:if test="ns4:partiallyCompleteNumber">
                    <ns4:partiallyCompleteNumber>
                      <xsl:value-of select="ns4:partiallyCompleteNumber"/>
                    </ns4:partiallyCompleteNumber>
                  </xsl:if>
                  <xsl:if test="ns4:blendedValueFlag">
                    <ns4:blendedValueFlag>
                      <xsl:value-of select="ns4:blendedValueFlag"/>
                    </ns4:blendedValueFlag>
                  </xsl:if>
                  <xsl:if test="ns4:percentageAppliedToValue">
                    <ns4:percentageAppliedToValue>
                      <xsl:value-of select="ns4:percentageAppliedToValue"/>
                    </ns4:percentageAppliedToValue>
                  </xsl:if>
                  <xsl:if test="ns4:landValue">
                    <ns4:landValue>
                      <xsl:value-of select="ns4:landValue"/>
                    </ns4:landValue>
                  </xsl:if>
                  <xsl:if test="ns4:improvementValue">
                    <ns4:improvementValue>
                      <xsl:value-of select="ns4:improvementValue"/>
                    </ns4:improvementValue>
                  </xsl:if>
                  <xsl:if test="ns4:landReasonCode">
                    <ns4:landReasonCode>
                      <xsl:value-of select="ns4:landReasonCode"/>
                    </ns4:landReasonCode>
                  </xsl:if>
                  <xsl:if test="ns4:improvementReasonCode">
                    <ns4:improvementReasonCode>
                      <xsl:value-of select="ns4:improvementReasonCode"/>
                    </ns4:improvementReasonCode>
                  </xsl:if>
                  <xsl:if test="ns4:fixtureValue">
                    <ns4:fixtureValue>
                      <xsl:value-of select="ns4:fixtureValue"/>
                    </ns4:fixtureValue>
                  </xsl:if>
                  <xsl:if test="ns4:retainedLandValue">
                    <ns4:retainedLandValue>
                      <xsl:value-of select="ns4:retainedLandValue"/>
                    </ns4:retainedLandValue>
                  </xsl:if>
                  <xsl:if test="ns4:retainedImprovementValue">
                    <ns4:retainedImprovementValue>
                      <xsl:value-of select="ns4:retainedImprovementValue"/>
                    </ns4:retainedImprovementValue>
                  </xsl:if>
                  <xsl:if test="ns4:retainedFixtureValue">
                    <ns4:retainedFixtureValue>
                      <xsl:value-of select="ns4:retainedFixtureValue"/>
                    </ns4:retainedFixtureValue>
                  </xsl:if>
                  <xsl:if test="ns4:ppAssessmentNumber">
                    <ns4:ppAssessmentNumber>
                      <xsl:value-of select="ns4:ppAssessmentNumber"/>
                    </ns4:ppAssessmentNumber>
                  </xsl:if>
                  <xsl:if test="ns4:personalPropertyType">
                    <ns4:personalPropertyType>
                      <xsl:value-of select="ns4:personalPropertyType"/>
                    </ns4:personalPropertyType>
                  </xsl:if>
                  <xsl:if test="ns4:ppDescription">
                    <ns4:ppDescription>
                      <xsl:value-of select="ns4:ppDescription"/>
                    </ns4:ppDescription>
                  </xsl:if>
                  <xsl:if test="ns4:totalAdjAcquisitionCost">
                    <ns4:totalAdjAcquisitionCost>
                      <xsl:value-of select="ns4:totalAdjAcquisitionCost"/>
                    </ns4:totalAdjAcquisitionCost>
                  </xsl:if>
                  <xsl:if test="ns4:percentageFixture">
                    <ns4:percentageFixture>
                      <xsl:value-of select="ns4:percentageFixture"/>
                    </ns4:percentageFixture>
                  </xsl:if>
                  <xsl:if test="ns4:effectiveBeginDate">
                    <ns4:effectiveBeginDate>
                      <xsl:value-of select="ns4:effectiveBeginDate"/>
                    </ns4:effectiveBeginDate>
                  </xsl:if>
                  <xsl:if test="ns4:effectiveEndDate">
                    <ns4:effectiveEndDate>
                      <xsl:value-of select="ns4:effectiveEndDate"/>
                    </ns4:effectiveEndDate>
                  </xsl:if>
                  <xsl:if test="ns4:verificationDate">
                    <ns4:verificationDate>
                      <xsl:value-of select="ns4:verificationDate"/>
                    </ns4:verificationDate>
                  </xsl:if>
                  <xsl:if test="ns4:eventSource">
                    <ns4:eventSource>
                      <xsl:value-of select="ns4:eventSource"/>
                    </ns4:eventSource>
                  </xsl:if>
                  <xsl:if test="ns4:verifiedBy">
                    <ns4:verifiedBy>
                      <xsl:value-of select="ns4:verifiedBy"/>
                    </ns4:verifiedBy>
                  </xsl:if>
                  <xsl:if test="ns4:byeLegacySourceSystem">
                    <ns4:byeLegacySourceSystem>
                      <xsl:value-of select="ns4:byeLegacySourceSystem"/>
                    </ns4:byeLegacySourceSystem>
                  </xsl:if>
                  <xsl:if test="ns4:originalAIN">
                    <ns4:originalAIN>
                      <xsl:value-of select="ns4:originalAIN"/>
                    </ns4:originalAIN>
                  </xsl:if>
                  <xsl:if test="ns4:originalBYEId">
                    <ns4:originalBYEId>
                      <xsl:value-of select="ns4:originalBYEId"/>
                    </ns4:originalBYEId>
                  </xsl:if>
                  <xsl:if test="ns4:rollType">
                    <ns4:rollType>
                      <xsl:value-of select="ns4:rollType"/>
                    </ns4:rollType>
                  </xsl:if>
                  <xsl:if test="ns4:transactionType">
                    <ns4:transactionType>
                      <xsl:value-of select="ns4:transactionType"/>
                    </ns4:transactionType>
                  </xsl:if>
                  <xsl:if test="ns4:userId">
                    <ns4:userId>
                      <xsl:value-of select="ns4:userId"/>
                    </ns4:userId>
                  </xsl:if>
                  <xsl:if test="ns4:newConstructionDate">
                    <ns4:newConstructionDate>
                      <xsl:value-of select="ns4:newConstructionDate"/>
                    </ns4:newConstructionDate>
                  </xsl:if>
                  <xsl:if test="ns4:createBy">
                    <ns4:createBy>
                      <xsl:value-of select="ns4:createBy"/>
                    </ns4:createBy>
                  </xsl:if>
                  <xsl:if test="ns4:createdDate">
                    <ns4:createdDate>
                      <xsl:value-of select="ns4:createdDate"/>
                    </ns4:createdDate>
                  </xsl:if>
                  <xsl:if test="ns4:modifiedBy">
                    <ns4:modifiedBy>
                      <xsl:value-of select="ns4:modifiedBy"/>
                    </ns4:modifiedBy>
                  </xsl:if>
                  <xsl:if test="ns4:inactiveDate">
                    <ns4:inactiveDate>
                      <xsl:value-of select="ns4:inactiveDate"/>
                    </ns4:inactiveDate>
                  </xsl:if>
                  <xsl:if test="ns4:modifiedDate">
                    <ns4:modifiedDate>
                      <xsl:value-of select="ns4:modifiedDate"/>
                    </ns4:modifiedDate>
                  </xsl:if>
                  <xsl:if test="ns4:currentOnClose">
                    <ns4:currentOnClose>
                      <xsl:value-of select="ns4:currentOnClose"/>
                    </ns4:currentOnClose>
                  </xsl:if>
                </ns1:baseYearEvent>
              </xsl:for-each>
            </ns1:baseYearEventList>
          </ns1:BYEDetailsUserModified>
        </xsl:if>
      </ns1:RetrieveBYEDetails>
      <ns0:sortBYE>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <ns2:ain>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:ain/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:ain/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:ain"/>
        </ns2:ain>
        <ns2:district>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:district/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:district/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:district"/>
        </ns2:district>
        <ns2:region>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:region/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:region/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:region"/>
        </ns2:region>
        <ns2:cluster>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:cluster/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:cluster/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:cluster"/>
        </ns2:cluster>
      </ns0:sortBYE>
      <ns0:assignTo_UserID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignTo_UserID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_UserID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_UserID"/>
      </ns0:assignTo_UserID>
      <ns0:assignTo_GroupID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignTo_GroupID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_GroupID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_GroupID"/>
      </ns0:assignTo_GroupID>
      <ns0:assignTo_ManagerID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignTo_ManagerID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_ManagerID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_ManagerID"/>
      </ns0:assignTo_ManagerID>
      <ns0:role>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:role/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:role/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:role"/>
      </ns0:role>
      <ns0:ownerID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:ownerID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:ownerID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:ownerID"/>
      </ns0:ownerID>
      <ns0:clientID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:clientID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:clientID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:clientID"/>
      </ns0:clientID>
      <ns0:checkBYE>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:checkBYE/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:checkBYE/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:checkBYE"/>
      </ns0:checkBYE>
      <ns0:userType>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:userType/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:userType/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:userType"/>
      </ns0:userType>
      <ns0:acquiredBy>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:acquiredBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:acquiredBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:acquiredBy"/>
      </ns0:acquiredBy>
      <ns0:returnTo>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:returnTo/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:returnTo/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:returnTo"/>
      </ns0:returnTo>
      <ns0:assignmentBox>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignmentBox/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignmentBox/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <ns3:assignmentBox_UserId>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:assignmentBox_UserId/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:assignmentBox_UserId/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:assignmentBox_UserId"/>
        </ns3:assignmentBox_UserId>
        <ns3:assignmentBox_GroupId>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:assignmentBox_GroupId/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:assignmentBox_GroupId/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:assignmentBox_GroupId"/>
        </ns3:assignmentBox_GroupId>
        <ns3:userType>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:userType/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:userType/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:userType"/>
        </ns3:userType>
      </ns0:assignmentBox>
      <ns0:assignedBy>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignedBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignedBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignedBy"/>
      </ns0:assignedBy>
      <ns0:submitBy>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:submitBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:submitBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:submitBy"/>
      </ns0:submitBy>
    </ns0:RetriveBYEDetails>
  </xsl:template>
</xsl:stylesheet>