<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns5="http://xmlns.oracle.com/bpm/bpmobject/Data/UIStateBO" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns9="http://xmlns.oracle.com/bpel/workflow/common" xmlns:ns8="http://assessor.lacounty.gov/amp/type/common/ResponseHeader/v1.0" xmlns:evidence="http://xmlns.oracle.com/bpel/workflow/TaskEvidenceService" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:bpmo="http://xmlns.oracle.com/bpm/bpmobject/" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:ns7="http://assessor.lacounty.gov/amp/type/common/RequestHeader/v1.0" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ns2="http://xmlns.oracle.com/bpm/bpmobject/Data/SortBYEBO" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns3="http://xmlns.oracle.com/bpm/bpmobject/Data/AssignToUserOrGroupBO" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns1="http://assessor.lacounty.gov/amp/data/bvm/RetrieveBYE/v1.0" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns0="http://xmlns.oracle.com/bpm/bpmobject/Data/RetriveBYEDetails" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns6="http://assessor.lacounty.gov/amp/type/bvm/BaseYearEvent/v1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xmlns.oracle.com/bpel/workflow/task" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ns4="http://assessor.lacounty.gov/amp/data/bvm/ManageBYE/v1.0" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns5 ns9 ns8 evidence bpmo jaxb ns7 ns2 ns3 ns1 ns0 ns6 xsd tns ns4 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/RetriveBYEDetails.xsd"/>
            <oracle-xsl-mapper:rootElement name="RetriveBYEDetails" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/RetriveBYEDetails"/>
            <oracle-xsl-mapper:param name="retriveBYEDetails"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/SubmitBaseYearEventTaskWorkflowTask.xsd"/>
            <oracle-xsl-mapper:rootElement name="task" namespace="http://xmlns.oracle.com/bpel/workflow/task"/>
            <oracle-xsl-mapper:param name="execData"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/RetriveBYEDetails.xsd"/>
            <oracle-xsl-mapper:rootElement name="RetriveBYEDetails" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/RetriveBYEDetails"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 12:18:09 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="execData"/>
  <xsl:template match="/">
    <ns0:RetriveBYEDetails>
      <ns1:RetrieveBYEDetails>
        <ns1:BYEDetailsOriginal>
          <ns1:header>
            <ns8:operationStatus>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:header/ns8:operationStatus"/>
            </ns8:operationStatus>
            <ns8:instanceId>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:header/ns8:instanceId"/>
            </ns8:instanceId>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:header/ns8:requestId">
              <ns8:requestId>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:header/ns8:requestId"/>
              </ns8:requestId>
            </xsl:if>
          </ns1:header>
          <ns1:ain>
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:ain"/>
          </ns1:ain>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:aoid">
            <ns1:aoid>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:aoid"/>
            </ns1:aoid>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:ainType">
            <ns1:ainType>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:ainType"/>
            </ns1:ainType>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:reviewRequired">
            <ns1:reviewRequired>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:reviewRequired"/>
            </ns1:reviewRequired>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:processStatus">
            <ns1:processStatus>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:processStatus"/>
            </ns1:processStatus>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:ecid">
            <ns1:ecid>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:ecid"/>
            </ns1:ecid>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:dbLockStatus">
            <ns1:dbLockStatus>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:dbLockStatus"/>
            </ns1:dbLockStatus>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:lockedByUserId">
            <ns1:lockedByUserId>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:lockedByUserId"/>
            </ns1:lockedByUserId>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtId">
            <ns1:districtId>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtId"/>
            </ns1:districtId>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtName">
            <ns1:districtName>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtName"/>
            </ns1:districtName>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:region">
            <ns1:region>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:region"/>
            </ns1:region>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:regionName">
            <ns1:regionName>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:regionName"/>
            </ns1:regionName>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:clusterRouteId">
            <ns1:clusterRouteId>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:clusterRouteId"/>
            </ns1:clusterRouteId>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:clusterRoute">
            <ns1:clusterRoute>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:clusterRoute"/>
            </ns1:clusterRoute>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:clusterRouteName">
            <ns1:clusterRouteName>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:clusterRouteName"/>
            </ns1:clusterRouteName>
          </xsl:if>
          <ns1:isDirty>
            <xsl:text disable-output-escaping="no">false</xsl:text>
          </ns1:isDirty>
          <ns1:baseYearEventList>
            <xsl:for-each select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:baseYearEventList/ns1:baseYearEvent">
              <ns1:baseYearEvent>
                <ns6:ain>
                  <xsl:value-of select="ns6:ain"/>
                </ns6:ain>
                <xsl:if test="ns6:aoid">
                  <ns6:aoid>
                    <xsl:value-of select="ns6:aoid"/>
                  </ns6:aoid>
                </xsl:if>
                <xsl:if test="ns6:reviewRequired">
                  <ns6:reviewRequired>
                    <xsl:value-of select="ns6:reviewRequired"/>
                  </ns6:reviewRequired>
                </xsl:if>
                <ns6:byeId>
                  <xsl:value-of select="ns6:byeId"/>
                </ns6:byeId>
                <xsl:if test="ns6:ownershipCode">
                  <ns6:ownershipCode>
                    <xsl:value-of select="ns6:ownershipCode"/>
                  </ns6:ownershipCode>
                </xsl:if>
                <xsl:if test="ns6:percentOwnership">
                  <ns6:percentOwnership>
                    <xsl:value-of select="ns6:percentOwnership"/>
                  </ns6:percentOwnership>
                </xsl:if>
                <xsl:if test="ns6:eventNameId">
                  <ns6:eventNameId>
                    <xsl:value-of select="ns6:eventNameId"/>
                  </ns6:eventNameId>
                </xsl:if>
                <xsl:if test="ns6:eventNameKey">
                  <ns6:eventNameKey>
                    <xsl:value-of select="ns6:eventNameKey"/>
                  </ns6:eventNameKey>
                </xsl:if>
                <xsl:if test="ns6:eventNameLegend">
                  <ns6:eventNameLegend>
                    <xsl:value-of select="ns6:eventNameLegend"/>
                  </ns6:eventNameLegend>
                </xsl:if>
                <xsl:if test="ns6:eventDescriptionId">
                  <ns6:eventDescriptionId>
                    <xsl:value-of select="ns6:eventDescriptionId"/>
                  </ns6:eventDescriptionId>
                </xsl:if>
                <xsl:if test="ns6:eventDescriptionKey">
                  <ns6:eventDescriptionKey>
                    <xsl:value-of select="ns6:eventDescriptionKey"/>
                  </ns6:eventDescriptionKey>
                </xsl:if>
                <xsl:if test="ns6:eventDescriptionLegend">
                  <ns6:eventDescriptionLegend>
                    <xsl:value-of select="ns6:eventDescriptionLegend"/>
                  </ns6:eventDescriptionLegend>
                </xsl:if>
                <xsl:if test="ns6:eventDate">
                  <ns6:eventDate>
                    <xsl:value-of select="ns6:eventDate"/>
                  </ns6:eventDate>
                </xsl:if>
                <xsl:if test="ns6:recordingDate">
                  <ns6:recordingDate>
                    <xsl:value-of select="ns6:recordingDate"/>
                  </ns6:recordingDate>
                </xsl:if>
                <xsl:if test="ns6:documentNumber">
                  <ns6:documentNumber>
                    <xsl:value-of select="ns6:documentNumber"/>
                  </ns6:documentNumber>
                </xsl:if>
                <xsl:if test="ns6:sequenceNumber">
                  <ns6:sequenceNumber>
                    <xsl:value-of select="ns6:sequenceNumber"/>
                  </ns6:sequenceNumber>
                </xsl:if>
                <xsl:if test="ns6:baseYear">
                  <ns6:baseYear>
                    <xsl:value-of select="ns6:baseYear"/>
                  </ns6:baseYear>
                </xsl:if>
                <xsl:if test="ns6:subUnitNumber">
                  <ns6:subUnitNumber>
                    <xsl:value-of select="ns6:subUnitNumber"/>
                  </ns6:subUnitNumber>
                </xsl:if>
                <xsl:if test="ns6:subUnitDescription">
                  <ns6:subUnitDescription>
                    <xsl:value-of select="ns6:subUnitDescription"/>
                  </ns6:subUnitDescription>
                </xsl:if>
                <xsl:if test="ns6:partiallyCompleteNumber">
                  <ns6:partiallyCompleteNumber>
                    <xsl:value-of select="ns6:partiallyCompleteNumber"/>
                  </ns6:partiallyCompleteNumber>
                </xsl:if>
                <xsl:if test="ns6:blendedValueFlag">
                  <ns6:blendedValueFlag>
                    <xsl:value-of select="ns6:blendedValueFlag"/>
                  </ns6:blendedValueFlag>
                </xsl:if>
                <xsl:if test="ns6:percentageAppliedToValue">
                  <ns6:percentageAppliedToValue>
                    <xsl:value-of select="ns6:percentageAppliedToValue"/>
                  </ns6:percentageAppliedToValue>
                </xsl:if>
                <xsl:if test="ns6:landValue">
                  <ns6:landValue>
                    <xsl:value-of select="ns6:landValue"/>
                  </ns6:landValue>
                </xsl:if>
                <xsl:if test="ns6:improvementValue">
                  <ns6:improvementValue>
                    <xsl:value-of select="ns6:improvementValue"/>
                  </ns6:improvementValue>
                </xsl:if>
                <xsl:if test="ns6:landReasonCodeId">
                  <ns6:landReasonCodeId>
                    <xsl:value-of select="ns6:landReasonCodeId"/>
                  </ns6:landReasonCodeId>
                </xsl:if>
                <xsl:if test="ns6:landReasonCodeKey">
                  <ns6:landReasonCodeKey>
                    <xsl:value-of select="ns6:landReasonCodeKey"/>
                  </ns6:landReasonCodeKey>
                </xsl:if>
                <xsl:if test="ns6:landReasonCodeLegend">
                  <ns6:landReasonCodeLegend>
                    <xsl:value-of select="ns6:landReasonCodeLegend"/>
                  </ns6:landReasonCodeLegend>
                </xsl:if>
                <xsl:if test="ns6:improvementReasonCodeId">
                  <ns6:improvementReasonCodeId>
                    <xsl:value-of select="ns6:improvementReasonCodeId"/>
                  </ns6:improvementReasonCodeId>
                </xsl:if>
                <xsl:if test="ns6:improvementReasonCodeKey">
                  <ns6:improvementReasonCodeKey>
                    <xsl:value-of select="ns6:improvementReasonCodeKey"/>
                  </ns6:improvementReasonCodeKey>
                </xsl:if>
                <xsl:if test="ns6:improvementReasonCodeLegend">
                  <ns6:improvementReasonCodeLegend>
                    <xsl:value-of select="ns6:improvementReasonCodeLegend"/>
                  </ns6:improvementReasonCodeLegend>
                </xsl:if>
                <xsl:if test="ns6:fixtureValue">
                  <ns6:fixtureValue>
                    <xsl:value-of select="ns6:fixtureValue"/>
                  </ns6:fixtureValue>
                </xsl:if>
                <xsl:if test="ns6:retainedLandValue">
                  <ns6:retainedLandValue>
                    <xsl:value-of select="ns6:retainedLandValue"/>
                  </ns6:retainedLandValue>
                </xsl:if>
                <xsl:if test="ns6:retainedImprovementValue">
                  <ns6:retainedImprovementValue>
                    <xsl:value-of select="ns6:retainedImprovementValue"/>
                  </ns6:retainedImprovementValue>
                </xsl:if>
                <xsl:if test="ns6:retainedFixtureValue">
                  <ns6:retainedFixtureValue>
                    <xsl:value-of select="ns6:retainedFixtureValue"/>
                  </ns6:retainedFixtureValue>
                </xsl:if>
                <xsl:if test="ns6:ppAssessmentNumber">
                  <ns6:ppAssessmentNumber>
                    <xsl:value-of select="ns6:ppAssessmentNumber"/>
                  </ns6:ppAssessmentNumber>
                </xsl:if>
                <xsl:if test="ns6:personalPropertyType">
                  <ns6:personalPropertyType>
                    <xsl:value-of select="ns6:personalPropertyType"/>
                  </ns6:personalPropertyType>
                </xsl:if>
                <xsl:if test="ns6:ppDescription">
                  <ns6:ppDescription>
                    <xsl:value-of select="ns6:ppDescription"/>
                  </ns6:ppDescription>
                </xsl:if>
                <xsl:if test="ns6:totalAdjAcquisitionCost">
                  <ns6:totalAdjAcquisitionCost>
                    <xsl:value-of select="ns6:totalAdjAcquisitionCost"/>
                  </ns6:totalAdjAcquisitionCost>
                </xsl:if>
                <xsl:if test="ns6:percentageFixture">
                  <ns6:percentageFixture>
                    <xsl:value-of select="ns6:percentageFixture"/>
                  </ns6:percentageFixture>
                </xsl:if>
                <xsl:if test="ns6:effectiveBeginDate">
                  <ns6:effectiveBeginDate>
                    <xsl:value-of select="ns6:effectiveBeginDate"/>
                  </ns6:effectiveBeginDate>
                </xsl:if>
                <xsl:if test="ns6:effectiveEndDate">
                  <ns6:effectiveEndDate>
                    <xsl:value-of select="ns6:effectiveEndDate"/>
                  </ns6:effectiveEndDate>
                </xsl:if>
                <xsl:if test="ns6:verificationDate">
                  <ns6:verificationDate>
                    <xsl:value-of select="ns6:verificationDate"/>
                  </ns6:verificationDate>
                </xsl:if>
                <xsl:if test="ns6:eventSource">
                  <ns6:eventSource>
                    <xsl:value-of select="ns6:eventSource"/>
                  </ns6:eventSource>
                </xsl:if>
                <xsl:if test="ns6:verifiedBy">
                  <ns6:verifiedBy>
                    <xsl:value-of select="ns6:verifiedBy"/>
                  </ns6:verifiedBy>
                </xsl:if>
                <xsl:if test="ns6:byeLegacySourceSystem">
                  <ns6:byeLegacySourceSystem>
                    <xsl:value-of select="ns6:byeLegacySourceSystem"/>
                  </ns6:byeLegacySourceSystem>
                </xsl:if>
                <xsl:if test="ns6:originalAIN">
                  <ns6:originalAIN>
                    <xsl:value-of select="ns6:originalAIN"/>
                  </ns6:originalAIN>
                </xsl:if>
                <xsl:if test="ns6:originalBYEId">
                  <ns6:originalBYEId>
                    <xsl:value-of select="ns6:originalBYEId"/>
                  </ns6:originalBYEId>
                </xsl:if>
                <xsl:if test="ns6:rollType">
                  <ns6:rollType>
                    <xsl:value-of select="ns6:rollType"/>
                  </ns6:rollType>
                </xsl:if>
                <xsl:if test="ns6:transactionType">
                  <ns6:transactionType>
                    <xsl:value-of select="ns6:transactionType"/>
                  </ns6:transactionType>
                </xsl:if>
                <xsl:if test="ns6:userId">
                  <ns6:userId>
                    <xsl:value-of select="ns6:userId"/>
                  </ns6:userId>
                </xsl:if>
                <xsl:if test="ns6:newConstructionDate">
                  <ns6:newConstructionDate>
                    <xsl:value-of select="ns6:newConstructionDate"/>
                  </ns6:newConstructionDate>
                </xsl:if>
                <xsl:if test="ns6:createBy">
                  <ns6:createBy>
                    <xsl:value-of select="ns6:createBy"/>
                  </ns6:createBy>
                </xsl:if>
                <xsl:if test="ns6:createdDate">
                  <ns6:createdDate>
                    <xsl:value-of select="ns6:createdDate"/>
                  </ns6:createdDate>
                </xsl:if>
                <xsl:if test="ns6:modifiedBy">
                  <ns6:modifiedBy>
                    <xsl:value-of select="ns6:modifiedBy"/>
                  </ns6:modifiedBy>
                </xsl:if>
                <xsl:if test="ns6:inactiveDate">
                  <ns6:inactiveDate>
                    <xsl:value-of select="ns6:inactiveDate"/>
                  </ns6:inactiveDate>
                </xsl:if>
                <xsl:if test="ns6:modifiedDate">
                  <ns6:modifiedDate>
                    <xsl:value-of select="ns6:modifiedDate"/>
                  </ns6:modifiedDate>
                </xsl:if>
                <xsl:if test="ns6:currentOnClose">
                  <ns6:currentOnClose>
                    <xsl:value-of select="ns6:currentOnClose"/>
                  </ns6:currentOnClose>
                </xsl:if>
                <xsl:if test="ns6:notes">
                  <ns6:notes>
                    <xsl:value-of select="ns6:notes"/>
                  </ns6:notes>
                </xsl:if>
                <xsl:if test="ns6:asmtRollId">
                  <ns6:asmtRollId>
                    <xsl:value-of select="ns6:asmtRollId"/>
                  </ns6:asmtRollId>
                </xsl:if>
              </ns1:baseYearEvent>
            </xsl:for-each>
          </ns1:baseYearEventList>
        </ns1:BYEDetailsOriginal>
        <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified">
          <ns1:BYEDetailsUserModified>
            <ns1:header>
              <ns8:operationStatus>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:header/ns8:operationStatus"/>
              </ns8:operationStatus>
              <ns8:instanceId>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:header/ns8:instanceId"/>
              </ns8:instanceId>
              <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:header/ns8:requestId">
                <ns8:requestId>
                  <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:header/ns8:requestId"/>
                </ns8:requestId>
              </xsl:if>
            </ns1:header>
            <ns1:ain>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:ain"/>
            </ns1:ain>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:aoid">
              <ns1:aoid>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:aoid"/>
              </ns1:aoid>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:ainType">
              <ns1:ainType>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:ainType"/>
              </ns1:ainType>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:reviewRequired">
              <ns1:reviewRequired>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:reviewRequired"/>
              </ns1:reviewRequired>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:processStatus">
              <ns1:processStatus>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:processStatus"/>
              </ns1:processStatus>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:ecid">
              <ns1:ecid>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:ecid"/>
              </ns1:ecid>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:dbLockStatus">
              <ns1:dbLockStatus>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:dbLockStatus"/>
              </ns1:dbLockStatus>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:lockedByUserId">
              <ns1:lockedByUserId>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:lockedByUserId"/>
              </ns1:lockedByUserId>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:districtId">
              <ns1:districtId>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:districtId"/>
              </ns1:districtId>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:districtName">
              <ns1:districtName>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:districtName"/>
              </ns1:districtName>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:region">
              <ns1:region>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:region"/>
              </ns1:region>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:regionName">
              <ns1:regionName>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:regionName"/>
              </ns1:regionName>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:clusterRouteId">
              <ns1:clusterRouteId>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:clusterRouteId"/>
              </ns1:clusterRouteId>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:clusterRoute">
              <ns1:clusterRoute>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:clusterRoute"/>
              </ns1:clusterRoute>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:clusterRouteName">
              <ns1:clusterRouteName>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:clusterRouteName"/>
              </ns1:clusterRouteName>
            </xsl:if>
            <ns1:isDirty>
              <xsl:text disable-output-escaping="no">false</xsl:text>
            </ns1:isDirty>
            <ns1:baseYearEventList>
              <xsl:for-each select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:baseYearEventList/ns1:baseYearEvent">
                <ns1:baseYearEvent>
                  <ns6:ain>
                    <xsl:value-of select="ns6:ain"/>
                  </ns6:ain>
                  <xsl:if test="ns6:aoid">
                    <ns6:aoid>
                      <xsl:value-of select="ns6:aoid"/>
                    </ns6:aoid>
                  </xsl:if>
                  <xsl:if test="ns6:reviewRequired">
                    <ns6:reviewRequired>
                      <xsl:value-of select="ns6:reviewRequired"/>
                    </ns6:reviewRequired>
                  </xsl:if>
                  <ns6:byeId>
                    <xsl:value-of select="ns6:byeId"/>
                  </ns6:byeId>
                  <xsl:if test="ns6:ownershipCode">
                    <ns6:ownershipCode>
                      <xsl:value-of select="ns6:ownershipCode"/>
                    </ns6:ownershipCode>
                  </xsl:if>
                  <xsl:if test="ns6:percentOwnership">
                    <ns6:percentOwnership>
                      <xsl:value-of select="ns6:percentOwnership"/>
                    </ns6:percentOwnership>
                  </xsl:if>
                  <xsl:if test="ns6:eventNameId">
                    <ns6:eventNameId>
                      <xsl:value-of select="ns6:eventNameId"/>
                    </ns6:eventNameId>
                  </xsl:if>
                  <xsl:if test="ns6:eventNameKey">
                    <ns6:eventNameKey>
                      <xsl:value-of select="ns6:eventNameKey"/>
                    </ns6:eventNameKey>
                  </xsl:if>
                  <xsl:if test="ns6:eventNameLegend">
                    <ns6:eventNameLegend>
                      <xsl:value-of select="ns6:eventNameLegend"/>
                    </ns6:eventNameLegend>
                  </xsl:if>
                  <xsl:if test="ns6:eventDescriptionId">
                    <ns6:eventDescriptionId>
                      <xsl:value-of select="ns6:eventDescriptionId"/>
                    </ns6:eventDescriptionId>
                  </xsl:if>
                  <xsl:if test="ns6:eventDescriptionKey">
                    <ns6:eventDescriptionKey>
                      <xsl:value-of select="ns6:eventDescriptionKey"/>
                    </ns6:eventDescriptionKey>
                  </xsl:if>
                  <xsl:if test="ns6:eventDescriptionLegend">
                    <ns6:eventDescriptionLegend>
                      <xsl:value-of select="ns6:eventDescriptionLegend"/>
                    </ns6:eventDescriptionLegend>
                  </xsl:if>
                  <xsl:if test="ns6:eventDate">
                    <ns6:eventDate>
                      <xsl:value-of select="ns6:eventDate"/>
                    </ns6:eventDate>
                  </xsl:if>
                  <xsl:if test="ns6:recordingDate">
                    <ns6:recordingDate>
                      <xsl:value-of select="ns6:recordingDate"/>
                    </ns6:recordingDate>
                  </xsl:if>
                  <xsl:if test="ns6:documentNumber">
                    <ns6:documentNumber>
                      <xsl:value-of select="ns6:documentNumber"/>
                    </ns6:documentNumber>
                  </xsl:if>
                  <xsl:if test="ns6:sequenceNumber">
                    <ns6:sequenceNumber>
                      <xsl:value-of select="ns6:sequenceNumber"/>
                    </ns6:sequenceNumber>
                  </xsl:if>
                  <xsl:if test="ns6:baseYear">
                    <ns6:baseYear>
                      <xsl:value-of select="ns6:baseYear"/>
                    </ns6:baseYear>
                  </xsl:if>
                  <xsl:if test="ns6:subUnitNumber">
                    <ns6:subUnitNumber>
                      <xsl:value-of select="ns6:subUnitNumber"/>
                    </ns6:subUnitNumber>
                  </xsl:if>
                  <xsl:if test="ns6:subUnitDescription">
                    <ns6:subUnitDescription>
                      <xsl:value-of select="ns6:subUnitDescription"/>
                    </ns6:subUnitDescription>
                  </xsl:if>
                  <xsl:if test="ns6:partiallyCompleteNumber">
                    <ns6:partiallyCompleteNumber>
                      <xsl:value-of select="ns6:partiallyCompleteNumber"/>
                    </ns6:partiallyCompleteNumber>
                  </xsl:if>
                  <xsl:if test="ns6:blendedValueFlag">
                    <ns6:blendedValueFlag>
                      <xsl:value-of select="ns6:blendedValueFlag"/>
                    </ns6:blendedValueFlag>
                  </xsl:if>
                  <xsl:if test="ns6:percentageAppliedToValue">
                    <ns6:percentageAppliedToValue>
                      <xsl:value-of select="ns6:percentageAppliedToValue"/>
                    </ns6:percentageAppliedToValue>
                  </xsl:if>
                  <xsl:if test="ns6:landValue">
                    <ns6:landValue>
                      <xsl:value-of select="ns6:landValue"/>
                    </ns6:landValue>
                  </xsl:if>
                  <xsl:if test="ns6:improvementValue">
                    <ns6:improvementValue>
                      <xsl:value-of select="ns6:improvementValue"/>
                    </ns6:improvementValue>
                  </xsl:if>
                  <xsl:if test="ns6:landReasonCodeId">
                    <ns6:landReasonCodeId>
                      <xsl:value-of select="ns6:landReasonCodeId"/>
                    </ns6:landReasonCodeId>
                  </xsl:if>
                  <xsl:if test="ns6:landReasonCodeKey">
                    <ns6:landReasonCodeKey>
                      <xsl:value-of select="ns6:landReasonCodeKey"/>
                    </ns6:landReasonCodeKey>
                  </xsl:if>
                  <xsl:if test="ns6:landReasonCodeLegend">
                    <ns6:landReasonCodeLegend>
                      <xsl:value-of select="ns6:landReasonCodeLegend"/>
                    </ns6:landReasonCodeLegend>
                  </xsl:if>
                  <xsl:if test="ns6:improvementReasonCodeId">
                    <ns6:improvementReasonCodeId>
                      <xsl:value-of select="ns6:improvementReasonCodeId"/>
                    </ns6:improvementReasonCodeId>
                  </xsl:if>
                  <xsl:if test="ns6:improvementReasonCodeKey">
                    <ns6:improvementReasonCodeKey>
                      <xsl:value-of select="ns6:improvementReasonCodeKey"/>
                    </ns6:improvementReasonCodeKey>
                  </xsl:if>
                  <xsl:if test="ns6:improvementReasonCodeLegend">
                    <ns6:improvementReasonCodeLegend>
                      <xsl:value-of select="ns6:improvementReasonCodeLegend"/>
                    </ns6:improvementReasonCodeLegend>
                  </xsl:if>
                  <xsl:if test="ns6:fixtureValue">
                    <ns6:fixtureValue>
                      <xsl:value-of select="ns6:fixtureValue"/>
                    </ns6:fixtureValue>
                  </xsl:if>
                  <xsl:if test="ns6:retainedLandValue">
                    <ns6:retainedLandValue>
                      <xsl:value-of select="ns6:retainedLandValue"/>
                    </ns6:retainedLandValue>
                  </xsl:if>
                  <xsl:if test="ns6:retainedImprovementValue">
                    <ns6:retainedImprovementValue>
                      <xsl:value-of select="ns6:retainedImprovementValue"/>
                    </ns6:retainedImprovementValue>
                  </xsl:if>
                  <xsl:if test="ns6:retainedFixtureValue">
                    <ns6:retainedFixtureValue>
                      <xsl:value-of select="ns6:retainedFixtureValue"/>
                    </ns6:retainedFixtureValue>
                  </xsl:if>
                  <xsl:if test="ns6:ppAssessmentNumber">
                    <ns6:ppAssessmentNumber>
                      <xsl:value-of select="ns6:ppAssessmentNumber"/>
                    </ns6:ppAssessmentNumber>
                  </xsl:if>
                  <xsl:if test="ns6:personalPropertyType">
                    <ns6:personalPropertyType>
                      <xsl:value-of select="ns6:personalPropertyType"/>
                    </ns6:personalPropertyType>
                  </xsl:if>
                  <xsl:if test="ns6:ppDescription">
                    <ns6:ppDescription>
                      <xsl:value-of select="ns6:ppDescription"/>
                    </ns6:ppDescription>
                  </xsl:if>
                  <xsl:if test="ns6:totalAdjAcquisitionCost">
                    <ns6:totalAdjAcquisitionCost>
                      <xsl:value-of select="ns6:totalAdjAcquisitionCost"/>
                    </ns6:totalAdjAcquisitionCost>
                  </xsl:if>
                  <xsl:if test="ns6:percentageFixture">
                    <ns6:percentageFixture>
                      <xsl:value-of select="ns6:percentageFixture"/>
                    </ns6:percentageFixture>
                  </xsl:if>
                  <xsl:if test="ns6:effectiveBeginDate">
                    <ns6:effectiveBeginDate>
                      <xsl:value-of select="ns6:effectiveBeginDate"/>
                    </ns6:effectiveBeginDate>
                  </xsl:if>
                  <xsl:if test="ns6:effectiveEndDate">
                    <ns6:effectiveEndDate>
                      <xsl:value-of select="ns6:effectiveEndDate"/>
                    </ns6:effectiveEndDate>
                  </xsl:if>
                  <xsl:if test="ns6:verificationDate">
                    <ns6:verificationDate>
                      <xsl:value-of select="ns6:verificationDate"/>
                    </ns6:verificationDate>
                  </xsl:if>
                  <xsl:if test="ns6:eventSource">
                    <ns6:eventSource>
                      <xsl:value-of select="ns6:eventSource"/>
                    </ns6:eventSource>
                  </xsl:if>
                  <xsl:if test="ns6:verifiedBy">
                    <ns6:verifiedBy>
                      <xsl:value-of select="ns6:verifiedBy"/>
                    </ns6:verifiedBy>
                  </xsl:if>
                  <xsl:if test="ns6:byeLegacySourceSystem">
                    <ns6:byeLegacySourceSystem>
                      <xsl:value-of select="ns6:byeLegacySourceSystem"/>
                    </ns6:byeLegacySourceSystem>
                  </xsl:if>
                  <xsl:if test="ns6:originalAIN">
                    <ns6:originalAIN>
                      <xsl:value-of select="ns6:originalAIN"/>
                    </ns6:originalAIN>
                  </xsl:if>
                  <xsl:if test="ns6:originalBYEId">
                    <ns6:originalBYEId>
                      <xsl:value-of select="ns6:originalBYEId"/>
                    </ns6:originalBYEId>
                  </xsl:if>
                  <xsl:if test="ns6:rollType">
                    <ns6:rollType>
                      <xsl:value-of select="ns6:rollType"/>
                    </ns6:rollType>
                  </xsl:if>
                  <xsl:if test="ns6:transactionType">
                    <ns6:transactionType>
                      <xsl:value-of select="ns6:transactionType"/>
                    </ns6:transactionType>
                  </xsl:if>
                  <xsl:if test="ns6:userId">
                    <ns6:userId>
                      <xsl:value-of select="ns6:userId"/>
                    </ns6:userId>
                  </xsl:if>
                  <xsl:if test="ns6:newConstructionDate">
                    <ns6:newConstructionDate>
                      <xsl:value-of select="ns6:newConstructionDate"/>
                    </ns6:newConstructionDate>
                  </xsl:if>
                  <xsl:if test="ns6:createBy">
                    <ns6:createBy>
                      <xsl:value-of select="ns6:createBy"/>
                    </ns6:createBy>
                  </xsl:if>
                  <xsl:if test="ns6:createdDate">
                    <ns6:createdDate>
                      <xsl:value-of select="ns6:createdDate"/>
                    </ns6:createdDate>
                  </xsl:if>
                  <xsl:if test="ns6:modifiedBy">
                    <ns6:modifiedBy>
                      <xsl:value-of select="ns6:modifiedBy"/>
                    </ns6:modifiedBy>
                  </xsl:if>
                  <xsl:if test="ns6:inactiveDate">
                    <ns6:inactiveDate>
                      <xsl:value-of select="ns6:inactiveDate"/>
                    </ns6:inactiveDate>
                  </xsl:if>
                  <xsl:if test="ns6:modifiedDate">
                    <ns6:modifiedDate>
                      <xsl:value-of select="ns6:modifiedDate"/>
                    </ns6:modifiedDate>
                  </xsl:if>
                  <xsl:if test="ns6:currentOnClose">
                    <ns6:currentOnClose>
                      <xsl:value-of select="ns6:currentOnClose"/>
                    </ns6:currentOnClose>
                  </xsl:if>
                  <xsl:if test="ns6:notes">
                    <ns6:notes>
                      <xsl:value-of select="ns6:notes"/>
                    </ns6:notes>
                  </xsl:if>
                  <xsl:if test="ns6:asmtRollId">
                    <ns6:asmtRollId>
                      <xsl:value-of select="ns6:asmtRollId"/>
                    </ns6:asmtRollId>
                  </xsl:if>
                </ns1:baseYearEvent>
              </xsl:for-each>
            </ns1:baseYearEventList>
          </ns1:BYEDetailsUserModified>
        </xsl:if>
      </ns1:RetrieveBYEDetails>
      <ns0:sortBYE>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <ns2:ain>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:ain/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:ain/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:ain"/>
        </ns2:ain>
        <ns2:district>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:district/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:district/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:district"/>
        </ns2:district>
        <ns2:region>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:region/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:region/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:region"/>
        </ns2:region>
        <ns2:cluster>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:cluster/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:cluster/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:cluster"/>
        </ns2:cluster>
        <ns2:noOfEvents>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:noOfEvents/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:noOfEvents/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:noOfEvents"/>
        </ns2:noOfEvents>
        <ns2:assignedBy>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:assignedBy/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:assignedBy/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:assignedBy"/>
        </ns2:assignedBy>
        <ns2:updatedBy>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedBy/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedBy/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedBy"/>
        </ns2:updatedBy>
        <ns2:updatedDate>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedDate/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedDate/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedDate"/>
        </ns2:updatedDate>
        <ns2:milestone>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:milestone/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:milestone/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:milestone"/>
        </ns2:milestone>
        <xsl:choose>
          <xsl:when test="contains($execData/tns:task/tns:systemAttributes/tns:outcome,&quot;SUBMIT&quot;)">
            <ns2:updatedByInfo>
              <xsl:value-of select="concat(concat($execData/tns:task/tns:systemAttributes/tns:updatedBy/tns:displayName,&quot; - &quot;),$execData/tns:task/tns:systemAttributes/tns:updatedDate)"/>
            </ns2:updatedByInfo>
          </xsl:when>
          <xsl:otherwise>
            <ns2:updatedByInfo>
              <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedByInfo/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedByInfo/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedByInfo"/>
            </ns2:updatedByInfo>
          </xsl:otherwise>
        </xsl:choose>
      </ns0:sortBYE>
      <ns0:assignTo_UserID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignTo_UserID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_UserID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_UserID"/>
      </ns0:assignTo_UserID>
      <ns0:assignTo_GroupID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignTo_GroupID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_GroupID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_GroupID"/>
      </ns0:assignTo_GroupID>
      <ns0:assignTo_ManagerID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignTo_ManagerID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_ManagerID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_ManagerID"/>
      </ns0:assignTo_ManagerID>
      <ns0:role>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:role/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:role/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:role"/>
      </ns0:role>
      <ns0:ownerID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:ownerID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:ownerID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:ownerID"/>
      </ns0:ownerID>
      <ns0:clientID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:clientID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:clientID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:clientID"/>
      </ns0:clientID>
      <ns0:checkBYE>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:checkBYE/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:checkBYE/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:checkBYE"/>
      </ns0:checkBYE>
      <ns0:userType>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:userType/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:userType/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:userType"/>
      </ns0:userType>
      <ns0:acquiredBy>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:acquiredBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:acquiredBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:acquiredBy"/>
      </ns0:acquiredBy>
      <ns0:returnTo>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:returnTo/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:returnTo/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:returnTo"/>
      </ns0:returnTo>
      <ns0:assignmentBox>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignmentBox/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignmentBox/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <ns3:assignmentBox_UserId>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:assignmentBox_UserId/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:assignmentBox_UserId/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:assignmentBox_UserId"/>
        </ns3:assignmentBox_UserId>
        <ns3:assignmentBox_GroupId>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:assignmentBox_GroupId/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:assignmentBox_GroupId/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:assignmentBox_GroupId"/>
        </ns3:assignmentBox_GroupId>
        <ns3:userType>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:userType/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:userType/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignmentBox/ns3:userType"/>
        </ns3:userType>
      </ns0:assignmentBox>
      <ns0:assignedBy>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignedBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignedBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignedBy"/>
      </ns0:assignedBy>
      <ns4:manageBYERequest>
        <ns4:header>
          <xsl:if test="/ns0:RetriveBYEDetails/ns4:manageBYERequest/ns4:header/ns7:applicationId">
            <ns7:applicationId>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns4:manageBYERequest/ns4:header/ns7:applicationId"/>
            </ns7:applicationId>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns4:manageBYERequest/ns4:header/ns7:requestId">
            <ns7:requestId>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns4:manageBYERequest/ns4:header/ns7:requestId"/>
            </ns7:requestId>
          </xsl:if>
        </ns4:header>
        <ns4:ain>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns4:manageBYERequest/ns4:ain"/>
        </ns4:ain>
        <xsl:if test="/ns0:RetriveBYEDetails/ns4:manageBYERequest/ns4:aoid">
          <ns4:aoid>
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns4:manageBYERequest/ns4:aoid"/>
          </ns4:aoid>
        </xsl:if>
        <xsl:if test="/ns0:RetriveBYEDetails/ns4:manageBYERequest/ns4:userId">
          <ns4:userId>
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns4:manageBYERequest/ns4:userId"/>
          </ns4:userId>
        </xsl:if>
        <xsl:if test="/ns0:RetriveBYEDetails/ns4:manageBYERequest/ns4:ownerId">
          <ns4:ownerId>
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns4:manageBYERequest/ns4:ownerId"/>
          </ns4:ownerId>
        </xsl:if>
        <ns4:processType>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns4:manageBYERequest/ns4:processType"/>
        </ns4:processType>
        <ns4:Source>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns4:manageBYERequest/ns4:Source"/>
        </ns4:Source>
      </ns4:manageBYERequest>
      <ns0:uiStateBO>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:uiStateBO/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:uiStateBO/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <ns5:key>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:uiStateBO/ns5:key/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:uiStateBO/ns5:key/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:uiStateBO/ns5:key"/>
        </ns5:key>
        <xsl:for-each select="/ns0:RetriveBYEDetails/ns0:uiStateBO/ns5:value">
          <ns5:value>
            <xsl:if test="@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="."/>
          </ns5:value>
        </xsl:for-each>
      </ns0:uiStateBO>
      <xsl:choose>
        <xsl:when test="contains($execData/tns:task/tns:systemAttributes/tns:outcome,&quot;SUBMIT&quot;)">
          <ns0:updatedBy>
            <xsl:value-of select="$execData/tns:task/tns:systemAttributes/tns:updatedBy/tns:id"/>
          </ns0:updatedBy>
        </xsl:when>
        <xsl:when test="contains($execData/tns:task/tns:systemAttributes/tns:outcome,&quot;ASSIGN&quot;)">
          <ns0:updatedBy>
            <xsl:value-of select="$execData/tns:task/tns:systemAttributes/tns:updatedBy/tns:id"/>
          </ns0:updatedBy>
        </xsl:when>
        <xsl:when test="contains($execData/tns:task/tns:systemAttributes/tns:outcome,&quot;APPROVE&quot;)">
          <ns0:updatedBy>
            <xsl:value-of select="$execData/tns:task/tns:systemAttributes/tns:updatedBy/tns:id"/>
          </ns0:updatedBy>
        </xsl:when>
        <xsl:when test="contains($execData/tns:task/tns:systemAttributes/tns:outcome,&quot;REJECT&quot;)">
          <ns0:updatedBy>
            <xsl:value-of select="$execData/tns:task/tns:systemAttributes/tns:updatedBy/tns:id"/>
          </ns0:updatedBy>
        </xsl:when>
        <xsl:when test="contains($execData/tns:task/tns:systemAttributes/tns:outcome,&quot;CANCEL&quot;)">
          <ns0:updatedBy>
            <xsl:value-of select="$execData/tns:task/tns:systemAttributes/tns:updatedBy/tns:id"/>
          </ns0:updatedBy>
        </xsl:when>
        <xsl:otherwise>
          <ns0:updatedBy>
            <xsl:text disable-output-escaping="no"/>
          </ns0:updatedBy>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="string-length($execData/tns:task/tns:systemAttributes/tns:acquiredBy) > 0.0">
          <ns0:claimedBy>
            <xsl:value-of select="$execData/tns:task/tns:systemAttributes/tns:acquiredBy"/>
          </ns0:claimedBy>
        </xsl:when>
        <xsl:otherwise>
          <ns0:claimedBy>
            <xsl:text disable-output-escaping="no"/>
          </ns0:claimedBy>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="contains($execData/tns:task/tns:systemAttributes/tns:outcome,&quot;APPROVE&quot;)">
          <ns0:approvedBy>
            <xsl:value-of select="$execData/tns:task/tns:systemAttributes/tns:updatedBy/tns:id"/>
          </ns0:approvedBy>
        </xsl:when>
        <xsl:otherwise>
          <ns0:approvedBy>
            <xsl:text disable-output-escaping="no"/>
          </ns0:approvedBy>
        </xsl:otherwise>
      </xsl:choose>
    </ns0:RetriveBYEDetails>
  </xsl:template>
</xsl:stylesheet>