<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns4="http://assessor.lacounty.gov/amp/type/common/ResponseHeader/v1.0" xmlns:ns3="http://xmlns.oracle.com/bpel/workflow/common" xmlns:evidence="http://xmlns.oracle.com/bpel/workflow/TaskEvidenceService" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:ns2="http://assessor.lacounty.gov/amp/type/common/RequestHeader/v1.0" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns6="http://xmlns.oracle.com/bpm/bpmobject/Data/SortBYEBO" xmlns:ns8="http://assessor.lacounty.gov/amp/data/ao/UpdateProcessStatus/v1.0" xmlns:ns0="http://xmlns.oracle.com/bpm/bpmobject/Data/AssignToUserOrGroupBO" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns5="http://assessor.lacounty.gov/amp/data/bvm/RetrieveBYE/v1.0" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns7="http://xmlns.oracle.com/bpm/bpmobject/Data/RetriveBYEDetails" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="http://assessor.lacounty.gov/amp/type/bvm/BaseYearEvent/v1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xmlns.oracle.com/bpel/workflow/task" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns4 ns3 evidence jaxb ns2 ns6 ns8 ns0 ns5 ns7 ns1 xsd tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/SubmitBaseYearEventTaskWorkflowTask.xsd"/>
            <oracle-xsl-mapper:rootElement name="task" namespace="http://xmlns.oracle.com/bpel/workflow/task"/>
            <oracle-xsl-mapper:param name="execData"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/ao/UpdateProcessStatus.xsd"/>
            <oracle-xsl-mapper:rootElement name="updateProcessStatusRequest" namespace="http://assessor.lacounty.gov/amp/data/ao/UpdateProcessStatus/v1.0"/>
            <oracle-xsl-mapper:param name="ProcessStatusPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/ao/UpdateProcessStatus.xsd"/>
            <oracle-xsl-mapper:rootElement name="updateProcessStatusRequest" namespace="http://assessor.lacounty.gov/amp/data/ao/UpdateProcessStatus/v1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 12:18:09 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="ProcessStatusPDO"/>
  <xsl:template match="/">
    <ns8:updateProcessStatusRequest>
      <ns8:header>
        <xsl:if test="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:header/ns2:applicationId">
          <ns2:applicationId>
            <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:header/ns2:applicationId"/>
          </ns2:applicationId>
        </xsl:if>
        <xsl:if test="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:header/ns2:requestId">
          <ns2:requestId>
            <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:header/ns2:requestId"/>
          </ns2:requestId>
        </xsl:if>
      </ns8:header>
      <ns8:ain>
        <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:ain"/>
      </ns8:ain>
      <ns8:aoid>
        <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:aoid"/>
      </ns8:aoid>
      <ns8:userId>
        <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:userId"/>
      </ns8:userId>
      <ns8:processType>
        <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:processType"/>
      </ns8:processType>
      <ns8:initiatedBy>
        <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:initiatedBy"/>
      </ns8:initiatedBy>
      <ns8:initiatedDate>
        <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:initiatedDate"/>
      </ns8:initiatedDate>
      <ns8:lockStatus>
        <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:lockStatus"/>
      </ns8:lockStatus>
      <ns8:lockStatusDate>
        <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:lockStatusDate"/>
      </ns8:lockStatusDate>
      <ns8:processName>
        <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:processName"/>
      </ns8:processName>
      <ns8:reviewedBy>
        <xsl:value-of select="/tns:task/tns:systemAttributes/tns:reviewers/tns:id"/>
      </ns8:reviewedBy>
      <ns8:reviewedDate>
        <xsl:value-of select="/tns:task/tns:systemAttributes/tns:assignedDate"/>
      </ns8:reviewedDate>
      <xsl:choose>
        <xsl:when test="contains(/tns:task/tns:systemAttributes/tns:outcome,&quot;SUBMIT&quot;)">
          <ns8:editBy>
            <xsl:value-of select="/tns:task/tns:systemAttributes/tns:updatedBy/tns:id"/>
          </ns8:editBy>
        </xsl:when>
        <xsl:otherwise>
          <ns8:editBy>
            <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:editBy"/>
          </ns8:editBy>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="contains(/tns:task/tns:systemAttributes/tns:outcome,&quot;SUBMIT&quot;)">
          <ns8:editDate>
            <xsl:value-of select="/tns:task/tns:systemAttributes/tns:updatedDate"/>
          </ns8:editDate>
        </xsl:when>
        <xsl:otherwise>
          <ns8:editDate>
            <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:editDate"/>
          </ns8:editDate>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="contains(/tns:task/tns:systemAttributes/tns:outcome,&quot;SUBMIT&quot;)">
          <ns8:editStatus>
            <xsl:value-of select="/tns:task/tns:systemAttributes/tns:outcome"/>
          </ns8:editStatus>
        </xsl:when>
        <xsl:otherwise>
          <ns8:editStatus>
            <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:editStatus"/>
          </ns8:editStatus>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="contains(/tns:task/tns:systemAttributes/tns:outcome,&quot;APPROVE&quot;)">
          <ns8:approvedBy>
            <xsl:value-of select="/tns:task/tns:systemAttributes/tns:updatedBy/tns:id"/>
          </ns8:approvedBy>
        </xsl:when>
        <xsl:otherwise>
          <ns8:approvedBy>
            <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:approvedBy"/>
          </ns8:approvedBy>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="contains(/tns:task/tns:systemAttributes/tns:outcome,&quot;APPROVE&quot;)">
          <ns8:approvedDate>
            <xsl:value-of select="/tns:task/tns:systemAttributes/tns:updatedDate"/>
          </ns8:approvedDate>
        </xsl:when>
        <xsl:otherwise>
          <ns8:approvedDate>
            <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:approvedDate"/>
          </ns8:approvedDate>
        </xsl:otherwise>
      </xsl:choose>
      <ns8:processAssignment>
        <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:processAssignment"/>
      </ns8:processAssignment>
      <ns8:processStatus>
        <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:processStatus"/>
      </ns8:processStatus>
      <ns8:processInstanceId>
        <xsl:value-of select="$ProcessStatusPDO/ns8:updateProcessStatusRequest/ns8:processInstanceId"/>
      </ns8:processInstanceId>
    </ns8:updateProcessStatusRequest>
  </xsl:template>
</xsl:stylesheet>