<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://assessor.lacounty.gov/amp/data/ao/WorkflowAssignment/v1.0" xmlns:inp2="http://assessor.lacounty.gov/amp/type/common/ResponseHeader/v1.0" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:inp1="http://assessor.lacounty.gov/amp/type/common/RequestHeader/v1.0" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:tns="http://assessor.lacounty.gov/amp/data/bvm/VerifyBYE/v1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:inp3="http://assessor.lacounty.gov/amp/type/bvm/BaseYearEvent/v1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ns0="http://assessor.lacounty.gov/amp/data/ao/UpsertWorkflowAssignment/v1.0" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl inp2 inp1 tns inp3 xsd ns1 ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/bvm/VerifyBYE.xsd"/>
            <oracle-xsl-mapper:rootElement name="verifyBYERequest" namespace="http://assessor.lacounty.gov/amp/data/bvm/VerifyBYE/v1.0"/>
            <oracle-xsl-mapper:param name="VerifyBYE_ReqPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/ao/UpsertWorkflowAssignment.xsd"/>
            <oracle-xsl-mapper:rootElement name="upsertWorkflowAssignmentRequest" namespace="http://assessor.lacounty.gov/amp/data/ao/UpsertWorkflowAssignment/v1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 12:18:09 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns0:upsertWorkflowAssignmentRequest>
      <ns0:header>
        <xsl:if test="/tns:verifyBYERequest/tns:header/inp1:applicationId">
          <inp1:applicationId>
            <xsl:value-of select="/tns:verifyBYERequest/tns:header/inp1:applicationId"/>
          </inp1:applicationId>
        </xsl:if>
        <xsl:if test="/tns:verifyBYERequest/tns:header/inp1:requestId">
          <inp1:requestId>
            <xsl:value-of select="/tns:verifyBYERequest/tns:header/inp1:requestId"/>
          </inp1:requestId>
        </xsl:if>
      </ns0:header>
      <ns0:transactionType>
        <xsl:text disable-output-escaping="no">D</xsl:text>
      </ns0:transactionType>
      <ns0:workflowAssignmentList>
        <ns0:assignment>
          <ns1:aoid>
            <xsl:value-of select="/tns:verifyBYERequest/tns:aoid"/>
          </ns1:aoid>
          <ns1:ain>
            <xsl:value-of select="/tns:verifyBYERequest/tns:ain"/>
          </ns1:ain>
          <ns1:processType>
            <xsl:value-of select="/tns:verifyBYERequest/tns:processType"/>
          </ns1:processType>
          <ns1:assignmentStatus>
            <xsl:text disable-output-escaping="no">COMPLETED</xsl:text>
          </ns1:assignmentStatus>
          <ns1:source>
            <xsl:value-of select="/tns:verifyBYERequest/tns:Source"/>
          </ns1:source>
        </ns0:assignment>
      </ns0:workflowAssignmentList>
    </ns0:upsertWorkflowAssignmentRequest>
  </xsl:template>
</xsl:stylesheet>