<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns8="http://xmlns.oracle.com/bpm/bpmobject/Data/UIStateBO" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns7="http://assessor.lacounty.gov/amp/type/common/ResponseHeader/v1.0" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:bpmo="http://xmlns.oracle.com/bpm/bpmobject/" xmlns:ns6="http://assessor.lacounty.gov/amp/type/common/RequestHeader/v1.0" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns2="http://xmlns.oracle.com/bpm/bpmobject/Data/SortBYEBO" xmlns:ns3="http://xmlns.oracle.com/bpm/bpmobject/Data/AssignToUserOrGroupBO" xmlns:tns="http://assessor.lacounty.gov/amp/data/bvm/VerifyBYE/v1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns1="http://assessor.lacounty.gov/amp/data/bvm/RetrieveBYE/v1.0" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns0="http://xmlns.oracle.com/bpm/bpmobject/Data/RetriveBYEDetails" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns5="http://assessor.lacounty.gov/amp/type/bvm/BaseYearEvent/v1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ns4="http://assessor.lacounty.gov/amp/data/bvm/ManageBYE/v1.0" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns8 ns7 bpmo ns6 ns2 ns3 tns ns1 ns0 ns5 xsd ns4 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/RetriveBYEDetails.xsd"/>
            <oracle-xsl-mapper:rootElement name="RetriveBYEDetails" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/RetriveBYEDetails"/>
            <oracle-xsl-mapper:param name="RetriveBYE_PDO"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/bvm/VerifyBYE.xsd"/>
            <oracle-xsl-mapper:rootElement name="verifyBYERequest" namespace="http://assessor.lacounty.gov/amp/data/bvm/VerifyBYE/v1.0"/>
            <oracle-xsl-mapper:param name="VerifyBYE_ReqPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/RetriveBYEDetails.xsd"/>
            <oracle-xsl-mapper:rootElement name="RetriveBYEDetails" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/RetriveBYEDetails"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 12:18:09 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="VerifyBYE_ReqPDO"/>
  <xsl:template match="/">
    <ns0:RetriveBYEDetails>
      <ns1:RetrieveBYEDetails>
        <ns1:BYEDetailsOriginal>
          <ns1:header>
            <ns7:operationStatus>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:header/ns7:operationStatus"/>
            </ns7:operationStatus>
            <ns7:instanceId>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:header/ns7:instanceId"/>
            </ns7:instanceId>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:header/ns7:requestId">
              <ns7:requestId>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:header/ns7:requestId"/>
              </ns7:requestId>
            </xsl:if>
          </ns1:header>
          <ns1:ain>
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:ain"/>
          </ns1:ain>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:aoid">
            <ns1:aoid>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:aoid"/>
            </ns1:aoid>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:ainType">
            <ns1:ainType>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:ainType"/>
            </ns1:ainType>
          </xsl:if>
          <ns1:reviewRequired>
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:reviewRequired"/>
          </ns1:reviewRequired>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:processStatus">
            <ns1:processStatus>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:processStatus"/>
            </ns1:processStatus>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:ecid">
            <ns1:ecid>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:ecid"/>
            </ns1:ecid>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:dbLockStatus">
            <ns1:dbLockStatus>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:dbLockStatus"/>
            </ns1:dbLockStatus>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:lockedByUserId">
            <ns1:lockedByUserId>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:lockedByUserId"/>
            </ns1:lockedByUserId>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtId">
            <ns1:districtId>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtId"/>
            </ns1:districtId>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtName">
            <ns1:districtName>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtName"/>
            </ns1:districtName>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:region">
            <ns1:region>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:region"/>
            </ns1:region>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:regionName">
            <ns1:regionName>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:regionName"/>
            </ns1:regionName>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:clusterRouteId">
            <ns1:clusterRouteId>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:clusterRouteId"/>
            </ns1:clusterRouteId>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:clusterRoute">
            <ns1:clusterRoute>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:clusterRoute"/>
            </ns1:clusterRoute>
          </xsl:if>
          <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:clusterRouteName">
            <ns1:clusterRouteName>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:clusterRouteName"/>
            </ns1:clusterRouteName>
          </xsl:if>
          <ns1:isDirty>
            <xsl:text disable-output-escaping="no">false</xsl:text>
          </ns1:isDirty>
          <ns1:baseYearEventList>
            <xsl:for-each select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:baseYearEventList/ns1:baseYearEvent">
              <ns1:baseYearEvent>
                <ns5:ain>
                  <xsl:value-of select="ns5:ain"/>
                </ns5:ain>
                <xsl:if test="ns5:aoid">
                  <ns5:aoid>
                    <xsl:value-of select="ns5:aoid"/>
                  </ns5:aoid>
                </xsl:if>
                <ns5:reviewRequired>
                  <xsl:value-of select="../../ns1:reviewRequired"/>
                </ns5:reviewRequired>
                <ns5:byeId>
                  <xsl:value-of select="ns5:byeId"/>
                </ns5:byeId>
                <xsl:if test="ns5:ownershipCode">
                  <ns5:ownershipCode>
                    <xsl:value-of select="ns5:ownershipCode"/>
                  </ns5:ownershipCode>
                </xsl:if>
                <xsl:if test="ns5:percentOwnership">
                  <ns5:percentOwnership>
                    <xsl:value-of select="ns5:percentOwnership"/>
                  </ns5:percentOwnership>
                </xsl:if>
                <xsl:if test="ns5:eventNameId">
                  <ns5:eventNameId>
                    <xsl:value-of select="ns5:eventNameId"/>
                  </ns5:eventNameId>
                </xsl:if>
                <xsl:if test="ns5:eventNameKey">
                  <ns5:eventNameKey>
                    <xsl:value-of select="ns5:eventNameKey"/>
                  </ns5:eventNameKey>
                </xsl:if>
                <xsl:if test="ns5:eventNameLegend">
                  <ns5:eventNameLegend>
                    <xsl:value-of select="ns5:eventNameLegend"/>
                  </ns5:eventNameLegend>
                </xsl:if>
                <xsl:if test="ns5:eventDescriptionId">
                  <ns5:eventDescriptionId>
                    <xsl:value-of select="ns5:eventDescriptionId"/>
                  </ns5:eventDescriptionId>
                </xsl:if>
                <xsl:if test="ns5:eventDescriptionKey">
                  <ns5:eventDescriptionKey>
                    <xsl:value-of select="ns5:eventDescriptionKey"/>
                  </ns5:eventDescriptionKey>
                </xsl:if>
                <xsl:if test="ns5:eventDescriptionLegend">
                  <ns5:eventDescriptionLegend>
                    <xsl:value-of select="ns5:eventDescriptionLegend"/>
                  </ns5:eventDescriptionLegend>
                </xsl:if>
                <xsl:if test="ns5:eventDate">
                  <ns5:eventDate>
                    <xsl:value-of select="ns5:eventDate"/>
                  </ns5:eventDate>
                </xsl:if>
                <xsl:if test="ns5:recordingDate">
                  <ns5:recordingDate>
                    <xsl:value-of select="ns5:recordingDate"/>
                  </ns5:recordingDate>
                </xsl:if>
                <xsl:if test="ns5:documentNumber">
                  <ns5:documentNumber>
                    <xsl:value-of select="ns5:documentNumber"/>
                  </ns5:documentNumber>
                </xsl:if>
                <xsl:if test="ns5:sequenceNumber">
                  <ns5:sequenceNumber>
                    <xsl:value-of select="ns5:sequenceNumber"/>
                  </ns5:sequenceNumber>
                </xsl:if>
                <xsl:if test="ns5:baseYear">
                  <ns5:baseYear>
                    <xsl:value-of select="ns5:baseYear"/>
                  </ns5:baseYear>
                </xsl:if>
                <xsl:if test="ns5:subUnitNumber">
                  <ns5:subUnitNumber>
                    <xsl:value-of select="ns5:subUnitNumber"/>
                  </ns5:subUnitNumber>
                </xsl:if>
                <xsl:if test="ns5:subUnitDescription">
                  <ns5:subUnitDescription>
                    <xsl:value-of select="ns5:subUnitDescription"/>
                  </ns5:subUnitDescription>
                </xsl:if>
                <xsl:if test="ns5:partiallyCompleteNumber">
                  <ns5:partiallyCompleteNumber>
                    <xsl:value-of select="ns5:partiallyCompleteNumber"/>
                  </ns5:partiallyCompleteNumber>
                </xsl:if>
                <xsl:if test="ns5:blendedValueFlag">
                  <ns5:blendedValueFlag>
                    <xsl:value-of select="ns5:blendedValueFlag"/>
                  </ns5:blendedValueFlag>
                </xsl:if>
                <xsl:if test="ns5:percentageAppliedToValue">
                  <ns5:percentageAppliedToValue>
                    <xsl:value-of select="ns5:percentageAppliedToValue"/>
                  </ns5:percentageAppliedToValue>
                </xsl:if>
                <xsl:if test="ns5:landValue">
                  <ns5:landValue>
                    <xsl:value-of select="ns5:landValue"/>
                  </ns5:landValue>
                </xsl:if>
                <xsl:if test="ns5:improvementValue">
                  <ns5:improvementValue>
                    <xsl:value-of select="ns5:improvementValue"/>
                  </ns5:improvementValue>
                </xsl:if>
                <xsl:if test="ns5:landReasonCodeId">
                  <ns5:landReasonCodeId>
                    <xsl:value-of select="ns5:landReasonCodeId"/>
                  </ns5:landReasonCodeId>
                </xsl:if>
                <xsl:if test="ns5:landReasonCodeKey">
                  <ns5:landReasonCodeKey>
                    <xsl:value-of select="ns5:landReasonCodeKey"/>
                  </ns5:landReasonCodeKey>
                </xsl:if>
                <xsl:if test="ns5:landReasonCodeLegend">
                  <ns5:landReasonCodeLegend>
                    <xsl:value-of select="ns5:landReasonCodeLegend"/>
                  </ns5:landReasonCodeLegend>
                </xsl:if>
                <xsl:if test="ns5:improvementReasonCodeId">
                  <ns5:improvementReasonCodeId>
                    <xsl:value-of select="ns5:improvementReasonCodeId"/>
                  </ns5:improvementReasonCodeId>
                </xsl:if>
                <xsl:if test="ns5:improvementReasonCodeKey">
                  <ns5:improvementReasonCodeKey>
                    <xsl:value-of select="ns5:improvementReasonCodeKey"/>
                  </ns5:improvementReasonCodeKey>
                </xsl:if>
                <xsl:if test="ns5:improvementReasonCodeLegend">
                  <ns5:improvementReasonCodeLegend>
                    <xsl:value-of select="ns5:improvementReasonCodeLegend"/>
                  </ns5:improvementReasonCodeLegend>
                </xsl:if>
                <xsl:if test="ns5:fixtureValue">
                  <ns5:fixtureValue>
                    <xsl:value-of select="ns5:fixtureValue"/>
                  </ns5:fixtureValue>
                </xsl:if>
                <xsl:if test="ns5:retainedLandValue">
                  <ns5:retainedLandValue>
                    <xsl:value-of select="ns5:retainedLandValue"/>
                  </ns5:retainedLandValue>
                </xsl:if>
                <xsl:if test="ns5:retainedImprovementValue">
                  <ns5:retainedImprovementValue>
                    <xsl:value-of select="ns5:retainedImprovementValue"/>
                  </ns5:retainedImprovementValue>
                </xsl:if>
                <xsl:if test="ns5:retainedFixtureValue">
                  <ns5:retainedFixtureValue>
                    <xsl:value-of select="ns5:retainedFixtureValue"/>
                  </ns5:retainedFixtureValue>
                </xsl:if>
                <xsl:if test="ns5:ppAssessmentNumber">
                  <ns5:ppAssessmentNumber>
                    <xsl:value-of select="ns5:ppAssessmentNumber"/>
                  </ns5:ppAssessmentNumber>
                </xsl:if>
                <xsl:if test="ns5:personalPropertyType">
                  <ns5:personalPropertyType>
                    <xsl:value-of select="ns5:personalPropertyType"/>
                  </ns5:personalPropertyType>
                </xsl:if>
                <xsl:if test="ns5:ppDescription">
                  <ns5:ppDescription>
                    <xsl:value-of select="ns5:ppDescription"/>
                  </ns5:ppDescription>
                </xsl:if>
                <xsl:if test="ns5:totalAdjAcquisitionCost">
                  <ns5:totalAdjAcquisitionCost>
                    <xsl:value-of select="ns5:totalAdjAcquisitionCost"/>
                  </ns5:totalAdjAcquisitionCost>
                </xsl:if>
                <xsl:if test="ns5:percentageFixture">
                  <ns5:percentageFixture>
                    <xsl:value-of select="ns5:percentageFixture"/>
                  </ns5:percentageFixture>
                </xsl:if>
                <xsl:if test="ns5:effectiveBeginDate">
                  <ns5:effectiveBeginDate>
                    <xsl:value-of select="ns5:effectiveBeginDate"/>
                  </ns5:effectiveBeginDate>
                </xsl:if>
                <xsl:if test="ns5:effectiveEndDate">
                  <ns5:effectiveEndDate>
                    <xsl:value-of select="ns5:effectiveEndDate"/>
                  </ns5:effectiveEndDate>
                </xsl:if>
                <xsl:if test="ns5:verificationDate">
                  <ns5:verificationDate>
                    <xsl:value-of select="ns5:verificationDate"/>
                  </ns5:verificationDate>
                </xsl:if>
                <xsl:if test="ns5:eventSource">
                  <ns5:eventSource>
                    <xsl:value-of select="ns5:eventSource"/>
                  </ns5:eventSource>
                </xsl:if>
                <xsl:if test="ns5:verifiedBy">
                  <ns5:verifiedBy>
                    <xsl:value-of select="ns5:verifiedBy"/>
                  </ns5:verifiedBy>
                </xsl:if>
                <xsl:if test="ns5:byeLegacySourceSystem">
                  <ns5:byeLegacySourceSystem>
                    <xsl:value-of select="ns5:byeLegacySourceSystem"/>
                  </ns5:byeLegacySourceSystem>
                </xsl:if>
                <xsl:if test="ns5:originalAIN">
                  <ns5:originalAIN>
                    <xsl:value-of select="ns5:originalAIN"/>
                  </ns5:originalAIN>
                </xsl:if>
                <xsl:if test="ns5:originalBYEId">
                  <ns5:originalBYEId>
                    <xsl:value-of select="ns5:originalBYEId"/>
                  </ns5:originalBYEId>
                </xsl:if>
                <xsl:if test="ns5:rollType">
                  <ns5:rollType>
                    <xsl:value-of select="ns5:rollType"/>
                  </ns5:rollType>
                </xsl:if>
                <ns5:transactionType>
                  <xsl:value-of select="ns5:transactionType"/>
                </ns5:transactionType>
                <xsl:if test="ns5:userId">
                  <ns5:userId>
                    <xsl:value-of select="ns5:userId"/>
                  </ns5:userId>
                </xsl:if>
                <xsl:if test="ns5:newConstructionDate">
                  <ns5:newConstructionDate>
                    <xsl:value-of select="ns5:newConstructionDate"/>
                  </ns5:newConstructionDate>
                </xsl:if>
                <xsl:if test="ns5:createBy">
                  <ns5:createBy>
                    <xsl:value-of select="ns5:createBy"/>
                  </ns5:createBy>
                </xsl:if>
                <xsl:if test="ns5:createdDate">
                  <ns5:createdDate>
                    <xsl:value-of select="ns5:createdDate"/>
                  </ns5:createdDate>
                </xsl:if>
                <xsl:if test="ns5:modifiedBy">
                  <ns5:modifiedBy>
                    <xsl:value-of select="ns5:modifiedBy"/>
                  </ns5:modifiedBy>
                </xsl:if>
                <xsl:if test="ns5:inactiveDate">
                  <ns5:inactiveDate>
                    <xsl:value-of select="ns5:inactiveDate"/>
                  </ns5:inactiveDate>
                </xsl:if>
                <xsl:if test="ns5:modifiedDate">
                  <ns5:modifiedDate>
                    <xsl:value-of select="ns5:modifiedDate"/>
                  </ns5:modifiedDate>
                </xsl:if>
                <ns5:currentOnClose>
                  <xsl:value-of select="ns5:currentOnClose"/>
                </ns5:currentOnClose>
                <xsl:if test="ns5:notes">
                  <ns5:notes>
                    <xsl:value-of select="ns5:notes"/>
                  </ns5:notes>
                </xsl:if>
              </ns1:baseYearEvent>
            </xsl:for-each>
          </ns1:baseYearEventList>
        </ns1:BYEDetailsOriginal>
        <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified">
          <ns1:BYEDetailsUserModified>
            <ns1:header>
              <ns7:operationStatus>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:header/ns7:operationStatus"/>
              </ns7:operationStatus>
              <ns7:instanceId>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:header/ns7:instanceId"/>
              </ns7:instanceId>
              <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:header/ns7:requestId">
                <ns7:requestId>
                  <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:header/ns7:requestId"/>
                </ns7:requestId>
              </xsl:if>
            </ns1:header>
            <ns1:ain>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:ain"/>
            </ns1:ain>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:aoid">
              <ns1:aoid>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:aoid"/>
              </ns1:aoid>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:ainType">
              <ns1:ainType>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:ainType"/>
              </ns1:ainType>
            </xsl:if>
            <ns1:reviewRequired>
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:reviewRequired"/>
            </ns1:reviewRequired>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:processStatus">
              <ns1:processStatus>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:processStatus"/>
              </ns1:processStatus>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:ecid">
              <ns1:ecid>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:ecid"/>
              </ns1:ecid>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:dbLockStatus">
              <ns1:dbLockStatus>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:dbLockStatus"/>
              </ns1:dbLockStatus>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:lockedByUserId">
              <ns1:lockedByUserId>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:lockedByUserId"/>
              </ns1:lockedByUserId>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:districtId">
              <ns1:districtId>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:districtId"/>
              </ns1:districtId>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:districtName">
              <ns1:districtName>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:districtName"/>
              </ns1:districtName>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:region">
              <ns1:region>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:region"/>
              </ns1:region>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:regionName">
              <ns1:regionName>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:regionName"/>
              </ns1:regionName>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:clusterRouteId">
              <ns1:clusterRouteId>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:clusterRouteId"/>
              </ns1:clusterRouteId>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:clusterRoute">
              <ns1:clusterRoute>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:clusterRoute"/>
              </ns1:clusterRoute>
            </xsl:if>
            <xsl:if test="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:clusterRouteName">
              <ns1:clusterRouteName>
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:clusterRouteName"/>
              </ns1:clusterRouteName>
            </xsl:if>
            <ns1:isDirty>
              <xsl:text disable-output-escaping="no">false</xsl:text>
            </ns1:isDirty>
            <ns1:baseYearEventList>
              <xsl:for-each select="/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsUserModified/ns1:baseYearEventList/ns1:baseYearEvent">
                <ns1:baseYearEvent>
                  <ns5:ain>
                    <xsl:value-of select="ns5:ain"/>
                  </ns5:ain>
                  <xsl:if test="ns5:aoid">
                    <ns5:aoid>
                      <xsl:value-of select="ns5:aoid"/>
                    </ns5:aoid>
                  </xsl:if>
                  <ns5:reviewRequired>
                    <xsl:value-of select="../../ns1:reviewRequired"/>
                  </ns5:reviewRequired>
                  <ns5:byeId>
                    <xsl:value-of select="ns5:byeId"/>
                  </ns5:byeId>
                  <xsl:if test="ns5:ownershipCode">
                    <ns5:ownershipCode>
                      <xsl:value-of select="ns5:ownershipCode"/>
                    </ns5:ownershipCode>
                  </xsl:if>
                  <xsl:if test="ns5:percentOwnership">
                    <ns5:percentOwnership>
                      <xsl:value-of select="ns5:percentOwnership"/>
                    </ns5:percentOwnership>
                  </xsl:if>
                  <xsl:if test="ns5:eventNameId">
                    <ns5:eventNameId>
                      <xsl:value-of select="ns5:eventNameId"/>
                    </ns5:eventNameId>
                  </xsl:if>
                  <xsl:if test="ns5:eventNameKey">
                    <ns5:eventNameKey>
                      <xsl:value-of select="ns5:eventNameKey"/>
                    </ns5:eventNameKey>
                  </xsl:if>
                  <xsl:if test="ns5:eventNameLegend">
                    <ns5:eventNameLegend>
                      <xsl:value-of select="ns5:eventNameLegend"/>
                    </ns5:eventNameLegend>
                  </xsl:if>
                  <xsl:if test="ns5:eventDescriptionId">
                    <ns5:eventDescriptionId>
                      <xsl:value-of select="ns5:eventDescriptionId"/>
                    </ns5:eventDescriptionId>
                  </xsl:if>
                  <xsl:if test="ns5:eventDescriptionKey">
                    <ns5:eventDescriptionKey>
                      <xsl:value-of select="ns5:eventDescriptionKey"/>
                    </ns5:eventDescriptionKey>
                  </xsl:if>
                  <xsl:if test="ns5:eventDescriptionLegend">
                    <ns5:eventDescriptionLegend>
                      <xsl:value-of select="ns5:eventDescriptionLegend"/>
                    </ns5:eventDescriptionLegend>
                  </xsl:if>
                  <xsl:if test="ns5:eventDate">
                    <ns5:eventDate>
                      <xsl:value-of select="ns5:eventDate"/>
                    </ns5:eventDate>
                  </xsl:if>
                  <xsl:if test="ns5:recordingDate">
                    <ns5:recordingDate>
                      <xsl:value-of select="ns5:recordingDate"/>
                    </ns5:recordingDate>
                  </xsl:if>
                  <xsl:if test="ns5:documentNumber">
                    <ns5:documentNumber>
                      <xsl:value-of select="ns5:documentNumber"/>
                    </ns5:documentNumber>
                  </xsl:if>
                  <xsl:if test="ns5:sequenceNumber">
                    <ns5:sequenceNumber>
                      <xsl:value-of select="ns5:sequenceNumber"/>
                    </ns5:sequenceNumber>
                  </xsl:if>
                  <xsl:if test="ns5:baseYear">
                    <ns5:baseYear>
                      <xsl:value-of select="ns5:baseYear"/>
                    </ns5:baseYear>
                  </xsl:if>
                  <xsl:if test="ns5:subUnitNumber">
                    <ns5:subUnitNumber>
                      <xsl:value-of select="ns5:subUnitNumber"/>
                    </ns5:subUnitNumber>
                  </xsl:if>
                  <xsl:if test="ns5:subUnitDescription">
                    <ns5:subUnitDescription>
                      <xsl:value-of select="ns5:subUnitDescription"/>
                    </ns5:subUnitDescription>
                  </xsl:if>
                  <xsl:if test="ns5:partiallyCompleteNumber">
                    <ns5:partiallyCompleteNumber>
                      <xsl:value-of select="ns5:partiallyCompleteNumber"/>
                    </ns5:partiallyCompleteNumber>
                  </xsl:if>
                  <xsl:if test="ns5:blendedValueFlag">
                    <ns5:blendedValueFlag>
                      <xsl:value-of select="ns5:blendedValueFlag"/>
                    </ns5:blendedValueFlag>
                  </xsl:if>
                  <xsl:if test="ns5:percentageAppliedToValue">
                    <ns5:percentageAppliedToValue>
                      <xsl:value-of select="ns5:percentageAppliedToValue"/>
                    </ns5:percentageAppliedToValue>
                  </xsl:if>
                  <xsl:if test="ns5:landValue">
                    <ns5:landValue>
                      <xsl:value-of select="ns5:landValue"/>
                    </ns5:landValue>
                  </xsl:if>
                  <xsl:if test="ns5:improvementValue">
                    <ns5:improvementValue>
                      <xsl:value-of select="ns5:improvementValue"/>
                    </ns5:improvementValue>
                  </xsl:if>
                  <xsl:if test="ns5:landReasonCodeId">
                    <ns5:landReasonCodeId>
                      <xsl:value-of select="ns5:landReasonCodeId"/>
                    </ns5:landReasonCodeId>
                  </xsl:if>
                  <xsl:if test="ns5:landReasonCodeKey">
                    <ns5:landReasonCodeKey>
                      <xsl:value-of select="ns5:landReasonCodeKey"/>
                    </ns5:landReasonCodeKey>
                  </xsl:if>
                  <xsl:if test="ns5:landReasonCodeLegend">
                    <ns5:landReasonCodeLegend>
                      <xsl:value-of select="ns5:landReasonCodeLegend"/>
                    </ns5:landReasonCodeLegend>
                  </xsl:if>
                  <xsl:if test="ns5:improvementReasonCodeId">
                    <ns5:improvementReasonCodeId>
                      <xsl:value-of select="ns5:improvementReasonCodeId"/>
                    </ns5:improvementReasonCodeId>
                  </xsl:if>
                  <xsl:if test="ns5:improvementReasonCodeKey">
                    <ns5:improvementReasonCodeKey>
                      <xsl:value-of select="ns5:improvementReasonCodeKey"/>
                    </ns5:improvementReasonCodeKey>
                  </xsl:if>
                  <xsl:if test="ns5:improvementReasonCodeLegend">
                    <ns5:improvementReasonCodeLegend>
                      <xsl:value-of select="ns5:improvementReasonCodeLegend"/>
                    </ns5:improvementReasonCodeLegend>
                  </xsl:if>
                  <xsl:if test="ns5:fixtureValue">
                    <ns5:fixtureValue>
                      <xsl:value-of select="ns5:fixtureValue"/>
                    </ns5:fixtureValue>
                  </xsl:if>
                  <xsl:if test="ns5:retainedLandValue">
                    <ns5:retainedLandValue>
                      <xsl:value-of select="ns5:retainedLandValue"/>
                    </ns5:retainedLandValue>
                  </xsl:if>
                  <xsl:if test="ns5:retainedImprovementValue">
                    <ns5:retainedImprovementValue>
                      <xsl:value-of select="ns5:retainedImprovementValue"/>
                    </ns5:retainedImprovementValue>
                  </xsl:if>
                  <xsl:if test="ns5:retainedFixtureValue">
                    <ns5:retainedFixtureValue>
                      <xsl:value-of select="ns5:retainedFixtureValue"/>
                    </ns5:retainedFixtureValue>
                  </xsl:if>
                  <xsl:if test="ns5:ppAssessmentNumber">
                    <ns5:ppAssessmentNumber>
                      <xsl:value-of select="ns5:ppAssessmentNumber"/>
                    </ns5:ppAssessmentNumber>
                  </xsl:if>
                  <xsl:if test="ns5:personalPropertyType">
                    <ns5:personalPropertyType>
                      <xsl:value-of select="ns5:personalPropertyType"/>
                    </ns5:personalPropertyType>
                  </xsl:if>
                  <xsl:if test="ns5:ppDescription">
                    <ns5:ppDescription>
                      <xsl:value-of select="ns5:ppDescription"/>
                    </ns5:ppDescription>
                  </xsl:if>
                  <xsl:if test="ns5:totalAdjAcquisitionCost">
                    <ns5:totalAdjAcquisitionCost>
                      <xsl:value-of select="ns5:totalAdjAcquisitionCost"/>
                    </ns5:totalAdjAcquisitionCost>
                  </xsl:if>
                  <xsl:if test="ns5:percentageFixture">
                    <ns5:percentageFixture>
                      <xsl:value-of select="ns5:percentageFixture"/>
                    </ns5:percentageFixture>
                  </xsl:if>
                  <xsl:if test="ns5:effectiveBeginDate">
                    <ns5:effectiveBeginDate>
                      <xsl:value-of select="ns5:effectiveBeginDate"/>
                    </ns5:effectiveBeginDate>
                  </xsl:if>
                  <xsl:if test="ns5:effectiveEndDate">
                    <ns5:effectiveEndDate>
                      <xsl:value-of select="ns5:effectiveEndDate"/>
                    </ns5:effectiveEndDate>
                  </xsl:if>
                  <xsl:if test="ns5:verificationDate">
                    <ns5:verificationDate>
                      <xsl:value-of select="ns5:verificationDate"/>
                    </ns5:verificationDate>
                  </xsl:if>
                  <xsl:if test="ns5:eventSource">
                    <ns5:eventSource>
                      <xsl:value-of select="ns5:eventSource"/>
                    </ns5:eventSource>
                  </xsl:if>
                  <xsl:if test="ns5:verifiedBy">
                    <ns5:verifiedBy>
                      <xsl:value-of select="ns5:verifiedBy"/>
                    </ns5:verifiedBy>
                  </xsl:if>
                  <xsl:if test="ns5:byeLegacySourceSystem">
                    <ns5:byeLegacySourceSystem>
                      <xsl:value-of select="ns5:byeLegacySourceSystem"/>
                    </ns5:byeLegacySourceSystem>
                  </xsl:if>
                  <xsl:if test="ns5:originalAIN">
                    <ns5:originalAIN>
                      <xsl:value-of select="ns5:originalAIN"/>
                    </ns5:originalAIN>
                  </xsl:if>
                  <xsl:if test="ns5:originalBYEId">
                    <ns5:originalBYEId>
                      <xsl:value-of select="ns5:originalBYEId"/>
                    </ns5:originalBYEId>
                  </xsl:if>
                  <xsl:if test="ns5:rollType">
                    <ns5:rollType>
                      <xsl:value-of select="ns5:rollType"/>
                    </ns5:rollType>
                  </xsl:if>
                  <ns5:transactionType>
                    <xsl:value-of select="ns5:transactionType"/>
                  </ns5:transactionType>
                  <xsl:if test="ns5:userId">
                    <ns5:userId>
                      <xsl:value-of select="ns5:userId"/>
                    </ns5:userId>
                  </xsl:if>
                  <xsl:if test="ns5:newConstructionDate">
                    <ns5:newConstructionDate>
                      <xsl:value-of select="ns5:newConstructionDate"/>
                    </ns5:newConstructionDate>
                  </xsl:if>
                  <xsl:if test="ns5:createBy">
                    <ns5:createBy>
                      <xsl:value-of select="ns5:createBy"/>
                    </ns5:createBy>
                  </xsl:if>
                  <xsl:if test="ns5:createdDate">
                    <ns5:createdDate>
                      <xsl:value-of select="ns5:createdDate"/>
                    </ns5:createdDate>
                  </xsl:if>
                  <xsl:if test="ns5:modifiedBy">
                    <ns5:modifiedBy>
                      <xsl:value-of select="ns5:modifiedBy"/>
                    </ns5:modifiedBy>
                  </xsl:if>
                  <xsl:if test="ns5:inactiveDate">
                    <ns5:inactiveDate>
                      <xsl:value-of select="ns5:inactiveDate"/>
                    </ns5:inactiveDate>
                  </xsl:if>
                  <xsl:if test="ns5:modifiedDate">
                    <ns5:modifiedDate>
                      <xsl:value-of select="ns5:modifiedDate"/>
                    </ns5:modifiedDate>
                  </xsl:if>
                  <ns5:currentOnClose>
                    <xsl:value-of select="ns5:currentOnClose"/>
                  </ns5:currentOnClose>
                  <xsl:if test="ns5:notes">
                    <ns5:notes>
                      <xsl:value-of select="ns5:notes"/>
                    </ns5:notes>
                  </xsl:if>
                  <xsl:if test="ns5:asmtRollId">
                    <ns5:asmtRollId>
                      <xsl:value-of select="ns5:asmtRollId"/>
                    </ns5:asmtRollId>
                  </xsl:if>
                </ns1:baseYearEvent>
              </xsl:for-each>
            </ns1:baseYearEventList>
          </ns1:BYEDetailsUserModified>
        </xsl:if>
      </ns1:RetrieveBYEDetails>
      <ns0:sortBYE>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <ns2:ain>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:ain/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:ain/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:ain"/>
        </ns2:ain>
        <ns2:district>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:district/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:district/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:district"/>
        </ns2:district>
        <ns2:region>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:region/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:region/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:region"/>
        </ns2:region>
        <ns2:cluster>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:cluster/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:cluster/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:cluster"/>
        </ns2:cluster>
        <ns2:noOfEvents>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:noOfEvents/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:noOfEvents/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:noOfEvents"/>
        </ns2:noOfEvents>
        <ns2:assignedBy>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:assignedBy/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:assignedBy/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:assignedBy"/>
        </ns2:assignedBy>
        <ns2:updatedBy>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedBy/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedBy/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedBy"/>
        </ns2:updatedBy>
        <ns2:updatedDate>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedDate/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedDate/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedDate"/>
        </ns2:updatedDate>
        <ns2:milestone>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:milestone/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:milestone/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:milestone"/>
        </ns2:milestone>
        <ns2:updatedByInfo>
          <xsl:if test="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedByInfo/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedByInfo/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:sortBYE/ns2:updatedByInfo"/>
        </ns2:updatedByInfo>
      </ns0:sortBYE>
      <ns0:assignTo_UserID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignTo_UserID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_UserID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_UserID"/>
      </ns0:assignTo_UserID>
      <ns0:assignTo_GroupID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignTo_GroupID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_GroupID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_GroupID"/>
      </ns0:assignTo_GroupID>
      <ns0:assignTo_ManagerID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignTo_ManagerID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_ManagerID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignTo_ManagerID"/>
      </ns0:assignTo_ManagerID>
      <ns0:role>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:role/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:role/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:role"/>
      </ns0:role>
      <ns0:ownerID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:ownerID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:ownerID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:ownerID"/>
      </ns0:ownerID>
      <ns0:clientID>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:clientID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:clientID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:clientID"/>
      </ns0:clientID>
      <ns0:checkBYE>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:checkBYE/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:checkBYE/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:checkBYE"/>
      </ns0:checkBYE>
      <ns0:userType>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:userType/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:userType/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:userType"/>
      </ns0:userType>
      <ns0:acquiredBy>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:acquiredBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:acquiredBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:acquiredBy"/>
      </ns0:acquiredBy>
      <xsl:choose>
        <xsl:when test="contains(/ns0:RetriveBYEDetails/ns0:returnTo,&quot;Manager&quot;)">
          <ns0:returnTo>
            <xsl:if test="/ns0:RetriveBYEDetails/ns0:returnTo/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:returnTo/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:returnTo"/>
          </ns0:returnTo>
        </xsl:when>
        <xsl:when test="contains(/ns0:RetriveBYEDetails/ns0:returnTo,&quot;District&quot;)">
          <ns0:returnTo>
            <xsl:if test="/ns0:RetriveBYEDetails/ns0:returnTo/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:returnTo/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:returnTo"/>
          </ns0:returnTo>
        </xsl:when>
        <xsl:otherwise>
          <ns0:returnTo>
            <xsl:text disable-output-escaping="no"/>
          </ns0:returnTo>
        </xsl:otherwise>
      </xsl:choose>
      <ns0:assignmentBox>
        <ns3:assignmentBox_UserId>
          <xsl:text disable-output-escaping="no"/>
        </ns3:assignmentBox_UserId>
        <ns3:assignmentBox_GroupId>
          <xsl:text disable-output-escaping="no"/>
        </ns3:assignmentBox_GroupId>
        <ns3:userType>
          <xsl:text disable-output-escaping="no"/>
        </ns3:userType>
      </ns0:assignmentBox>
      <ns0:assignedBy>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:assignedBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignedBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:assignedBy"/>
      </ns0:assignedBy>
      <ns0:submitBy>
        <xsl:if test="/ns0:RetriveBYEDetails/ns0:submitBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:submitBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:RetriveBYEDetails/ns0:submitBy"/>
      </ns0:submitBy>
      <ns4:manageBYERequest>
        <ns4:header>
          <xsl:if test="$VerifyBYE_ReqPDO/tns:verifyBYERequest/tns:header/ns6:applicationId">
            <ns6:applicationId>
              <xsl:value-of select="$VerifyBYE_ReqPDO/tns:verifyBYERequest/tns:header/ns6:applicationId"/>
            </ns6:applicationId>
          </xsl:if>
          <xsl:if test="$VerifyBYE_ReqPDO/tns:verifyBYERequest/tns:header/ns6:requestId">
            <ns6:requestId>
              <xsl:value-of select="$VerifyBYE_ReqPDO/tns:verifyBYERequest/tns:header/ns6:requestId"/>
            </ns6:requestId>
          </xsl:if>
        </ns4:header>
        <ns4:ain>
          <xsl:value-of select="$VerifyBYE_ReqPDO/tns:verifyBYERequest/tns:ain"/>
        </ns4:ain>
        <xsl:if test="$VerifyBYE_ReqPDO/tns:verifyBYERequest/tns:aoid">
          <ns4:aoid>
            <xsl:value-of select="$VerifyBYE_ReqPDO/tns:verifyBYERequest/tns:aoid"/>
          </ns4:aoid>
        </xsl:if>
        <xsl:if test="$VerifyBYE_ReqPDO/tns:verifyBYERequest/tns:userId">
          <ns4:userId>
            <xsl:value-of select="$VerifyBYE_ReqPDO/tns:verifyBYERequest/tns:userId"/>
          </ns4:userId>
        </xsl:if>
        <ns4:ownerId>
          <xsl:value-of select="$VerifyBYE_ReqPDO/tns:verifyBYERequest/tns:ownerId"/>
        </ns4:ownerId>
        <ns4:processType>
          <xsl:value-of select="$VerifyBYE_ReqPDO/tns:verifyBYERequest/tns:processType"/>
        </ns4:processType>
        <ns4:Source>
          <xsl:value-of select="$VerifyBYE_ReqPDO/tns:verifyBYERequest/tns:Source"/>
        </ns4:Source>
      </ns4:manageBYERequest>
    </ns0:RetriveBYEDetails>
  </xsl:template>
</xsl:stylesheet>