<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns9="http://xmlns.oracle.com/bpm/bpmobject/Data/AINAttributesBO" xmlns:ns7="http://assessor.lacounty.gov/amp/type/common/ResponseHeader/v1.0" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:bpmo="http://xmlns.oracle.com/bpm/bpmobject/" xmlns:ns6="http://assessor.lacounty.gov/amp/type/common/RequestHeader/v1.0" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns2="http://xmlns.oracle.com/bpm/bpmobject/Data/SortBYEBO" xmlns:ns3="http://xmlns.oracle.com/bpm/bpmobject/Data/AssignToUserOrGroupBO" xmlns:tns="http://assessor.lacounty.gov/amp/data/bvm/VerifyBYE/v1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns1="http://assessor.lacounty.gov/amp/data/bvm/RetrieveBYE/v1.0" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns0="http://xmlns.oracle.com/bpm/bpmobject/Data/RetriveBYEDetails" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns5="http://assessor.lacounty.gov/amp/type/bvm/BaseYearEvent/v1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ns4="http://assessor.lacounty.gov/amp/data/bvm/ManageBYE/v1.0" xmlns:ns8="http://xmlns.oracle.com/bpm/bpmobject/Data/InitiatorInfoBO" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns7 bpmo ns6 ns2 ns3 tns ns1 ns0 ns5 xsd ns4 ns8 ns9 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/RetriveBYEDetails.xsd"/>
            <oracle-xsl-mapper:rootElement name="RetriveBYEDetails" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/RetriveBYEDetails"/>
            <oracle-xsl-mapper:param name="RetriveBYE_PDO"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/InitiatorInfoBO.xsd"/>
            <oracle-xsl-mapper:rootElement name="InitiatorInfoBO" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/InitiatorInfoBO"/>
            <oracle-xsl-mapper:param name="InitiatorInfoPDO"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/bvm/VerifyBYE.xsd"/>
            <oracle-xsl-mapper:rootElement name="verifyBYERequest" namespace="http://assessor.lacounty.gov/amp/data/bvm/VerifyBYE/v1.0"/>
            <oracle-xsl-mapper:param name="VerifyBYE_ReqPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/AINAttributesBO.xsd"/>
            <oracle-xsl-mapper:rootElement name="AINAttributesBO" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/AINAttributesBO"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 12:18:09 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="InitiatorInfoPDO"/>
  <xsl:param name="VerifyBYE_ReqPDO"/>
  <xsl:template match="/">
    <ns9:AINAttributesBO>
      <xsl:choose>
        <xsl:when test="contains(/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtName,&quot;North&quot;)">
          <ns9:aINDistrict>
            <xsl:text disable-output-escaping="no">North</xsl:text>
          </ns9:aINDistrict>
        </xsl:when>
        <xsl:when test="contains(/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtName,&quot;South&quot;)">
          <ns9:aINDistrict>
            <xsl:text disable-output-escaping="no">South</xsl:text>
          </ns9:aINDistrict>
        </xsl:when>
        <xsl:when test="contains(/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtName,&quot;East&quot;)">
          <ns9:aINDistrict>
            <xsl:text disable-output-escaping="no">East</xsl:text>
          </ns9:aINDistrict>
        </xsl:when>
        <xsl:when test="contains(/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtName,&quot;West&quot;)">
          <ns9:aINDistrict>
            <xsl:text disable-output-escaping="no">West</xsl:text>
          </ns9:aINDistrict>
        </xsl:when>
        <xsl:when test="contains(/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtName,&quot;Lancaster&quot;)">
          <ns9:aINDistrict>
            <xsl:text disable-output-escaping="no">North</xsl:text>
          </ns9:aINDistrict>
        </xsl:when>
        <xsl:when test="contains(/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtName,&quot;Hall of Administration&quot;)">
          <ns9:aINDistrict>
            <xsl:text disable-output-escaping="no">HOA</xsl:text>
          </ns9:aINDistrict>
        </xsl:when>
        <xsl:when test="contains(/ns0:RetriveBYEDetails/ns1:RetrieveBYEDetails/ns1:BYEDetailsOriginal/ns1:districtName,&quot;Unknown&quot;)">
          <ns9:aINDistrict>
            <xsl:text disable-output-escaping="no">HOA</xsl:text>
          </ns9:aINDistrict>
        </xsl:when>
        <xsl:otherwise>
          <ns9:aINDistrict>
            <xsl:if test="$InitiatorInfoPDO/ns8:InitiatorInfoBO/ns8:initiatorDistrict/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="$InitiatorInfoPDO/ns8:InitiatorInfoBO/ns8:initiatorDistrict/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="$InitiatorInfoPDO/ns8:InitiatorInfoBO/ns8:initiatorDistrict"/>
          </ns9:aINDistrict>
        </xsl:otherwise>
      </xsl:choose>
      <!--ns9:initiatorDerivedRole>
        <xsl:if test="$InitiatorInfoPDO/ns8:InitiatorInfoBO/ns8:initiatorRole/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="$InitiatorInfoPDO/ns8:InitiatorInfoBO/ns8:initiatorRole/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="$InitiatorInfoPDO/ns8:InitiatorInfoBO/ns8:initiatorRole"/>
      </ns9:initiatorDerivedRole-->
    </ns9:AINAttributesBO>
  </xsl:template>
</xsl:stylesheet>