package gov.lacounty.assessor.amp.wsdl.bvm.baseyeareventrulesservice.v1;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 150302.2135.55683)

@WebServiceClient(wsdlLocation="http://localhost/soa-infra/services/amp/BaseYearEventRulesService/BaseYearEventRulesService_ep?wsdl",
  targetNamespace="http://assessor.lacounty.gov/amp/wsdl/bvm/BaseYearEventRulesService/v1.0",
  name="BaseYearEventRulesService_ep")
public class BaseYearEventRulesService_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("gov.lacounty.assessor.amp.wsdl.bvm.baseyeareventrulesservice.v1.BaseYearEventRulesService_ep");
      URL baseUrl = BaseYearEventRulesService_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            BaseYearEventRulesService_ep.class.getResource("http://localhost/soa-infra/services/amp/BaseYearEventRulesService/BaseYearEventRulesService_ep?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://localhost/soa-infra/services/amp/BaseYearEventRulesService/BaseYearEventRulesService_ep?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://localhost/soa-infra/services/amp/BaseYearEventRulesService/BaseYearEventRulesService_ep?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://localhost/soa-infra/services/amp/BaseYearEventRulesService/BaseYearEventRulesService_ep?wsdl",
          e);
    }
  }

  public BaseYearEventRulesService_ep()
  {
    super(wsdlLocationURL,
          new QName("http://assessor.lacounty.gov/amp/wsdl/bvm/BaseYearEventRulesService/v1.0",
                    "BaseYearEventRulesService_ep"));
  }

  public BaseYearEventRulesService_ep(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="BaseYearEventRulesService_pt")
  public BaseYearEventRulesService getBaseYearEventRulesService_pt()
  {
    return (BaseYearEventRulesService) super.getPort(new QName("http://assessor.lacounty.gov/amp/wsdl/bvm/BaseYearEventRulesService/v1.0",
                                                               "BaseYearEventRulesService_pt"),
                                                     BaseYearEventRulesService.class);
  }

  @WebEndpoint(name="BaseYearEventRulesService_pt")
  public BaseYearEventRulesService getBaseYearEventRulesService_pt(WebServiceFeature... features)
  {
    return (BaseYearEventRulesService) super.getPort(new QName("http://assessor.lacounty.gov/amp/wsdl/bvm/BaseYearEventRulesService/v1.0",
                                                               "BaseYearEventRulesService_pt"),
                                                     BaseYearEventRulesService.class,
                                                     features);
  }
}
