package gov.lacounty.assessor.amp.wsdl.bvm.baseyeareventrulesservice.v1;

import javax.xml.ws.WebFault;

@WebFault(faultBean="gov.lacounty.assessor.amp.type.common.fault.v1.Fault",
  targetNamespace="http://assessor.lacounty.gov/amp/wsdl/common/Fault/v1.0",
  name="fault")
public class FaultMessage
  extends Exception
{
  private gov.lacounty.assessor.amp.type.common.fault.v1.Fault faultInfo;

  public FaultMessage(String message,
                      gov.lacounty.assessor.amp.type.common.fault.v1.Fault faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public FaultMessage(String message,
                      gov.lacounty.assessor.amp.type.common.fault.v1.Fault faultInfo,
                      Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public gov.lacounty.assessor.amp.type.common.fault.v1.Fault getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(gov.lacounty.assessor.amp.type.common.fault.v1.Fault faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 150302.2135.55683)
