<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns4="http://xmlns.oracle.com/bpm/bpmobject/Data/PDCRHumanTaskBO" xmlns:ns7="http://assessor.lacounty.gov/amp/type/common/ResponseHeader/v1.0" xmlns:ns5="http://xmlns.oracle.com/bpel/workflow/common" xmlns:evidence="http://xmlns.oracle.com/bpel/workflow/TaskEvidenceService" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:bpmo="http://xmlns.oracle.com/bpm/bpmobject/" xmlns:ns1="http://assessor.lacounty.gov/amp/type/common/RealPropertyInfo/v1.0" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:ns3="http://assessor.lacounty.gov/amp/type/common/RequestHeader/v1.0" xmlns:ns6="http://xmlns.oracle.com/bpm/bpmobject/Data/SortPDCRBO" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://xmlns.oracle.com/bpm/bpmobject/Data/AssignToUserOrGroupBO" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns2="http://assessor.lacounty.gov/amp/data/ao/ManagePDCR/v1.0" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xmlns.oracle.com/bpel/workflow/task" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns4 ns7 ns5 evidence bpmo ns1 jaxb ns3 ns6 ns0 ns2 xsd tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/ReviewPropertyDataChangeRequestWorkflowTask.xsd"/>
            <oracle-xsl-mapper:rootElement name="task" namespace="http://xmlns.oracle.com/bpel/workflow/task"/>
            <oracle-xsl-mapper:param name="execData"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/PDCRHumanTaskBO.xsd"/>
            <oracle-xsl-mapper:rootElement name="PDCRHumanTaskBO" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/PDCRHumanTaskBO"/>
            <oracle-xsl-mapper:param name="HumanTaskPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/PDCRHumanTaskBO.xsd"/>
            <oracle-xsl-mapper:rootElement name="PDCRHumanTaskBO" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/PDCRHumanTaskBO"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 15:05:03 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="HumanTaskPDO"/>
  <xsl:template match="/">
    <ns4:PDCRHumanTaskBO>
      <ns2:managePDCRRequest>
        <ns2:header>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:header/ns3:applicationId">
            <ns3:applicationId>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:header/ns3:applicationId"/>
            </ns3:applicationId>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:header/ns3:requestId">
            <ns3:requestId>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:header/ns3:requestId"/>
            </ns3:requestId>
          </xsl:if>
        </ns2:header>
        <ns2:ain>
          <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:ain"/>
        </ns2:ain>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:aoid">
          <ns2:aoid>
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:aoid"/>
          </ns2:aoid>
        </xsl:if>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userId">
          <ns2:userId>
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userId"/>
          </ns2:userId>
        </xsl:if>
        <ns2:processType>
          <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:processType"/>
        </ns2:processType>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:actionType">
          <ns2:actionType>
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:actionType"/>
          </ns2:actionType>
        </xsl:if>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userType">
          <ns2:userType>
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userType"/>
          </ns2:userType>
        </xsl:if>
        <ns2:requestorInfo>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:requestorName">
            <ns2:requestorName>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:requestorName"/>
            </ns2:requestorName>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:requestorType">
            <ns2:requestorType>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:requestorType"/>
            </ns2:requestorType>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:Phone">
            <ns2:Phone>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:Phone"/>
            </ns2:Phone>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:email">
            <ns2:email>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:email"/>
            </ns2:email>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:reasonForRequest">
            <ns2:reasonForRequest>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:reasonForRequest"/>
            </ns2:reasonForRequest>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:comments">
            <ns2:comments>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:comments"/>
            </ns2:comments>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:dataChangeSource">
            <ns2:dataChangeSource>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:dataChangeSource"/>
            </ns2:dataChangeSource>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:preferredContact">
            <ns2:preferredContact>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:requestorInfo/ns2:preferredContact"/>
            </ns2:preferredContact>
          </xsl:if>
        </ns2:requestorInfo>
        <ns2:source>
          <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:source"/>
        </ns2:source>
        <ns2:originalRealPropertyInfo>
          <ns1:ain>
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:ain"/>
          </ns1:ain>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:aoid">
            <ns1:aoid>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:aoid"/>
            </ns1:aoid>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:region">
            <ns1:region>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:region"/>
            </ns1:region>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:cluster">
            <ns1:cluster>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:cluster"/>
            </ns1:cluster>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:propertyAddress">
            <ns1:propertyAddress>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:propertyAddress"/>
            </ns1:propertyAddress>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:district">
            <ns1:district>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:district"/>
            </ns1:district>
          </xsl:if>
          <ns1:subPartList>
            <xsl:for-each select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:subPartList/ns1:subPart">
              <ns1:subPart>
                <xsl:if test="ns1:dbUniqueId">
                  <ns1:dbUniqueId>
                    <xsl:value-of select="ns1:dbUniqueId"/>
                  </ns1:dbUniqueId>
                </xsl:if>
                <ns1:ain>
                  <xsl:value-of select="ns1:ain"/>
                </ns1:ain>
                <xsl:if test="ns1:aoid">
                  <ns1:aoid>
                    <xsl:value-of select="ns1:aoid"/>
                  </ns1:aoid>
                </xsl:if>
                <xsl:if test="ns1:transactionType">
                  <ns1:transactionType>
                    <xsl:value-of select="ns1:transactionType"/>
                  </ns1:transactionType>
                </xsl:if>
                <xsl:if test="ns1:improvementNumber">
                  <ns1:improvementNumber>
                    <xsl:value-of select="ns1:improvementNumber"/>
                  </ns1:improvementNumber>
                </xsl:if>
                <xsl:if test="ns1:subPartNumber">
                  <ns1:subPartNumber>
                    <xsl:value-of select="ns1:subPartNumber"/>
                  </ns1:subPartNumber>
                </xsl:if>
                <xsl:if test="ns1:rcnYearChange">
                  <ns1:rcnYearChange>
                    <xsl:value-of select="ns1:rcnYearChange"/>
                  </ns1:rcnYearChange>
                </xsl:if>
                <xsl:if test="ns1:designTypeRef">
                  <ns1:designTypeRef>
                    <xsl:value-of select="ns1:designTypeRef"/>
                  </ns1:designTypeRef>
                </xsl:if>
                <xsl:if test="ns1:designTypeKey">
                  <ns1:designTypeKey>
                    <xsl:value-of select="ns1:designTypeKey"/>
                  </ns1:designTypeKey>
                </xsl:if>
                <xsl:if test="ns1:designTypeLegend">
                  <ns1:designTypeLegend>
                    <xsl:value-of select="ns1:designTypeLegend"/>
                  </ns1:designTypeLegend>
                </xsl:if>
                <xsl:if test="ns1:qualityClass">
                  <ns1:qualityClass>
                    <xsl:value-of select="ns1:qualityClass"/>
                  </ns1:qualityClass>
                </xsl:if>
                <xsl:if test="ns1:yearBuilt">
                  <ns1:yearBuilt>
                    <xsl:value-of select="ns1:yearBuilt"/>
                  </ns1:yearBuilt>
                </xsl:if>
                <xsl:if test="ns1:effectiveYearBuilt">
                  <ns1:effectiveYearBuilt>
                    <xsl:value-of select="ns1:effectiveYearBuilt"/>
                  </ns1:effectiveYearBuilt>
                </xsl:if>
                <xsl:if test="ns1:depreciationTable">
                  <ns1:depreciationTable>
                    <xsl:value-of select="ns1:depreciationTable"/>
                  </ns1:depreciationTable>
                </xsl:if>
                <xsl:if test="ns1:numberOfUnits">
                  <ns1:numberOfUnits>
                    <xsl:value-of select="ns1:numberOfUnits"/>
                  </ns1:numberOfUnits>
                </xsl:if>
                <xsl:if test="ns1:bedroomCount">
                  <ns1:bedroomCount>
                    <xsl:value-of select="ns1:bedroomCount"/>
                  </ns1:bedroomCount>
                </xsl:if>
                <xsl:if test="ns1:bathroomCount">
                  <ns1:bathroomCount>
                    <xsl:value-of select="ns1:bathroomCount"/>
                  </ns1:bathroomCount>
                </xsl:if>
                <xsl:if test="ns1:improvementSizeSqft">
                  <ns1:improvementSizeSqft>
                    <xsl:value-of select="ns1:improvementSizeSqft"/>
                  </ns1:improvementSizeSqft>
                </xsl:if>
                <xsl:if test="ns1:rcnOtherTotal">
                  <ns1:rcnOtherTotal>
                    <xsl:value-of select="ns1:rcnOtherTotal"/>
                  </ns1:rcnOtherTotal>
                </xsl:if>
                <xsl:if test="ns1:costFactor">
                  <ns1:costFactor>
                    <xsl:value-of select="ns1:costFactor"/>
                  </ns1:costFactor>
                </xsl:if>
                <xsl:if test="ns1:rcnMain">
                  <ns1:rcnMain>
                    <xsl:value-of select="ns1:rcnMain"/>
                  </ns1:rcnMain>
                </xsl:if>
                <xsl:if test="ns1:percentGood">
                  <ns1:percentGood>
                    <xsl:value-of select="ns1:percentGood"/>
                  </ns1:percentGood>
                </xsl:if>
                <xsl:if test="ns1:addedDepreciationTypeRef">
                  <ns1:addedDepreciationTypeRef>
                    <xsl:value-of select="ns1:addedDepreciationTypeRef"/>
                  </ns1:addedDepreciationTypeRef>
                </xsl:if>
                <xsl:if test="ns1:addedDepreciationTypeKey">
                  <ns1:addedDepreciationTypeKey>
                    <xsl:value-of select="ns1:addedDepreciationTypeKey"/>
                  </ns1:addedDepreciationTypeKey>
                </xsl:if>
                <xsl:if test="ns1:addedDepreciationTypeLegend">
                  <ns1:addedDepreciationTypeLegend>
                    <xsl:value-of select="ns1:addedDepreciationTypeLegend"/>
                  </ns1:addedDepreciationTypeLegend>
                </xsl:if>
                <xsl:if test="ns1:addedDepreciationPercent">
                  <ns1:addedDepreciationPercent>
                    <xsl:value-of select="ns1:addedDepreciationPercent"/>
                  </ns1:addedDepreciationPercent>
                </xsl:if>
                <xsl:if test="ns1:rcnLessDepreciation">
                  <ns1:rcnLessDepreciation>
                    <xsl:value-of select="ns1:rcnLessDepreciation"/>
                  </ns1:rcnLessDepreciation>
                </xsl:if>
              </ns1:subPart>
            </xsl:for-each>
          </ns1:subPartList>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:composite">
            <ns1:composite>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:composite/ns1:dbUniqueId">
                <ns1:dbUniqueId>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:composite/ns1:dbUniqueId"/>
                </ns1:dbUniqueId>
              </xsl:if>
              <ns1:ain>
                <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:composite/ns1:ain"/>
              </ns1:ain>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:composite/ns1:aoid">
                <ns1:aoid>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:composite/ns1:aoid"/>
                </ns1:aoid>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:composite/ns1:transactionType">
                <ns1:transactionType>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:composite/ns1:transactionType"/>
                </ns1:transactionType>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:composite/ns1:sqft">
                <ns1:sqft>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:composite/ns1:sqft"/>
                </ns1:sqft>
              </xsl:if>
            </ns1:composite>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land">
            <ns1:land>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:dbUniqueId">
                <ns1:dbUniqueId>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:dbUniqueId"/>
                </ns1:dbUniqueId>
              </xsl:if>
              <ns1:ain>
                <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:ain"/>
              </ns1:ain>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:aoid">
                <ns1:aoid>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:aoid"/>
                </ns1:aoid>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:transactionType">
                <ns1:transactionType>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:transactionType"/>
                </ns1:transactionType>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:width">
                <ns1:width>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:width"/>
                </ns1:width>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:depth">
                <ns1:depth>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:depth"/>
                </ns1:depth>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:sizeSqft">
                <ns1:sizeSqft>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:sizeSqft"/>
                </ns1:sizeSqft>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:sizeUsableSqft">
                <ns1:sizeUsableSqft>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:sizeUsableSqft"/>
                </ns1:sizeUsableSqft>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:sizeAcreAge">
                <ns1:sizeAcreAge>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:sizeAcreAge"/>
                </ns1:sizeAcreAge>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:corner">
                <ns1:corner>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:corner"/>
                </ns1:corner>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:sewer">
                <ns1:sewer>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:sewer"/>
                </ns1:sewer>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:traffic">
                <ns1:traffic>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:traffic"/>
                </ns1:traffic>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:freewayProximity">
                <ns1:freewayProximity>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:freewayProximity"/>
                </ns1:freewayProximity>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:flightPath">
                <ns1:flightPath>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:flightPath"/>
                </ns1:flightPath>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:golfFront">
                <ns1:golfFront>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:golfFront"/>
                </ns1:golfFront>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:horses">
                <ns1:horses>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:horses"/>
                </ns1:horses>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:viewCodeKey">
                <ns1:viewCodeKey>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:viewCodeKey"/>
                </ns1:viewCodeKey>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:viewCodeRef">
                <ns1:viewCodeRef>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:viewCodeRef"/>
                </ns1:viewCodeRef>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:viewCodeLegend">
                <ns1:viewCodeLegend>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:viewCodeLegend"/>
                </ns1:viewCodeLegend>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:useCode">
                <ns1:useCode>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:useCode"/>
                </ns1:useCode>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:useType">
                <ns1:useType>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:useType"/>
                </ns1:useType>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:codeSplit">
                <ns1:codeSplit>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:originalRealPropertyInfo/ns1:land/ns1:codeSplit"/>
                </ns1:codeSplit>
              </xsl:if>
            </ns1:land>
          </xsl:if>
        </ns2:originalRealPropertyInfo>
        <ns2:userEnteredRealPropertyInfo>
          <ns1:ain>
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:ain"/>
          </ns1:ain>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:aoid">
            <ns1:aoid>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:aoid"/>
            </ns1:aoid>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:region">
            <ns1:region>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:region"/>
            </ns1:region>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:cluster">
            <ns1:cluster>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:cluster"/>
            </ns1:cluster>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:propertyAddress">
            <ns1:propertyAddress>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:propertyAddress"/>
            </ns1:propertyAddress>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:district">
            <ns1:district>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:district"/>
            </ns1:district>
          </xsl:if>
          <ns1:subPartList>
            <xsl:for-each select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:subPartList/ns1:subPart">
              <ns1:subPart>
                <xsl:if test="ns1:dbUniqueId">
                  <ns1:dbUniqueId>
                    <xsl:value-of select="ns1:dbUniqueId"/>
                  </ns1:dbUniqueId>
                </xsl:if>
                <ns1:ain>
                  <xsl:value-of select="ns1:ain"/>
                </ns1:ain>
                <xsl:if test="ns1:aoid">
                  <ns1:aoid>
                    <xsl:value-of select="ns1:aoid"/>
                  </ns1:aoid>
                </xsl:if>
                <xsl:if test="ns1:transactionType">
                  <ns1:transactionType>
                    <xsl:value-of select="ns1:transactionType"/>
                  </ns1:transactionType>
                </xsl:if>
                <xsl:if test="ns1:improvementNumber">
                  <ns1:improvementNumber>
                    <xsl:value-of select="ns1:improvementNumber"/>
                  </ns1:improvementNumber>
                </xsl:if>
                <xsl:if test="ns1:subPartNumber">
                  <ns1:subPartNumber>
                    <xsl:value-of select="ns1:subPartNumber"/>
                  </ns1:subPartNumber>
                </xsl:if>
                <xsl:if test="ns1:rcnYearChange">
                  <ns1:rcnYearChange>
                    <xsl:value-of select="ns1:rcnYearChange"/>
                  </ns1:rcnYearChange>
                </xsl:if>
                <xsl:if test="ns1:designTypeRef">
                  <ns1:designTypeRef>
                    <xsl:value-of select="ns1:designTypeRef"/>
                  </ns1:designTypeRef>
                </xsl:if>
                <xsl:if test="ns1:designTypeKey">
                  <ns1:designTypeKey>
                    <xsl:value-of select="ns1:designTypeKey"/>
                  </ns1:designTypeKey>
                </xsl:if>
                <xsl:if test="ns1:designTypeLegend">
                  <ns1:designTypeLegend>
                    <xsl:value-of select="ns1:designTypeLegend"/>
                  </ns1:designTypeLegend>
                </xsl:if>
                <xsl:if test="ns1:qualityClass">
                  <ns1:qualityClass>
                    <xsl:value-of select="ns1:qualityClass"/>
                  </ns1:qualityClass>
                </xsl:if>
                <xsl:if test="ns1:yearBuilt">
                  <ns1:yearBuilt>
                    <xsl:value-of select="ns1:yearBuilt"/>
                  </ns1:yearBuilt>
                </xsl:if>
                <xsl:if test="ns1:effectiveYearBuilt">
                  <ns1:effectiveYearBuilt>
                    <xsl:value-of select="ns1:effectiveYearBuilt"/>
                  </ns1:effectiveYearBuilt>
                </xsl:if>
                <xsl:if test="ns1:depreciationTable">
                  <ns1:depreciationTable>
                    <xsl:value-of select="ns1:depreciationTable"/>
                  </ns1:depreciationTable>
                </xsl:if>
                <xsl:if test="ns1:numberOfUnits">
                  <ns1:numberOfUnits>
                    <xsl:value-of select="ns1:numberOfUnits"/>
                  </ns1:numberOfUnits>
                </xsl:if>
                <xsl:if test="ns1:bedroomCount">
                  <ns1:bedroomCount>
                    <xsl:value-of select="ns1:bedroomCount"/>
                  </ns1:bedroomCount>
                </xsl:if>
                <xsl:if test="ns1:bathroomCount">
                  <ns1:bathroomCount>
                    <xsl:value-of select="ns1:bathroomCount"/>
                  </ns1:bathroomCount>
                </xsl:if>
                <xsl:if test="ns1:improvementSizeSqft">
                  <ns1:improvementSizeSqft>
                    <xsl:value-of select="ns1:improvementSizeSqft"/>
                  </ns1:improvementSizeSqft>
                </xsl:if>
                <xsl:if test="ns1:rcnOtherTotal">
                  <ns1:rcnOtherTotal>
                    <xsl:value-of select="ns1:rcnOtherTotal"/>
                  </ns1:rcnOtherTotal>
                </xsl:if>
                <xsl:if test="ns1:costFactor">
                  <ns1:costFactor>
                    <xsl:value-of select="ns1:costFactor"/>
                  </ns1:costFactor>
                </xsl:if>
                <xsl:if test="ns1:rcnMain">
                  <ns1:rcnMain>
                    <xsl:value-of select="ns1:rcnMain"/>
                  </ns1:rcnMain>
                </xsl:if>
                <xsl:if test="ns1:percentGood">
                  <ns1:percentGood>
                    <xsl:value-of select="ns1:percentGood"/>
                  </ns1:percentGood>
                </xsl:if>
                <xsl:if test="ns1:addedDepreciationTypeRef">
                  <ns1:addedDepreciationTypeRef>
                    <xsl:value-of select="ns1:addedDepreciationTypeRef"/>
                  </ns1:addedDepreciationTypeRef>
                </xsl:if>
                <xsl:if test="ns1:addedDepreciationTypeKey">
                  <ns1:addedDepreciationTypeKey>
                    <xsl:value-of select="ns1:addedDepreciationTypeKey"/>
                  </ns1:addedDepreciationTypeKey>
                </xsl:if>
                <xsl:if test="ns1:addedDepreciationTypeLegend">
                  <ns1:addedDepreciationTypeLegend>
                    <xsl:value-of select="ns1:addedDepreciationTypeLegend"/>
                  </ns1:addedDepreciationTypeLegend>
                </xsl:if>
                <xsl:if test="ns1:addedDepreciationPercent">
                  <ns1:addedDepreciationPercent>
                    <xsl:value-of select="ns1:addedDepreciationPercent"/>
                  </ns1:addedDepreciationPercent>
                </xsl:if>
                <xsl:if test="ns1:rcnLessDepreciation">
                  <ns1:rcnLessDepreciation>
                    <xsl:value-of select="ns1:rcnLessDepreciation"/>
                  </ns1:rcnLessDepreciation>
                </xsl:if>
              </ns1:subPart>
            </xsl:for-each>
          </ns1:subPartList>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:composite">
            <ns1:composite>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:composite/ns1:dbUniqueId">
                <ns1:dbUniqueId>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:composite/ns1:dbUniqueId"/>
                </ns1:dbUniqueId>
              </xsl:if>
              <ns1:ain>
                <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:composite/ns1:ain"/>
              </ns1:ain>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:composite/ns1:aoid">
                <ns1:aoid>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:composite/ns1:aoid"/>
                </ns1:aoid>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:composite/ns1:transactionType">
                <ns1:transactionType>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:composite/ns1:transactionType"/>
                </ns1:transactionType>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:composite/ns1:sqft">
                <ns1:sqft>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:composite/ns1:sqft"/>
                </ns1:sqft>
              </xsl:if>
            </ns1:composite>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land">
            <ns1:land>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:dbUniqueId">
                <ns1:dbUniqueId>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:dbUniqueId"/>
                </ns1:dbUniqueId>
              </xsl:if>
              <ns1:ain>
                <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:ain"/>
              </ns1:ain>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:aoid">
                <ns1:aoid>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:aoid"/>
                </ns1:aoid>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:transactionType">
                <ns1:transactionType>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:transactionType"/>
                </ns1:transactionType>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:width">
                <ns1:width>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:width"/>
                </ns1:width>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:depth">
                <ns1:depth>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:depth"/>
                </ns1:depth>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:sizeSqft">
                <ns1:sizeSqft>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:sizeSqft"/>
                </ns1:sizeSqft>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:sizeUsableSqft">
                <ns1:sizeUsableSqft>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:sizeUsableSqft"/>
                </ns1:sizeUsableSqft>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:sizeAcreAge">
                <ns1:sizeAcreAge>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:sizeAcreAge"/>
                </ns1:sizeAcreAge>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:corner">
                <ns1:corner>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:corner"/>
                </ns1:corner>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:sewer">
                <ns1:sewer>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:sewer"/>
                </ns1:sewer>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:traffic">
                <ns1:traffic>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:traffic"/>
                </ns1:traffic>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:freewayProximity">
                <ns1:freewayProximity>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:freewayProximity"/>
                </ns1:freewayProximity>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:flightPath">
                <ns1:flightPath>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:flightPath"/>
                </ns1:flightPath>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:golfFront">
                <ns1:golfFront>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:golfFront"/>
                </ns1:golfFront>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:horses">
                <ns1:horses>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:horses"/>
                </ns1:horses>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:viewCodeKey">
                <ns1:viewCodeKey>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:viewCodeKey"/>
                </ns1:viewCodeKey>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:viewCodeRef">
                <ns1:viewCodeRef>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:viewCodeRef"/>
                </ns1:viewCodeRef>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:viewCodeLegend">
                <ns1:viewCodeLegend>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:viewCodeLegend"/>
                </ns1:viewCodeLegend>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:useCode">
                <ns1:useCode>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:useCode"/>
                </ns1:useCode>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:useType">
                <ns1:useType>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:useType"/>
                </ns1:useType>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:codeSplit">
                <ns1:codeSplit>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:userEnteredRealPropertyInfo/ns1:land/ns1:codeSplit"/>
                </ns1:codeSplit>
              </xsl:if>
            </ns1:land>
          </xsl:if>
        </ns2:userEnteredRealPropertyInfo>
        <ns2:finalRealPropertyInfo>
          <ns1:ain>
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:ain"/>
          </ns1:ain>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:aoid">
            <ns1:aoid>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:aoid"/>
            </ns1:aoid>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:region">
            <ns1:region>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:region"/>
            </ns1:region>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:cluster">
            <ns1:cluster>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:cluster"/>
            </ns1:cluster>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:propertyAddress">
            <ns1:propertyAddress>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:propertyAddress"/>
            </ns1:propertyAddress>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:district">
            <ns1:district>
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:district"/>
            </ns1:district>
          </xsl:if>
          <ns1:subPartList>
            <xsl:for-each select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:subPartList/ns1:subPart">
              <ns1:subPart>
                <xsl:if test="ns1:dbUniqueId">
                  <ns1:dbUniqueId>
                    <xsl:value-of select="ns1:dbUniqueId"/>
                  </ns1:dbUniqueId>
                </xsl:if>
                <ns1:ain>
                  <xsl:value-of select="ns1:ain"/>
                </ns1:ain>
                <xsl:if test="ns1:aoid">
                  <ns1:aoid>
                    <xsl:value-of select="ns1:aoid"/>
                  </ns1:aoid>
                </xsl:if>
                <xsl:if test="ns1:transactionType">
                  <ns1:transactionType>
                    <xsl:value-of select="ns1:transactionType"/>
                  </ns1:transactionType>
                </xsl:if>
                <xsl:if test="ns1:improvementNumber">
                  <ns1:improvementNumber>
                    <xsl:value-of select="ns1:improvementNumber"/>
                  </ns1:improvementNumber>
                </xsl:if>
                <xsl:if test="ns1:subPartNumber">
                  <ns1:subPartNumber>
                    <xsl:value-of select="ns1:subPartNumber"/>
                  </ns1:subPartNumber>
                </xsl:if>
                <xsl:if test="ns1:rcnYearChange">
                  <ns1:rcnYearChange>
                    <xsl:value-of select="ns1:rcnYearChange"/>
                  </ns1:rcnYearChange>
                </xsl:if>
                <xsl:if test="ns1:designTypeRef">
                  <ns1:designTypeRef>
                    <xsl:value-of select="ns1:designTypeRef"/>
                  </ns1:designTypeRef>
                </xsl:if>
                <xsl:if test="ns1:designTypeKey">
                  <ns1:designTypeKey>
                    <xsl:value-of select="ns1:designTypeKey"/>
                  </ns1:designTypeKey>
                </xsl:if>
                <xsl:if test="ns1:designTypeLegend">
                  <ns1:designTypeLegend>
                    <xsl:value-of select="ns1:designTypeLegend"/>
                  </ns1:designTypeLegend>
                </xsl:if>
                <xsl:if test="ns1:qualityClass">
                  <ns1:qualityClass>
                    <xsl:value-of select="ns1:qualityClass"/>
                  </ns1:qualityClass>
                </xsl:if>
                <xsl:if test="ns1:yearBuilt">
                  <ns1:yearBuilt>
                    <xsl:value-of select="ns1:yearBuilt"/>
                  </ns1:yearBuilt>
                </xsl:if>
                <xsl:if test="ns1:effectiveYearBuilt">
                  <ns1:effectiveYearBuilt>
                    <xsl:value-of select="ns1:effectiveYearBuilt"/>
                  </ns1:effectiveYearBuilt>
                </xsl:if>
                <xsl:if test="ns1:depreciationTable">
                  <ns1:depreciationTable>
                    <xsl:value-of select="ns1:depreciationTable"/>
                  </ns1:depreciationTable>
                </xsl:if>
                <xsl:if test="ns1:numberOfUnits">
                  <ns1:numberOfUnits>
                    <xsl:value-of select="ns1:numberOfUnits"/>
                  </ns1:numberOfUnits>
                </xsl:if>
                <xsl:if test="ns1:bedroomCount">
                  <ns1:bedroomCount>
                    <xsl:value-of select="ns1:bedroomCount"/>
                  </ns1:bedroomCount>
                </xsl:if>
                <xsl:if test="ns1:bathroomCount">
                  <ns1:bathroomCount>
                    <xsl:value-of select="ns1:bathroomCount"/>
                  </ns1:bathroomCount>
                </xsl:if>
                <xsl:if test="ns1:improvementSizeSqft">
                  <ns1:improvementSizeSqft>
                    <xsl:value-of select="ns1:improvementSizeSqft"/>
                  </ns1:improvementSizeSqft>
                </xsl:if>
                <xsl:if test="ns1:rcnOtherTotal">
                  <ns1:rcnOtherTotal>
                    <xsl:value-of select="ns1:rcnOtherTotal"/>
                  </ns1:rcnOtherTotal>
                </xsl:if>
                <xsl:if test="ns1:costFactor">
                  <ns1:costFactor>
                    <xsl:value-of select="ns1:costFactor"/>
                  </ns1:costFactor>
                </xsl:if>
                <xsl:if test="ns1:rcnMain">
                  <ns1:rcnMain>
                    <xsl:value-of select="ns1:rcnMain"/>
                  </ns1:rcnMain>
                </xsl:if>
                <xsl:if test="ns1:percentGood">
                  <ns1:percentGood>
                    <xsl:value-of select="ns1:percentGood"/>
                  </ns1:percentGood>
                </xsl:if>
                <xsl:if test="ns1:addedDepreciationTypeRef">
                  <ns1:addedDepreciationTypeRef>
                    <xsl:value-of select="ns1:addedDepreciationTypeRef"/>
                  </ns1:addedDepreciationTypeRef>
                </xsl:if>
                <xsl:if test="ns1:addedDepreciationTypeKey">
                  <ns1:addedDepreciationTypeKey>
                    <xsl:value-of select="ns1:addedDepreciationTypeKey"/>
                  </ns1:addedDepreciationTypeKey>
                </xsl:if>
                <xsl:if test="ns1:addedDepreciationTypeLegend">
                  <ns1:addedDepreciationTypeLegend>
                    <xsl:value-of select="ns1:addedDepreciationTypeLegend"/>
                  </ns1:addedDepreciationTypeLegend>
                </xsl:if>
                <xsl:if test="ns1:addedDepreciationPercent">
                  <ns1:addedDepreciationPercent>
                    <xsl:value-of select="ns1:addedDepreciationPercent"/>
                  </ns1:addedDepreciationPercent>
                </xsl:if>
                <xsl:if test="ns1:rcnLessDepreciation">
                  <ns1:rcnLessDepreciation>
                    <xsl:value-of select="ns1:rcnLessDepreciation"/>
                  </ns1:rcnLessDepreciation>
                </xsl:if>
              </ns1:subPart>
            </xsl:for-each>
          </ns1:subPartList>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:composite">
            <ns1:composite>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:composite/ns1:dbUniqueId">
                <ns1:dbUniqueId>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:composite/ns1:dbUniqueId"/>
                </ns1:dbUniqueId>
              </xsl:if>
              <ns1:ain>
                <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:composite/ns1:ain"/>
              </ns1:ain>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:composite/ns1:aoid">
                <ns1:aoid>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:composite/ns1:aoid"/>
                </ns1:aoid>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:composite/ns1:transactionType">
                <ns1:transactionType>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:composite/ns1:transactionType"/>
                </ns1:transactionType>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:composite/ns1:sqft">
                <ns1:sqft>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:composite/ns1:sqft"/>
                </ns1:sqft>
              </xsl:if>
            </ns1:composite>
          </xsl:if>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land">
            <ns1:land>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:dbUniqueId">
                <ns1:dbUniqueId>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:dbUniqueId"/>
                </ns1:dbUniqueId>
              </xsl:if>
              <ns1:ain>
                <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:ain"/>
              </ns1:ain>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:aoid">
                <ns1:aoid>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:aoid"/>
                </ns1:aoid>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:transactionType">
                <ns1:transactionType>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:transactionType"/>
                </ns1:transactionType>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:width">
                <ns1:width>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:width"/>
                </ns1:width>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:depth">
                <ns1:depth>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:depth"/>
                </ns1:depth>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:sizeSqft">
                <ns1:sizeSqft>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:sizeSqft"/>
                </ns1:sizeSqft>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:sizeUsableSqft">
                <ns1:sizeUsableSqft>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:sizeUsableSqft"/>
                </ns1:sizeUsableSqft>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:sizeAcreAge">
                <ns1:sizeAcreAge>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:sizeAcreAge"/>
                </ns1:sizeAcreAge>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:corner">
                <ns1:corner>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:corner"/>
                </ns1:corner>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:sewer">
                <ns1:sewer>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:sewer"/>
                </ns1:sewer>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:traffic">
                <ns1:traffic>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:traffic"/>
                </ns1:traffic>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:freewayProximity">
                <ns1:freewayProximity>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:freewayProximity"/>
                </ns1:freewayProximity>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:flightPath">
                <ns1:flightPath>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:flightPath"/>
                </ns1:flightPath>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:golfFront">
                <ns1:golfFront>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:golfFront"/>
                </ns1:golfFront>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:horses">
                <ns1:horses>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:horses"/>
                </ns1:horses>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:viewCodeKey">
                <ns1:viewCodeKey>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:viewCodeKey"/>
                </ns1:viewCodeKey>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:viewCodeRef">
                <ns1:viewCodeRef>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:viewCodeRef"/>
                </ns1:viewCodeRef>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:viewCodeLegend">
                <ns1:viewCodeLegend>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:viewCodeLegend"/>
                </ns1:viewCodeLegend>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:useCode">
                <ns1:useCode>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:useCode"/>
                </ns1:useCode>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:useType">
                <ns1:useType>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:useType"/>
                </ns1:useType>
              </xsl:if>
              <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:codeSplit">
                <ns1:codeSplit>
                  <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns2:managePDCRRequest/ns2:finalRealPropertyInfo/ns1:land/ns1:codeSplit"/>
                </ns1:codeSplit>
              </xsl:if>
            </ns1:land>
          </xsl:if>
        </ns2:finalRealPropertyInfo>
      </ns2:managePDCRRequest>
      <ns4:assignTo_UserID>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignTo_UserID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignTo_UserID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignTo_UserID"/>
      </ns4:assignTo_UserID>
      <ns4:assignTo_GroupID>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignTo_GroupID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignTo_GroupID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignTo_GroupID"/>
      </ns4:assignTo_GroupID>
      <ns4:assignTo_ManagerID>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignTo_ManagerID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignTo_ManagerID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignTo_ManagerID"/>
      </ns4:assignTo_ManagerID>
      <ns4:role>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:role/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:role/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:role"/>
      </ns4:role>
      <ns4:ownerID>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:ownerID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:ownerID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:ownerID"/>
      </ns4:ownerID>
      <ns4:clientID>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:clientID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:clientID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:clientID"/>
      </ns4:clientID>
      <ns4:checkPDCR>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:checkPDCR/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:checkPDCR/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:checkPDCR"/>
      </ns4:checkPDCR>
      <ns4:userType>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:userType/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:userType/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:userType"/>
      </ns4:userType>
      <ns4:accquiredBy>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:accquiredBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:accquiredBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:accquiredBy"/>
      </ns4:accquiredBy>
      <xsl:choose>
        <xsl:when test="contains(/tns:task/tns:systemAttributes/tns:outcome,&quot;SUBMIT&quot;)">
          <ns4:returnTo>
            <xsl:value-of select="concat(concat(/tns:task/tns:systemAttributes/tns:updatedBy/tns:displayName,&quot; - &quot;),/tns:task/tns:systemAttributes/tns:updatedDate)"/>
          </ns4:returnTo>
        </xsl:when>
      </xsl:choose>
      <ns4:sortPDCR>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:sortPDCR/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:sortPDCR/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <ns6:ain>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:sortPDCR/ns6:ain/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:sortPDCR/ns6:ain/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:sortPDCR/ns6:ain"/>
        </ns6:ain>
        <ns6:district>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:sortPDCR/ns6:district/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:sortPDCR/ns6:district/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:sortPDCR/ns6:district"/>
        </ns6:district>
        <ns6:region>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:sortPDCR/ns6:region/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:sortPDCR/ns6:region/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:sortPDCR/ns6:region"/>
        </ns6:region>
        <ns6:cluster>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:sortPDCR/ns6:cluster/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:sortPDCR/ns6:cluster/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:sortPDCR/ns6:cluster"/>
        </ns6:cluster>
      </ns4:sortPDCR>
      <ns4:assignmentBox>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignmentBox/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignmentBox/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <ns0:assignmentBox_UserId>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignmentBox/ns0:assignmentBox_UserId/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignmentBox/ns0:assignmentBox_UserId/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignmentBox/ns0:assignmentBox_UserId"/>
        </ns0:assignmentBox_UserId>
        <ns0:assignmentBox_GroupId>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignmentBox/ns0:assignmentBox_GroupId/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignmentBox/ns0:assignmentBox_GroupId/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignmentBox/ns0:assignmentBox_GroupId"/>
        </ns0:assignmentBox_GroupId>
        <ns0:userType>
          <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignmentBox/ns0:userType/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignmentBox/ns0:userType/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignmentBox/ns0:userType"/>
        </ns0:userType>
      </ns4:assignmentBox>
      <ns4:assignedBy>
        <xsl:if test="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignedBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignedBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="$HumanTaskPDO/ns4:PDCRHumanTaskBO/ns4:assignedBy"/>
      </ns4:assignedBy>
    </ns4:PDCRHumanTaskBO>
  </xsl:template>
</xsl:stylesheet>