<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://xmlns.oracle.com/bpm/bpmobject/Data/PDCRHumanTaskBO" xmlns:ns6="http://assessor.lacounty.gov/amp/type/common/ResponseHeader/v1.0" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:bpmo="http://xmlns.oracle.com/bpm/bpmobject/" xmlns:ns4="http://assessor.lacounty.gov/amp/type/common/RealPropertyInfo/v1.0" xmlns:ns5="http://assessor.lacounty.gov/amp/type/common/RequestHeader/v1.0" xmlns:ns2="http://xmlns.oracle.com/bpm/bpmobject/Data/SortPDCRBO" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns3="http://xmlns.oracle.com/bpm/bpmobject/Data/AssignToUserOrGroupBO" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns1="http://assessor.lacounty.gov/amp/data/ao/ManagePDCR/v1.0" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns0 ns6 bpmo ns4 ns5 ns2 ns3 ns1 xsd xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/PDCRHumanTaskBO.xsd"/>
            <oracle-xsl-mapper:rootElement name="PDCRHumanTaskBO" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/PDCRHumanTaskBO"/>
            <oracle-xsl-mapper:param name="HumanTaskPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/PDCRHumanTaskBO.xsd"/>
            <oracle-xsl-mapper:rootElement name="PDCRHumanTaskBO" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/PDCRHumanTaskBO"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 15:05:03 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns0:PDCRHumanTaskBO>
      <ns1:managePDCRRequest>
        <ns1:header>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:header/ns5:applicationId">
            <ns5:applicationId>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:header/ns5:applicationId"/>
            </ns5:applicationId>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:header/ns5:requestId">
            <ns5:requestId>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:header/ns5:requestId"/>
            </ns5:requestId>
          </xsl:if>
        </ns1:header>
        <ns1:ain>
          <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:ain"/>
        </ns1:ain>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:aoid">
          <ns1:aoid>
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:aoid"/>
          </ns1:aoid>
        </xsl:if>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userId">
          <ns1:userId>
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userId"/>
          </ns1:userId>
        </xsl:if>
        <ns1:processType>
          <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:processType"/>
        </ns1:processType>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:actionType">
          <ns1:actionType>
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:actionType"/>
          </ns1:actionType>
        </xsl:if>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userType">
          <ns1:userType>
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userType"/>
          </ns1:userType>
        </xsl:if>
        <ns1:requestorInfo>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:requestorName">
            <ns1:requestorName>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:requestorName"/>
            </ns1:requestorName>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:requestorType">
            <ns1:requestorType>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:requestorType"/>
            </ns1:requestorType>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:Phone">
            <ns1:Phone>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:Phone"/>
            </ns1:Phone>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:email">
            <ns1:email>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:email"/>
            </ns1:email>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:reasonForRequest">
            <ns1:reasonForRequest>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:reasonForRequest"/>
            </ns1:reasonForRequest>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:comments">
            <ns1:comments>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:comments"/>
            </ns1:comments>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:dataChangeSource">
            <ns1:dataChangeSource>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:dataChangeSource"/>
            </ns1:dataChangeSource>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:preferredContact">
            <ns1:preferredContact>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:requestorInfo/ns1:preferredContact"/>
            </ns1:preferredContact>
          </xsl:if>
        </ns1:requestorInfo>
        <ns1:source>
          <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:source"/>
        </ns1:source>
        <ns1:originalRealPropertyInfo>
          <ns4:ain>
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:ain"/>
          </ns4:ain>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:aoid">
            <ns4:aoid>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:aoid"/>
            </ns4:aoid>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:region">
            <ns4:region>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:region"/>
            </ns4:region>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:cluster">
            <ns4:cluster>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:cluster"/>
            </ns4:cluster>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:propertyAddress">
            <ns4:propertyAddress>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:propertyAddress"/>
            </ns4:propertyAddress>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:district">
            <ns4:district>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:district"/>
            </ns4:district>
          </xsl:if>
          <ns4:subPartList>
            <xsl:for-each select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:subPartList/ns4:subPart">
              <ns4:subPart>
                <xsl:if test="ns4:dbUniqueId">
                  <ns4:dbUniqueId>
                    <xsl:value-of select="ns4:dbUniqueId"/>
                  </ns4:dbUniqueId>
                </xsl:if>
                <ns4:ain>
                  <xsl:value-of select="ns4:ain"/>
                </ns4:ain>
                <xsl:if test="ns4:aoid">
                  <ns4:aoid>
                    <xsl:value-of select="ns4:aoid"/>
                  </ns4:aoid>
                </xsl:if>
                <xsl:if test="ns4:transactionType">
                  <ns4:transactionType>
                    <xsl:value-of select="ns4:transactionType"/>
                  </ns4:transactionType>
                </xsl:if>
                <xsl:if test="ns4:improvementNumber">
                  <ns4:improvementNumber>
                    <xsl:value-of select="ns4:improvementNumber"/>
                  </ns4:improvementNumber>
                </xsl:if>
                <xsl:if test="ns4:subPartNumber">
                  <ns4:subPartNumber>
                    <xsl:value-of select="ns4:subPartNumber"/>
                  </ns4:subPartNumber>
                </xsl:if>
                <xsl:if test="ns4:rcnYearChange">
                  <ns4:rcnYearChange>
                    <xsl:value-of select="ns4:rcnYearChange"/>
                  </ns4:rcnYearChange>
                </xsl:if>
                <xsl:if test="ns4:designTypeRef">
                  <ns4:designTypeRef>
                    <xsl:value-of select="ns4:designTypeRef"/>
                  </ns4:designTypeRef>
                </xsl:if>
                <xsl:if test="ns4:designTypeKey">
                  <ns4:designTypeKey>
                    <xsl:value-of select="ns4:designTypeKey"/>
                  </ns4:designTypeKey>
                </xsl:if>
                <xsl:if test="ns4:designTypeLegend">
                  <ns4:designTypeLegend>
                    <xsl:value-of select="ns4:designTypeLegend"/>
                  </ns4:designTypeLegend>
                </xsl:if>
                <xsl:if test="ns4:qualityClass">
                  <ns4:qualityClass>
                    <xsl:value-of select="ns4:qualityClass"/>
                  </ns4:qualityClass>
                </xsl:if>
                <xsl:if test="ns4:yearBuilt">
                  <ns4:yearBuilt>
                    <xsl:value-of select="ns4:yearBuilt"/>
                  </ns4:yearBuilt>
                </xsl:if>
                <xsl:if test="ns4:effectiveYearBuilt">
                  <ns4:effectiveYearBuilt>
                    <xsl:value-of select="ns4:effectiveYearBuilt"/>
                  </ns4:effectiveYearBuilt>
                </xsl:if>
                <xsl:if test="ns4:depreciationTable">
                  <ns4:depreciationTable>
                    <xsl:value-of select="ns4:depreciationTable"/>
                  </ns4:depreciationTable>
                </xsl:if>
                <xsl:if test="ns4:numberOfUnits">
                  <ns4:numberOfUnits>
                    <xsl:value-of select="ns4:numberOfUnits"/>
                  </ns4:numberOfUnits>
                </xsl:if>
                <xsl:if test="ns4:bedroomCount">
                  <ns4:bedroomCount>
                    <xsl:value-of select="ns4:bedroomCount"/>
                  </ns4:bedroomCount>
                </xsl:if>
                <xsl:if test="ns4:bathroomCount">
                  <ns4:bathroomCount>
                    <xsl:value-of select="ns4:bathroomCount"/>
                  </ns4:bathroomCount>
                </xsl:if>
                <xsl:if test="ns4:improvementSizeSqft">
                  <ns4:improvementSizeSqft>
                    <xsl:value-of select="ns4:improvementSizeSqft"/>
                  </ns4:improvementSizeSqft>
                </xsl:if>
                <xsl:if test="ns4:rcnOtherTotal">
                  <ns4:rcnOtherTotal>
                    <xsl:value-of select="ns4:rcnOtherTotal"/>
                  </ns4:rcnOtherTotal>
                </xsl:if>
                <xsl:if test="ns4:costFactor">
                  <ns4:costFactor>
                    <xsl:value-of select="ns4:costFactor"/>
                  </ns4:costFactor>
                </xsl:if>
                <xsl:if test="ns4:rcnMain">
                  <ns4:rcnMain>
                    <xsl:value-of select="ns4:rcnMain"/>
                  </ns4:rcnMain>
                </xsl:if>
                <xsl:if test="ns4:percentGood">
                  <ns4:percentGood>
                    <xsl:value-of select="ns4:percentGood"/>
                  </ns4:percentGood>
                </xsl:if>
                <xsl:if test="ns4:addedDepreciationTypeRef">
                  <ns4:addedDepreciationTypeRef>
                    <xsl:value-of select="ns4:addedDepreciationTypeRef"/>
                  </ns4:addedDepreciationTypeRef>
                </xsl:if>
                <xsl:if test="ns4:addedDepreciationTypeKey">
                  <ns4:addedDepreciationTypeKey>
                    <xsl:value-of select="ns4:addedDepreciationTypeKey"/>
                  </ns4:addedDepreciationTypeKey>
                </xsl:if>
                <xsl:if test="ns4:addedDepreciationTypeLegend">
                  <ns4:addedDepreciationTypeLegend>
                    <xsl:value-of select="ns4:addedDepreciationTypeLegend"/>
                  </ns4:addedDepreciationTypeLegend>
                </xsl:if>
                <xsl:if test="ns4:addedDepreciationPercent">
                  <ns4:addedDepreciationPercent>
                    <xsl:value-of select="ns4:addedDepreciationPercent"/>
                  </ns4:addedDepreciationPercent>
                </xsl:if>
                <xsl:if test="ns4:rcnLessDepreciation">
                  <ns4:rcnLessDepreciation>
                    <xsl:value-of select="ns4:rcnLessDepreciation"/>
                  </ns4:rcnLessDepreciation>
                </xsl:if>
              </ns4:subPart>
            </xsl:for-each>
          </ns4:subPartList>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:composite">
            <ns4:composite>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:composite/ns4:dbUniqueId">
                <ns4:dbUniqueId>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:composite/ns4:dbUniqueId"/>
                </ns4:dbUniqueId>
              </xsl:if>
              <ns4:ain>
                <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:composite/ns4:ain"/>
              </ns4:ain>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:composite/ns4:aoid">
                <ns4:aoid>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:composite/ns4:aoid"/>
                </ns4:aoid>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:composite/ns4:transactionType">
                <ns4:transactionType>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:composite/ns4:transactionType"/>
                </ns4:transactionType>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:composite/ns4:sqft">
                <ns4:sqft>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:composite/ns4:sqft"/>
                </ns4:sqft>
              </xsl:if>
            </ns4:composite>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land">
            <ns4:land>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:dbUniqueId">
                <ns4:dbUniqueId>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:dbUniqueId"/>
                </ns4:dbUniqueId>
              </xsl:if>
              <ns4:ain>
                <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:ain"/>
              </ns4:ain>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:aoid">
                <ns4:aoid>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:aoid"/>
                </ns4:aoid>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:transactionType">
                <ns4:transactionType>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:transactionType"/>
                </ns4:transactionType>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:width">
                <ns4:width>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:width"/>
                </ns4:width>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:depth">
                <ns4:depth>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:depth"/>
                </ns4:depth>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:sizeSqft">
                <ns4:sizeSqft>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:sizeSqft"/>
                </ns4:sizeSqft>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:sizeUsableSqft">
                <ns4:sizeUsableSqft>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:sizeUsableSqft"/>
                </ns4:sizeUsableSqft>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:sizeAcreAge">
                <ns4:sizeAcreAge>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:sizeAcreAge"/>
                </ns4:sizeAcreAge>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:corner">
                <ns4:corner>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:corner"/>
                </ns4:corner>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:sewer">
                <ns4:sewer>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:sewer"/>
                </ns4:sewer>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:traffic">
                <ns4:traffic>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:traffic"/>
                </ns4:traffic>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:freewayProximity">
                <ns4:freewayProximity>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:freewayProximity"/>
                </ns4:freewayProximity>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:flightPath">
                <ns4:flightPath>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:flightPath"/>
                </ns4:flightPath>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:golfFront">
                <ns4:golfFront>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:golfFront"/>
                </ns4:golfFront>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:horses">
                <ns4:horses>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:horses"/>
                </ns4:horses>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:viewCodeKey">
                <ns4:viewCodeKey>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:viewCodeKey"/>
                </ns4:viewCodeKey>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:viewCodeRef">
                <ns4:viewCodeRef>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:viewCodeRef"/>
                </ns4:viewCodeRef>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:viewCodeLegend">
                <ns4:viewCodeLegend>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:viewCodeLegend"/>
                </ns4:viewCodeLegend>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:useCode">
                <ns4:useCode>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:useCode"/>
                </ns4:useCode>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:useType">
                <ns4:useType>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:useType"/>
                </ns4:useType>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:codeSplit">
                <ns4:codeSplit>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:originalRealPropertyInfo/ns4:land/ns4:codeSplit"/>
                </ns4:codeSplit>
              </xsl:if>
            </ns4:land>
          </xsl:if>
        </ns1:originalRealPropertyInfo>
        <ns1:userEnteredRealPropertyInfo>
          <ns4:ain>
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:ain"/>
          </ns4:ain>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:aoid">
            <ns4:aoid>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:aoid"/>
            </ns4:aoid>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:region">
            <ns4:region>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:region"/>
            </ns4:region>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:cluster">
            <ns4:cluster>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:cluster"/>
            </ns4:cluster>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:propertyAddress">
            <ns4:propertyAddress>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:propertyAddress"/>
            </ns4:propertyAddress>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:district">
            <ns4:district>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:district"/>
            </ns4:district>
          </xsl:if>
          <ns4:subPartList>
            <xsl:for-each select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:subPartList/ns4:subPart">
              <ns4:subPart>
                <xsl:if test="ns4:dbUniqueId">
                  <ns4:dbUniqueId>
                    <xsl:value-of select="ns4:dbUniqueId"/>
                  </ns4:dbUniqueId>
                </xsl:if>
                <ns4:ain>
                  <xsl:value-of select="ns4:ain"/>
                </ns4:ain>
                <xsl:if test="ns4:aoid">
                  <ns4:aoid>
                    <xsl:value-of select="ns4:aoid"/>
                  </ns4:aoid>
                </xsl:if>
                <xsl:if test="ns4:transactionType">
                  <ns4:transactionType>
                    <xsl:value-of select="ns4:transactionType"/>
                  </ns4:transactionType>
                </xsl:if>
                <xsl:if test="ns4:improvementNumber">
                  <ns4:improvementNumber>
                    <xsl:value-of select="ns4:improvementNumber"/>
                  </ns4:improvementNumber>
                </xsl:if>
                <xsl:if test="ns4:subPartNumber">
                  <ns4:subPartNumber>
                    <xsl:value-of select="ns4:subPartNumber"/>
                  </ns4:subPartNumber>
                </xsl:if>
                <xsl:if test="ns4:rcnYearChange">
                  <ns4:rcnYearChange>
                    <xsl:value-of select="ns4:rcnYearChange"/>
                  </ns4:rcnYearChange>
                </xsl:if>
                <xsl:if test="ns4:designTypeRef">
                  <ns4:designTypeRef>
                    <xsl:value-of select="ns4:designTypeRef"/>
                  </ns4:designTypeRef>
                </xsl:if>
                <xsl:if test="ns4:designTypeKey">
                  <ns4:designTypeKey>
                    <xsl:value-of select="ns4:designTypeKey"/>
                  </ns4:designTypeKey>
                </xsl:if>
                <xsl:if test="ns4:designTypeLegend">
                  <ns4:designTypeLegend>
                    <xsl:value-of select="ns4:designTypeLegend"/>
                  </ns4:designTypeLegend>
                </xsl:if>
                <xsl:if test="ns4:qualityClass">
                  <ns4:qualityClass>
                    <xsl:value-of select="ns4:qualityClass"/>
                  </ns4:qualityClass>
                </xsl:if>
                <xsl:if test="ns4:yearBuilt">
                  <ns4:yearBuilt>
                    <xsl:value-of select="ns4:yearBuilt"/>
                  </ns4:yearBuilt>
                </xsl:if>
                <xsl:if test="ns4:effectiveYearBuilt">
                  <ns4:effectiveYearBuilt>
                    <xsl:value-of select="ns4:effectiveYearBuilt"/>
                  </ns4:effectiveYearBuilt>
                </xsl:if>
                <xsl:if test="ns4:depreciationTable">
                  <ns4:depreciationTable>
                    <xsl:value-of select="ns4:depreciationTable"/>
                  </ns4:depreciationTable>
                </xsl:if>
                <xsl:if test="ns4:numberOfUnits">
                  <ns4:numberOfUnits>
                    <xsl:value-of select="ns4:numberOfUnits"/>
                  </ns4:numberOfUnits>
                </xsl:if>
                <xsl:if test="ns4:bedroomCount">
                  <ns4:bedroomCount>
                    <xsl:value-of select="ns4:bedroomCount"/>
                  </ns4:bedroomCount>
                </xsl:if>
                <xsl:if test="ns4:bathroomCount">
                  <ns4:bathroomCount>
                    <xsl:value-of select="ns4:bathroomCount"/>
                  </ns4:bathroomCount>
                </xsl:if>
                <xsl:if test="ns4:improvementSizeSqft">
                  <ns4:improvementSizeSqft>
                    <xsl:value-of select="ns4:improvementSizeSqft"/>
                  </ns4:improvementSizeSqft>
                </xsl:if>
                <xsl:if test="ns4:rcnOtherTotal">
                  <ns4:rcnOtherTotal>
                    <xsl:value-of select="ns4:rcnOtherTotal"/>
                  </ns4:rcnOtherTotal>
                </xsl:if>
                <xsl:if test="ns4:costFactor">
                  <ns4:costFactor>
                    <xsl:value-of select="ns4:costFactor"/>
                  </ns4:costFactor>
                </xsl:if>
                <xsl:if test="ns4:rcnMain">
                  <ns4:rcnMain>
                    <xsl:value-of select="ns4:rcnMain"/>
                  </ns4:rcnMain>
                </xsl:if>
                <xsl:if test="ns4:percentGood">
                  <ns4:percentGood>
                    <xsl:value-of select="ns4:percentGood"/>
                  </ns4:percentGood>
                </xsl:if>
                <xsl:if test="ns4:addedDepreciationTypeRef">
                  <ns4:addedDepreciationTypeRef>
                    <xsl:value-of select="ns4:addedDepreciationTypeRef"/>
                  </ns4:addedDepreciationTypeRef>
                </xsl:if>
                <xsl:if test="ns4:addedDepreciationTypeKey">
                  <ns4:addedDepreciationTypeKey>
                    <xsl:value-of select="ns4:addedDepreciationTypeKey"/>
                  </ns4:addedDepreciationTypeKey>
                </xsl:if>
                <xsl:if test="ns4:addedDepreciationTypeLegend">
                  <ns4:addedDepreciationTypeLegend>
                    <xsl:value-of select="ns4:addedDepreciationTypeLegend"/>
                  </ns4:addedDepreciationTypeLegend>
                </xsl:if>
                <xsl:if test="ns4:addedDepreciationPercent">
                  <ns4:addedDepreciationPercent>
                    <xsl:value-of select="ns4:addedDepreciationPercent"/>
                  </ns4:addedDepreciationPercent>
                </xsl:if>
                <xsl:if test="ns4:rcnLessDepreciation">
                  <ns4:rcnLessDepreciation>
                    <xsl:value-of select="ns4:rcnLessDepreciation"/>
                  </ns4:rcnLessDepreciation>
                </xsl:if>
              </ns4:subPart>
            </xsl:for-each>
          </ns4:subPartList>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:composite">
            <ns4:composite>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:composite/ns4:dbUniqueId">
                <ns4:dbUniqueId>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:composite/ns4:dbUniqueId"/>
                </ns4:dbUniqueId>
              </xsl:if>
              <ns4:ain>
                <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:composite/ns4:ain"/>
              </ns4:ain>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:composite/ns4:aoid">
                <ns4:aoid>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:composite/ns4:aoid"/>
                </ns4:aoid>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:composite/ns4:transactionType">
                <ns4:transactionType>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:composite/ns4:transactionType"/>
                </ns4:transactionType>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:composite/ns4:sqft">
                <ns4:sqft>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:composite/ns4:sqft"/>
                </ns4:sqft>
              </xsl:if>
            </ns4:composite>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land">
            <ns4:land>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:dbUniqueId">
                <ns4:dbUniqueId>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:dbUniqueId"/>
                </ns4:dbUniqueId>
              </xsl:if>
              <ns4:ain>
                <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:ain"/>
              </ns4:ain>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:aoid">
                <ns4:aoid>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:aoid"/>
                </ns4:aoid>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:transactionType">
                <ns4:transactionType>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:transactionType"/>
                </ns4:transactionType>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:width">
                <ns4:width>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:width"/>
                </ns4:width>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:depth">
                <ns4:depth>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:depth"/>
                </ns4:depth>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:sizeSqft">
                <ns4:sizeSqft>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:sizeSqft"/>
                </ns4:sizeSqft>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:sizeUsableSqft">
                <ns4:sizeUsableSqft>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:sizeUsableSqft"/>
                </ns4:sizeUsableSqft>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:sizeAcreAge">
                <ns4:sizeAcreAge>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:sizeAcreAge"/>
                </ns4:sizeAcreAge>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:corner">
                <ns4:corner>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:corner"/>
                </ns4:corner>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:sewer">
                <ns4:sewer>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:sewer"/>
                </ns4:sewer>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:traffic">
                <ns4:traffic>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:traffic"/>
                </ns4:traffic>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:freewayProximity">
                <ns4:freewayProximity>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:freewayProximity"/>
                </ns4:freewayProximity>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:flightPath">
                <ns4:flightPath>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:flightPath"/>
                </ns4:flightPath>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:golfFront">
                <ns4:golfFront>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:golfFront"/>
                </ns4:golfFront>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:horses">
                <ns4:horses>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:horses"/>
                </ns4:horses>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:viewCodeKey">
                <ns4:viewCodeKey>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:viewCodeKey"/>
                </ns4:viewCodeKey>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:viewCodeRef">
                <ns4:viewCodeRef>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:viewCodeRef"/>
                </ns4:viewCodeRef>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:viewCodeLegend">
                <ns4:viewCodeLegend>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:viewCodeLegend"/>
                </ns4:viewCodeLegend>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:useCode">
                <ns4:useCode>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:useCode"/>
                </ns4:useCode>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:useType">
                <ns4:useType>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:useType"/>
                </ns4:useType>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:codeSplit">
                <ns4:codeSplit>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:userEnteredRealPropertyInfo/ns4:land/ns4:codeSplit"/>
                </ns4:codeSplit>
              </xsl:if>
            </ns4:land>
          </xsl:if>
        </ns1:userEnteredRealPropertyInfo>
        <ns1:finalRealPropertyInfo>
          <ns4:ain>
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:ain"/>
          </ns4:ain>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:aoid">
            <ns4:aoid>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:aoid"/>
            </ns4:aoid>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:region">
            <ns4:region>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:region"/>
            </ns4:region>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:cluster">
            <ns4:cluster>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:cluster"/>
            </ns4:cluster>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:propertyAddress">
            <ns4:propertyAddress>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:propertyAddress"/>
            </ns4:propertyAddress>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:district">
            <ns4:district>
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:district"/>
            </ns4:district>
          </xsl:if>
          <ns4:subPartList>
            <xsl:for-each select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:subPartList/ns4:subPart">
              <ns4:subPart>
                <xsl:if test="ns4:dbUniqueId">
                  <ns4:dbUniqueId>
                    <xsl:value-of select="ns4:dbUniqueId"/>
                  </ns4:dbUniqueId>
                </xsl:if>
                <ns4:ain>
                  <xsl:value-of select="ns4:ain"/>
                </ns4:ain>
                <xsl:if test="ns4:aoid">
                  <ns4:aoid>
                    <xsl:value-of select="ns4:aoid"/>
                  </ns4:aoid>
                </xsl:if>
                <xsl:if test="ns4:transactionType">
                  <ns4:transactionType>
                    <xsl:value-of select="ns4:transactionType"/>
                  </ns4:transactionType>
                </xsl:if>
                <xsl:if test="ns4:improvementNumber">
                  <ns4:improvementNumber>
                    <xsl:value-of select="ns4:improvementNumber"/>
                  </ns4:improvementNumber>
                </xsl:if>
                <xsl:if test="ns4:subPartNumber">
                  <ns4:subPartNumber>
                    <xsl:value-of select="ns4:subPartNumber"/>
                  </ns4:subPartNumber>
                </xsl:if>
                <xsl:if test="ns4:rcnYearChange">
                  <ns4:rcnYearChange>
                    <xsl:value-of select="ns4:rcnYearChange"/>
                  </ns4:rcnYearChange>
                </xsl:if>
                <xsl:if test="ns4:designTypeRef">
                  <ns4:designTypeRef>
                    <xsl:value-of select="ns4:designTypeRef"/>
                  </ns4:designTypeRef>
                </xsl:if>
                <xsl:if test="ns4:designTypeKey">
                  <ns4:designTypeKey>
                    <xsl:value-of select="ns4:designTypeKey"/>
                  </ns4:designTypeKey>
                </xsl:if>
                <xsl:if test="ns4:designTypeLegend">
                  <ns4:designTypeLegend>
                    <xsl:value-of select="ns4:designTypeLegend"/>
                  </ns4:designTypeLegend>
                </xsl:if>
                <xsl:if test="ns4:qualityClass">
                  <ns4:qualityClass>
                    <xsl:value-of select="ns4:qualityClass"/>
                  </ns4:qualityClass>
                </xsl:if>
                <xsl:if test="ns4:yearBuilt">
                  <ns4:yearBuilt>
                    <xsl:value-of select="ns4:yearBuilt"/>
                  </ns4:yearBuilt>
                </xsl:if>
                <xsl:if test="ns4:effectiveYearBuilt">
                  <ns4:effectiveYearBuilt>
                    <xsl:value-of select="ns4:effectiveYearBuilt"/>
                  </ns4:effectiveYearBuilt>
                </xsl:if>
                <xsl:if test="ns4:depreciationTable">
                  <ns4:depreciationTable>
                    <xsl:value-of select="ns4:depreciationTable"/>
                  </ns4:depreciationTable>
                </xsl:if>
                <xsl:if test="ns4:numberOfUnits">
                  <ns4:numberOfUnits>
                    <xsl:value-of select="ns4:numberOfUnits"/>
                  </ns4:numberOfUnits>
                </xsl:if>
                <xsl:if test="ns4:bedroomCount">
                  <ns4:bedroomCount>
                    <xsl:value-of select="ns4:bedroomCount"/>
                  </ns4:bedroomCount>
                </xsl:if>
                <xsl:if test="ns4:bathroomCount">
                  <ns4:bathroomCount>
                    <xsl:value-of select="ns4:bathroomCount"/>
                  </ns4:bathroomCount>
                </xsl:if>
                <xsl:if test="ns4:improvementSizeSqft">
                  <ns4:improvementSizeSqft>
                    <xsl:value-of select="ns4:improvementSizeSqft"/>
                  </ns4:improvementSizeSqft>
                </xsl:if>
                <xsl:if test="ns4:rcnOtherTotal">
                  <ns4:rcnOtherTotal>
                    <xsl:value-of select="ns4:rcnOtherTotal"/>
                  </ns4:rcnOtherTotal>
                </xsl:if>
                <xsl:if test="ns4:costFactor">
                  <ns4:costFactor>
                    <xsl:value-of select="ns4:costFactor"/>
                  </ns4:costFactor>
                </xsl:if>
                <xsl:if test="ns4:rcnMain">
                  <ns4:rcnMain>
                    <xsl:value-of select="ns4:rcnMain"/>
                  </ns4:rcnMain>
                </xsl:if>
                <xsl:if test="ns4:percentGood">
                  <ns4:percentGood>
                    <xsl:value-of select="ns4:percentGood"/>
                  </ns4:percentGood>
                </xsl:if>
                <xsl:if test="ns4:addedDepreciationTypeRef">
                  <ns4:addedDepreciationTypeRef>
                    <xsl:value-of select="ns4:addedDepreciationTypeRef"/>
                  </ns4:addedDepreciationTypeRef>
                </xsl:if>
                <xsl:if test="ns4:addedDepreciationTypeKey">
                  <ns4:addedDepreciationTypeKey>
                    <xsl:value-of select="ns4:addedDepreciationTypeKey"/>
                  </ns4:addedDepreciationTypeKey>
                </xsl:if>
                <xsl:if test="ns4:addedDepreciationTypeLegend">
                  <ns4:addedDepreciationTypeLegend>
                    <xsl:value-of select="ns4:addedDepreciationTypeLegend"/>
                  </ns4:addedDepreciationTypeLegend>
                </xsl:if>
                <xsl:if test="ns4:addedDepreciationPercent">
                  <ns4:addedDepreciationPercent>
                    <xsl:value-of select="ns4:addedDepreciationPercent"/>
                  </ns4:addedDepreciationPercent>
                </xsl:if>
                <xsl:if test="ns4:rcnLessDepreciation">
                  <ns4:rcnLessDepreciation>
                    <xsl:value-of select="ns4:rcnLessDepreciation"/>
                  </ns4:rcnLessDepreciation>
                </xsl:if>
              </ns4:subPart>
            </xsl:for-each>
          </ns4:subPartList>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:composite">
            <ns4:composite>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:composite/ns4:dbUniqueId">
                <ns4:dbUniqueId>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:composite/ns4:dbUniqueId"/>
                </ns4:dbUniqueId>
              </xsl:if>
              <ns4:ain>
                <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:composite/ns4:ain"/>
              </ns4:ain>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:composite/ns4:aoid">
                <ns4:aoid>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:composite/ns4:aoid"/>
                </ns4:aoid>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:composite/ns4:transactionType">
                <ns4:transactionType>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:composite/ns4:transactionType"/>
                </ns4:transactionType>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:composite/ns4:sqft">
                <ns4:sqft>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:composite/ns4:sqft"/>
                </ns4:sqft>
              </xsl:if>
            </ns4:composite>
          </xsl:if>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land">
            <ns4:land>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:dbUniqueId">
                <ns4:dbUniqueId>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:dbUniqueId"/>
                </ns4:dbUniqueId>
              </xsl:if>
              <ns4:ain>
                <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:ain"/>
              </ns4:ain>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:aoid">
                <ns4:aoid>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:aoid"/>
                </ns4:aoid>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:transactionType">
                <ns4:transactionType>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:transactionType"/>
                </ns4:transactionType>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:width">
                <ns4:width>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:width"/>
                </ns4:width>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:depth">
                <ns4:depth>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:depth"/>
                </ns4:depth>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:sizeSqft">
                <ns4:sizeSqft>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:sizeSqft"/>
                </ns4:sizeSqft>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:sizeUsableSqft">
                <ns4:sizeUsableSqft>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:sizeUsableSqft"/>
                </ns4:sizeUsableSqft>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:sizeAcreAge">
                <ns4:sizeAcreAge>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:sizeAcreAge"/>
                </ns4:sizeAcreAge>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:corner">
                <ns4:corner>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:corner"/>
                </ns4:corner>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:sewer">
                <ns4:sewer>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:sewer"/>
                </ns4:sewer>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:traffic">
                <ns4:traffic>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:traffic"/>
                </ns4:traffic>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:freewayProximity">
                <ns4:freewayProximity>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:freewayProximity"/>
                </ns4:freewayProximity>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:flightPath">
                <ns4:flightPath>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:flightPath"/>
                </ns4:flightPath>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:golfFront">
                <ns4:golfFront>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:golfFront"/>
                </ns4:golfFront>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:horses">
                <ns4:horses>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:horses"/>
                </ns4:horses>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:viewCodeKey">
                <ns4:viewCodeKey>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:viewCodeKey"/>
                </ns4:viewCodeKey>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:viewCodeRef">
                <ns4:viewCodeRef>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:viewCodeRef"/>
                </ns4:viewCodeRef>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:viewCodeLegend">
                <ns4:viewCodeLegend>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:viewCodeLegend"/>
                </ns4:viewCodeLegend>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:useCode">
                <ns4:useCode>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:useCode"/>
                </ns4:useCode>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:useType">
                <ns4:useType>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:useType"/>
                </ns4:useType>
              </xsl:if>
              <xsl:if test="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:codeSplit">
                <ns4:codeSplit>
                  <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns1:managePDCRRequest/ns1:finalRealPropertyInfo/ns4:land/ns4:codeSplit"/>
                </ns4:codeSplit>
              </xsl:if>
            </ns4:land>
          </xsl:if>
        </ns1:finalRealPropertyInfo>
      </ns1:managePDCRRequest>
      <ns0:assignTo_UserID>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:assignTo_UserID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignTo_UserID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignTo_UserID"/>
      </ns0:assignTo_UserID>
      <ns0:assignTo_GroupID>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:assignTo_GroupID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignTo_GroupID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignTo_GroupID"/>
      </ns0:assignTo_GroupID>
      <ns0:assignTo_ManagerID>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:assignTo_ManagerID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignTo_ManagerID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignTo_ManagerID"/>
      </ns0:assignTo_ManagerID>
      <ns0:role>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:role/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:role/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:role"/>
      </ns0:role>
      <ns0:ownerID>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:ownerID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:ownerID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:ownerID"/>
      </ns0:ownerID>
      <ns0:clientID>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:clientID/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:clientID/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:clientID"/>
      </ns0:clientID>
      <ns0:checkPDCR>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:checkPDCR/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:checkPDCR/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:checkPDCR"/>
      </ns0:checkPDCR>
      <ns0:userType>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:userType/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:userType/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:userType"/>
      </ns0:userType>
      <ns0:accquiredBy>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:accquiredBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:accquiredBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:accquiredBy"/>
      </ns0:accquiredBy>
      <ns0:returnTo>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:returnTo/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:returnTo/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:returnTo"/>
      </ns0:returnTo>
      <ns0:sortPDCR>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:sortPDCR/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:sortPDCR/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <ns2:ain>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:sortPDCR/ns2:ain/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:sortPDCR/ns2:ain/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:sortPDCR/ns2:ain"/>
        </ns2:ain>
        <ns2:district>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:sortPDCR/ns2:district/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:sortPDCR/ns2:district/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:sortPDCR/ns2:district"/>
        </ns2:district>
        <ns2:region>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:sortPDCR/ns2:region/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:sortPDCR/ns2:region/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:sortPDCR/ns2:region"/>
        </ns2:region>
        <ns2:cluster>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:sortPDCR/ns2:cluster/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:sortPDCR/ns2:cluster/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:sortPDCR/ns2:cluster"/>
        </ns2:cluster>
      </ns0:sortPDCR>
      <ns0:assignmentBox>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:assignmentBox/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignmentBox/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <ns3:assignmentBox_UserId>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:assignmentBox/ns3:assignmentBox_UserId/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignmentBox/ns3:assignmentBox_UserId/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignmentBox/ns3:assignmentBox_UserId"/>
        </ns3:assignmentBox_UserId>
        <ns3:assignmentBox_GroupId>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:assignmentBox/ns3:assignmentBox_GroupId/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignmentBox/ns3:assignmentBox_GroupId/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignmentBox/ns3:assignmentBox_GroupId"/>
        </ns3:assignmentBox_GroupId>
        <ns3:userType>
          <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:assignmentBox/ns3:userType/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignmentBox/ns3:userType/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignmentBox/ns3:userType"/>
        </ns3:userType>
      </ns0:assignmentBox>
      <ns0:assignedBy>
        <xsl:if test="/ns0:PDCRHumanTaskBO/ns0:assignedBy/@xsi:nil">
          <xsl:attribute name="xsi:nil">
            <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignedBy/@xsi:nil"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:value-of select="/ns0:PDCRHumanTaskBO/ns0:assignedBy"/>
      </ns0:assignedBy>
    </ns0:PDCRHumanTaskBO>
  </xsl:template>
</xsl:stylesheet>