<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns8="http://assessor.lacounty.gov/amp/type/common/ParticipantDetails/v1.0" xmlns:ns4="http://xmlns.oracle.com/bpm/bpmobject/Data/PDCRHumanTaskBO" xmlns:ns7="http://assessor.lacounty.gov/amp/type/common/ResponseHeader/v1.0" xmlns:ns5="http://xmlns.oracle.com/bpel/workflow/common" xmlns:evidence="http://xmlns.oracle.com/bpel/workflow/TaskEvidenceService" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:ns1="http://assessor.lacounty.gov/amp/type/common/RealPropertyInfo/v1.0" xmlns:ns3="http://assessor.lacounty.gov/amp/type/common/RequestHeader/v1.0" xmlns:ns6="http://xmlns.oracle.com/bpm/bpmobject/Data/SortPDCRBO" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://xmlns.oracle.com/bpm/bpmobject/Data/AssignToUserOrGroupBO" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns2="http://assessor.lacounty.gov/amp/data/ao/ManagePDCR/v1.0" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:tns="http://xmlns.oracle.com/bpel/workflow/task" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns8 ns4 ns7 ns5 evidence jaxb ns1 ns3 ns6 ns0 ns2 xsd tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/ReviewPropertyDataChangeRequestWorkflowTask.xsd"/>
            <oracle-xsl-mapper:rootElement name="task" namespace="http://xmlns.oracle.com/bpel/workflow/task"/>
            <oracle-xsl-mapper:param name="execData"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/common/ParticipantDetails.xsd"/>
            <oracle-xsl-mapper:rootElement name="ParticipantDetails" namespace="http://assessor.lacounty.gov/amp/type/common/ParticipantDetails/v1.0"/>
            <oracle-xsl-mapper:param name="ParticipantDetailsPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/common/ParticipantDetails.xsd"/>
            <oracle-xsl-mapper:rootElement name="ParticipantDetails" namespace="http://assessor.lacounty.gov/amp/type/common/ParticipantDetails/v1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 15:05:03 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="ParticipantDetailsPDO"/>
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="contains(/tns:task/tns:systemAttributes/tns:outcome,'SUBMIT')">
        <ns8:ParticipantDetails>
          <ns8:participantId>
            <xsl:value-of select="/tns:task/tns:systemAttributes/tns:updatedBy/tns:id"/>
          </ns8:participantId>
          <ns8:participantUsername>
            <xsl:value-of select="/tns:task/tns:systemAttributes/tns:updatedBy/tns:displayName"/>
          </ns8:participantUsername>
          <ns8:participantUpdatedDate>
            <xsl:value-of select="/tns:task/tns:systemAttributes/tns:updatedDate"/>
          </ns8:participantUpdatedDate>
        </ns8:ParticipantDetails>
      </xsl:when>
      <xsl:otherwise>
        <ns8:ParticipantDetails>
          <ns8:participantId>
            <xsl:value-of select="$ParticipantDetailsPDO/ns8:ParticipantDetails/ns8:participantId"/>
          </ns8:participantId>
          <ns8:participantUsername>
            <xsl:value-of select="$ParticipantDetailsPDO/ns8:ParticipantDetails/ns8:participantUsername"/>
          </ns8:participantUsername>
          <ns8:participantUpdatedDate>
            <xsl:value-of select="$ParticipantDetailsPDO/ns8:ParticipantDetails/ns8:participantUpdatedDate"/>
          </ns8:participantUpdatedDate>
        </ns8:ParticipantDetails>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
</xsl:stylesheet>