<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns0="http://assessor.lacounty.gov/amp/data/ao/ManagePDCR/v1.0" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:inp3="http://assessor.lacounty.gov/amp/type/common/ResponseHeader/v1.0" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns1="http://assessor.lacounty.gov/amp/data/ao/UpdatePropertyDataCR/v1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:inp1="http://assessor.lacounty.gov/amp/type/common/RealPropertyInfo/v1.0" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:inp2="http://assessor.lacounty.gov/amp/type/common/RequestHeader/v1.0" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns0 inp3 inp1 xsd inp2 ns1 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/ao/ManagePDCR.xsd"/>
            <oracle-xsl-mapper:rootElement name="managePDCRRequest" namespace="http://assessor.lacounty.gov/amp/data/ao/ManagePDCR/v1.0"/>
            <oracle-xsl-mapper:param name="PDCRReqPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="http://ampsoad01.isd.lacounty.gov:8001/soa-infra/services/amp/PDCRMgmtService/apps/amp/xsd/ao/UpdatePropertyDataCR.xsd"/>
            <oracle-xsl-mapper:rootElement name="updatePropertyDataCRRequest" namespace="http://assessor.lacounty.gov/amp/data/ao/UpdatePropertyDataCR/v1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 15:05:03 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:updatePropertyDataCRRequest>
      <ns1:header>
        <xsl:if test="/ns0:managePDCRRequest/ns0:header/inp2:applicationId">
          <inp2:applicationId>
            <xsl:value-of select="/ns0:managePDCRRequest/ns0:header/inp2:applicationId"/>
          </inp2:applicationId>
        </xsl:if>
        <xsl:if test="/ns0:managePDCRRequest/ns0:header/inp2:requestId">
          <inp2:requestId>
            <xsl:value-of select="/ns0:managePDCRRequest/ns0:header/inp2:requestId"/>
          </inp2:requestId>
        </xsl:if>
      </ns1:header>
      <ns1:userId>
        <xsl:value-of select="/ns0:managePDCRRequest/ns0:userId"/>
      </ns1:userId>
      <ns1:source>
        <xsl:value-of select="/ns0:managePDCRRequest/ns0:source"/>
      </ns1:source>
      <ns1:realPropertyInfo>
        <inp1:ain>
          <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:ain"/>
        </inp1:ain>
        <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:aoid">
          <inp1:aoid>
            <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:aoid"/>
          </inp1:aoid>
        </xsl:if>
        <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:region">
          <inp1:region>
            <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:region"/>
          </inp1:region>
        </xsl:if>
        <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:cluster">
          <inp1:cluster>
            <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:cluster"/>
          </inp1:cluster>
        </xsl:if>
        <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:propertyAddress">
          <inp1:propertyAddress>
            <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:propertyAddress"/>
          </inp1:propertyAddress>
        </xsl:if>
        <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:district">
          <inp1:district>
            <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:district"/>
          </inp1:district>
        </xsl:if>
        <inp1:subPartList>
          <xsl:for-each select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:subPartList/inp1:subPart">
            <inp1:subPart>
              <xsl:if test="inp1:dbUniqueId">
                <inp1:dbUniqueId>
                  <xsl:value-of select="inp1:dbUniqueId"/>
                </inp1:dbUniqueId>
              </xsl:if>
              <inp1:ain>
                <xsl:value-of select="inp1:ain"/>
              </inp1:ain>
              <xsl:if test="inp1:aoid">
                <inp1:aoid>
                  <xsl:value-of select="inp1:aoid"/>
                </inp1:aoid>
              </xsl:if>
              <xsl:if test="inp1:transactionType">
                <inp1:transactionType>
                  <xsl:value-of select="inp1:transactionType"/>
                </inp1:transactionType>
              </xsl:if>
              <xsl:if test="inp1:improvementNumber">
                <inp1:improvementNumber>
                  <xsl:value-of select="inp1:improvementNumber"/>
                </inp1:improvementNumber>
              </xsl:if>
              <xsl:if test="inp1:subPartNumber">
                <inp1:subPartNumber>
                  <xsl:value-of select="inp1:subPartNumber"/>
                </inp1:subPartNumber>
              </xsl:if>
              <xsl:if test="inp1:rcnYearChange">
                <inp1:rcnYearChange>
                  <xsl:value-of select="inp1:rcnYearChange"/>
                </inp1:rcnYearChange>
              </xsl:if>
              <xsl:if test="inp1:designTypeRef">
                <inp1:designTypeRef>
                  <xsl:value-of select="inp1:designTypeRef"/>
                </inp1:designTypeRef>
              </xsl:if>
              <xsl:if test="inp1:designTypeKey">
                <inp1:designTypeKey>
                  <xsl:value-of select="inp1:designTypeKey"/>
                </inp1:designTypeKey>
              </xsl:if>
              <xsl:if test="inp1:designTypeLegend">
                <inp1:designTypeLegend>
                  <xsl:value-of select="inp1:designTypeLegend"/>
                </inp1:designTypeLegend>
              </xsl:if>
              <xsl:if test="inp1:qualityClass">
                <inp1:qualityClass>
                  <xsl:value-of select="inp1:qualityClass"/>
                </inp1:qualityClass>
              </xsl:if>
              <xsl:if test="inp1:yearBuilt">
                <inp1:yearBuilt>
                  <xsl:value-of select="inp1:yearBuilt"/>
                </inp1:yearBuilt>
              </xsl:if>
              <xsl:if test="inp1:effectiveYearBuilt">
                <inp1:effectiveYearBuilt>
                  <xsl:value-of select="inp1:effectiveYearBuilt"/>
                </inp1:effectiveYearBuilt>
              </xsl:if>
              <xsl:if test="inp1:depreciationTable">
                <inp1:depreciationTable>
                  <xsl:value-of select="inp1:depreciationTable"/>
                </inp1:depreciationTable>
              </xsl:if>
              <xsl:if test="inp1:numberOfUnits">
                <inp1:numberOfUnits>
                  <xsl:value-of select="inp1:numberOfUnits"/>
                </inp1:numberOfUnits>
              </xsl:if>
              <xsl:if test="inp1:bedroomCount">
                <inp1:bedroomCount>
                  <xsl:value-of select="inp1:bedroomCount"/>
                </inp1:bedroomCount>
              </xsl:if>
              <xsl:if test="inp1:bathroomCount">
                <inp1:bathroomCount>
                  <xsl:value-of select="inp1:bathroomCount"/>
                </inp1:bathroomCount>
              </xsl:if>
              <xsl:if test="inp1:improvementSizeSqft">
                <inp1:improvementSizeSqft>
                  <xsl:value-of select="inp1:improvementSizeSqft"/>
                </inp1:improvementSizeSqft>
              </xsl:if>
              <xsl:if test="inp1:rcnOtherTotal">
                <inp1:rcnOtherTotal>
                  <xsl:value-of select="inp1:rcnOtherTotal"/>
                </inp1:rcnOtherTotal>
              </xsl:if>
              <xsl:if test="inp1:costFactor">
                <inp1:costFactor>
                  <xsl:value-of select="inp1:costFactor"/>
                </inp1:costFactor>
              </xsl:if>
              <xsl:if test="inp1:rcnMain">
                <inp1:rcnMain>
                  <xsl:value-of select="inp1:rcnMain"/>
                </inp1:rcnMain>
              </xsl:if>
              <xsl:if test="inp1:percentGood">
                <inp1:percentGood>
                  <xsl:value-of select="inp1:percentGood"/>
                </inp1:percentGood>
              </xsl:if>
              <xsl:if test="inp1:addedDepreciationTypeRef">
                <inp1:addedDepreciationTypeRef>
                  <xsl:value-of select="inp1:addedDepreciationTypeRef"/>
                </inp1:addedDepreciationTypeRef>
              </xsl:if>
              <xsl:if test="inp1:addedDepreciationTypeKey">
                <inp1:addedDepreciationTypeKey>
                  <xsl:value-of select="inp1:addedDepreciationTypeKey"/>
                </inp1:addedDepreciationTypeKey>
              </xsl:if>
              <xsl:if test="inp1:addedDepreciationTypeLegend">
                <inp1:addedDepreciationTypeLegend>
                  <xsl:value-of select="inp1:addedDepreciationTypeLegend"/>
                </inp1:addedDepreciationTypeLegend>
              </xsl:if>
              <xsl:if test="inp1:addedDepreciationPercent">
                <inp1:addedDepreciationPercent>
                  <xsl:value-of select="inp1:addedDepreciationPercent"/>
                </inp1:addedDepreciationPercent>
              </xsl:if>
              <xsl:if test="inp1:rcnLessDepreciation">
                <inp1:rcnLessDepreciation>
                  <xsl:value-of select="inp1:rcnLessDepreciation"/>
                </inp1:rcnLessDepreciation>
              </xsl:if>
            </inp1:subPart>
          </xsl:for-each>
        </inp1:subPartList>
        <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:composite">
          <inp1:composite>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:composite/inp1:dbUniqueId">
              <inp1:dbUniqueId>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:composite/inp1:dbUniqueId"/>
              </inp1:dbUniqueId>
            </xsl:if>
            <inp1:ain>
              <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:composite/inp1:ain"/>
            </inp1:ain>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:composite/inp1:aoid">
              <inp1:aoid>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:composite/inp1:aoid"/>
              </inp1:aoid>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:composite/inp1:transactionType">
              <inp1:transactionType>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:composite/inp1:transactionType"/>
              </inp1:transactionType>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:composite/inp1:sqft">
              <inp1:sqft>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:composite/inp1:sqft"/>
              </inp1:sqft>
            </xsl:if>
          </inp1:composite>
        </xsl:if>
        <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land">
          <inp1:land>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:dbUniqueId">
              <inp1:dbUniqueId>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:dbUniqueId"/>
              </inp1:dbUniqueId>
            </xsl:if>
            <inp1:ain>
              <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:ain"/>
            </inp1:ain>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:aoid">
              <inp1:aoid>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:aoid"/>
              </inp1:aoid>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:transactionType">
              <inp1:transactionType>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:transactionType"/>
              </inp1:transactionType>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:width">
              <inp1:width>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:width"/>
              </inp1:width>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:depth">
              <inp1:depth>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:depth"/>
              </inp1:depth>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:sizeSqft">
              <inp1:sizeSqft>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:sizeSqft"/>
              </inp1:sizeSqft>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:sizeUsableSqft">
              <inp1:sizeUsableSqft>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:sizeUsableSqft"/>
              </inp1:sizeUsableSqft>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:sizeAcreAge">
              <inp1:sizeAcreAge>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:sizeAcreAge"/>
              </inp1:sizeAcreAge>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:corner">
              <inp1:corner>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:corner"/>
              </inp1:corner>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:sewer">
              <inp1:sewer>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:sewer"/>
              </inp1:sewer>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:traffic">
              <inp1:traffic>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:traffic"/>
              </inp1:traffic>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:freewayProximity">
              <inp1:freewayProximity>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:freewayProximity"/>
              </inp1:freewayProximity>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:flightPath">
              <inp1:flightPath>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:flightPath"/>
              </inp1:flightPath>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:golfFront">
              <inp1:golfFront>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:golfFront"/>
              </inp1:golfFront>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:horses">
              <inp1:horses>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:horses"/>
              </inp1:horses>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:viewCodeKey">
              <inp1:viewCodeKey>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:viewCodeKey"/>
              </inp1:viewCodeKey>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:viewCodeRef">
              <inp1:viewCodeRef>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:viewCodeRef"/>
              </inp1:viewCodeRef>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:viewCodeLegend">
              <inp1:viewCodeLegend>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:viewCodeLegend"/>
              </inp1:viewCodeLegend>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:useCode">
              <inp1:useCode>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:useCode"/>
              </inp1:useCode>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:useType">
              <inp1:useType>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:useType"/>
              </inp1:useType>
            </xsl:if>
            <xsl:if test="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:codeSplit">
              <inp1:codeSplit>
                <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:land/inp1:codeSplit"/>
              </inp1:codeSplit>
            </xsl:if>
          </inp1:land>
        </xsl:if>
      </ns1:realPropertyInfo>
    </ns1:updatePropertyDataCRRequest>
  </xsl:template>
</xsl:stylesheet>