<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns1="http://assessor.lacounty.gov/amp/data/ao/ReleaseLock/v1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns0="http://assessor.lacounty.gov/amp/data/ao/ManagePDCR/v1.0" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:inp3="http://assessor.lacounty.gov/amp/type/common/ResponseHeader/v1.0" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:inp1="http://assessor.lacounty.gov/amp/type/common/RealPropertyInfo/v1.0" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:inp2="http://assessor.lacounty.gov/amp/type/common/RequestHeader/v1.0" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns0 inp3 inp1 xsd inp2 ns1 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/ao/ManagePDCR.xsd"/>
            <oracle-xsl-mapper:rootElement name="managePDCRRequest" namespace="http://assessor.lacounty.gov/amp/data/ao/ManagePDCR/v1.0"/>
            <oracle-xsl-mapper:param name="PDCRReqPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="http://ampsoad01.isd.lacounty.gov:8001/soa-infra/services/amp/AINLockMgmtService/apps/amp/xsd/ao/ReleaseLock.xsd"/>
            <oracle-xsl-mapper:rootElement name="releaseLockRequest" namespace="http://assessor.lacounty.gov/amp/data/ao/ReleaseLock/v1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 15:05:03 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:releaseLockRequest>
      <ns1:header>
        <xsl:if test="/ns0:managePDCRRequest/ns0:header/inp2:applicationId">
          <inp2:applicationId>
            <xsl:value-of select="/ns0:managePDCRRequest/ns0:header/inp2:applicationId"/>
          </inp2:applicationId>
        </xsl:if>
        <xsl:if test="/ns0:managePDCRRequest/ns0:header/inp2:requestId">
          <inp2:requestId>
            <xsl:value-of select="/ns0:managePDCRRequest/ns0:header/inp2:requestId"/>
          </inp2:requestId>
        </xsl:if>
      </ns1:header>
      <ns1:ain>
        <xsl:value-of select="/ns0:managePDCRRequest/ns0:ain"/>
      </ns1:ain>
      <ns1:aoid>
        <xsl:value-of select="/ns0:managePDCRRequest/ns0:aoid"/>
      </ns1:aoid>
      <ns1:userId>
        <xsl:value-of select="/ns0:managePDCRRequest/ns0:userId"/>
      </ns1:userId>
      <ns1:processType>
        <xsl:value-of select="/ns0:managePDCRRequest/ns0:processType"/>
      </ns1:processType>
      <!--xsl:choose>
        <xsl:when test='/ns0:managePDCRRequest/ns0:processType = "BVM"'>
          <ns1:processType>
            <xsl:text disable-output-escaping="no">1</xsl:text>
          </ns1:processType>
        </xsl:when>
        <xsl:when test='/ns0:managePDCRRequest/ns0:processType = "PDCR"'>
          <ns1:processType>
            <xsl:text disable-output-escaping="no">2</xsl:text>
          </ns1:processType>
        </xsl:when>
        <xsl:otherwise>
          <ns1:processType>
            <xsl:text disable-output-escaping="no"></xsl:text>
          </ns1:processType>
        </xsl:otherwise>
      </xsl:choose-->
    </ns1:releaseLockRequest>
  </xsl:template>
</xsl:stylesheet>