<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://xmlns.oracle.com/bpel/workflow/common" xmlns:inp3="http://assessor.lacounty.gov/amp/type/common/ResponseHeader/v1.0" xmlns:evidence="http://xmlns.oracle.com/bpel/workflow/TaskEvidenceService" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:bpmo="http://xmlns.oracle.com/bpm/bpmobject/" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:inp1="http://assessor.lacounty.gov/amp/type/common/RealPropertyInfo/v1.0" xmlns:ns3="http://assessor.lacounty.gov/amp/data/ao/LogWorkFlowDetails/v1.0" xmlns:inp2="http://assessor.lacounty.gov/amp/type/common/RequestHeader/v1.0" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://assessor.lacounty.gov/amp/data/ao/ManagePDCR/v1.0" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns2="http://xmlns.oracle.com/bpm/bpmobject/Data/ErrorBO" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xmlns.oracle.com/bpel/workflow/task" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns1 inp3 evidence bpmo jaxb inp1 inp2 ns0 ns2 xsd tns ns3 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/ao/ManagePDCR.xsd"/>
            <oracle-xsl-mapper:rootElement name="managePDCRRequest" namespace="http://assessor.lacounty.gov/amp/data/ao/ManagePDCR/v1.0"/>
            <oracle-xsl-mapper:param name="PDCRReqPDO"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/soa/shared/workflow/WorkflowTask.xsd"/>
            <oracle-xsl-mapper:rootElement name="task" namespace="http://xmlns.oracle.com/bpel/workflow/task"/>
            <oracle-xsl-mapper:param name="execDataWFLogDO"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/ErrorBO.xsd"/>
            <oracle-xsl-mapper:rootElement name="ErrorBO" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/ErrorBO"/>
            <oracle-xsl-mapper:param name="errorDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/ao/LogWorkFlowDetails.xsd"/>
            <oracle-xsl-mapper:rootElement name="logWorkFlowDetailsRequest" namespace="http://assessor.lacounty.gov/amp/data/ao/LogWorkFlowDetails/v1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 15:05:03 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="execDataWFLogDO"/>
  <xsl:param name="errorDO"/>
  <xsl:template match="/">
    <ns3:logWorkFlowDetailsRequest>
      <ns3:header>
        <xsl:if test="/ns0:managePDCRRequest/ns0:header/inp2:applicationId">
          <inp2:applicationId>
            <xsl:value-of select="/ns0:managePDCRRequest/ns0:header/inp2:applicationId"/>
          </inp2:applicationId>
        </xsl:if>
        <xsl:if test="/ns0:managePDCRRequest/ns0:header/inp2:requestId">
          <inp2:requestId>
            <xsl:value-of select="/ns0:managePDCRRequest/ns0:header/inp2:requestId"/>
          </inp2:requestId>
        </xsl:if>
      </ns3:header>
      <ns3:ain>
        <xsl:value-of select="/ns0:managePDCRRequest/ns0:ain"/>
      </ns3:ain>
      <ns3:aoid>
        <xsl:value-of select="/ns0:managePDCRRequest/ns0:aoid"/>
      </ns3:aoid>
      <ns3:userId>
        <xsl:value-of select="/ns0:managePDCRRequest/ns0:userId"/>
      </ns3:userId>
      <ns3:processType>
        <xsl:value-of select="/ns0:managePDCRRequest/ns0:processType"/>
      </ns3:processType>
      <ns3:initiatedBy>
        <xsl:value-of select="/ns0:managePDCRRequest/ns0:userId"/>
      </ns3:initiatedBy>
      <ns3:initiatedDate>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:createdDate"/>
      </ns3:initiatedDate>
      <ns3:claimedBy>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:acquiredBy"/>
      </ns3:claimedBy>
      <ns3:claimedDate>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:assignedDate"/>
      </ns3:claimedDate>
      <ns3:reviewedBy>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:reviewers/tns:id"/>
      </ns3:reviewedBy>
      <ns3:reviewedDate>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:updatedDate"/>
      </ns3:reviewedDate>
      <ns3:editStatus>
        <xsl:text disable-output-escaping="no">COMPLETED</xsl:text>
      </ns3:editStatus>
      <ns3:editBy>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:updatedBy/tns:id"/>
      </ns3:editBy>
      <ns3:editDate>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:updatedDate"/>
      </ns3:editDate>
      <ns3:approvedBy>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:updatedBy/tns:id"/>
      </ns3:approvedBy>
      <ns3:approvedDate>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:updatedDate"/>
      </ns3:approvedDate>
      <xsl:choose>
        <xsl:when test="contains($execDataWFLogDO/tns:task/tns:taskDefinitionId,&quot;NotifyAdminOfIssue&quot;)">
          <ns3:processStatus>
            <xsl:text disable-output-escaping="no">ERRORED</xsl:text>
          </ns3:processStatus>
        </xsl:when>
        <xsl:otherwise>
          <ns3:processStatus>
            <xsl:text disable-output-escaping="no">COMPLETED</xsl:text>
          </ns3:processStatus>
        </xsl:otherwise>
      </xsl:choose>
      <ns3:processName>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:processInfo/tns:processName"/>
      </ns3:processName>
      <ns3:processInstanceId>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:sca/tns:compositeInstanceId"/>
      </ns3:processInstanceId>
      <ns3:ecid>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:sca/tns:ecId"/>
      </ns3:ecid>
      <ns3:district>
        <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:district"/>
      </ns3:district>
      <ns3:region>
        <xsl:value-of select="/ns0:managePDCRRequest/ns0:finalRealPropertyInfo/inp1:region"/>
      </ns3:region>
      <ns3:processStartTime>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:sca/tns:compositeCreatedTime"/>
      </ns3:processStartTime>
      <ns3:processEndTime>
        <xsl:value-of select="xp20:current-dateTime()"/>
      </ns3:processEndTime>
      <ns3:processPayload>
        <xsl:copy-of select="$execDataWFLogDO/tns:task/tns:payload"/>
      </ns3:processPayload>
      <ns3:taskId>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:taskId"/>
      </ns3:taskId>
      <ns3:taskName>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:taskDefinitionName"/>
      </ns3:taskName>
      <ns3:taskAction>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:actionDisplayName"/>
      </ns3:taskAction>
      <xsl:choose>
        <xsl:when test="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:assigneeUsers/tns:type">
          <ns3:taskType>
            <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:assigneeUsers/tns:type"/>
          </ns3:taskType>
        </xsl:when>
        <xsl:otherwise>
          <ns3:taskType>
            <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:assigneeGroups/tns:type"/>
          </ns3:taskType>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:assigneeUsers/tns:id != &quot;&quot;">
          <ns3:assignee>
            <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:assigneeUsers/tns:id"/>
          </ns3:assignee>
        </xsl:when>
        <xsl:otherwise>
          <ns3:assignee>
            <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:assigneeGroups/tns:id"/>
          </ns3:assignee>
        </xsl:otherwise>
      </xsl:choose>
      <ns3:taskStartDate>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:createdDate"/>
      </ns3:taskStartDate>
      <ns3:taskEndDate>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:endDate"/>
      </ns3:taskEndDate>
      <ns3:source>
        <xsl:value-of select="/ns0:managePDCRRequest/ns0:source"/>
      </ns3:source>
      <ns3:errorCode>
        <xsl:value-of select="$errorDO/ns2:ErrorBO/ns2:errorNS"/>
      </ns3:errorCode>
      <ns3:errorType>
        <xsl:value-of select="$errorDO/ns2:ErrorBO/ns2:errorName"/>
      </ns3:errorType>
      <ns3:errorDescription>
        <xsl:value-of select="$errorDO/ns2:ErrorBO/ns2:errorInfo"/>
      </ns3:errorDescription>
      <ns3:owner>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:ownerUser"/>
      </ns3:owner>
      <ns3:notes>
        <xsl:for-each select="$execDataWFLogDO/tns:task/tns:userComment">
          <ns3:notes>
            <ns3:description>
              <xsl:value-of select="tns:comment"/>
            </ns3:description>
            <ns3:updateBy>
              <xsl:value-of select="tns:updatedBy/tns:id"/>
            </ns3:updateBy>
          </ns3:notes>
        </xsl:for-each>
      </ns3:notes>
      <ns3:attachments>
        <xsl:for-each select="$execDataWFLogDO/tns:task/tns:attachment">
          <xsl:if test=".">
            <ns3:attachments>
              <xsl:if test="tns:content">
                <ns3:content>
                  <xsl:value-of select="tns:content"/>
                </ns3:content>
              </xsl:if>
              <xsl:if test="tns:mimeType">
                <ns3:mimeType>
                  <xsl:value-of select="tns:mimeType"/>
                </ns3:mimeType>
              </xsl:if>
              <ns3:documentName>
                <xsl:value-of select="tns:name"/>
              </ns3:documentName>
              <ns3:documentObjID>
                <xsl:value-of select="tns:id"/>
              </ns3:documentObjID>
              <ns3:documentURL>
                <xsl:value-of select="tns:URI"/>
              </ns3:documentURL>
              <xsl:if test="tns:systemVersionFlag">
                <ns3:systemVersionFlag>
                  <xsl:value-of select="tns:systemVersionFlag"/>
                </ns3:systemVersionFlag>
              </xsl:if>
              <xsl:if test="tns:taskId">
                <ns3:taskId>
                  <xsl:value-of select="tns:taskId"/>
                </ns3:taskId>
              </xsl:if>
              <xsl:if test="tns:version">
                <ns3:version>
                  <xsl:value-of select="tns:version"/>
                </ns3:version>
              </xsl:if>
              <xsl:if test="tns:acl">
                <ns3:acl>
                  <xsl:value-of select="tns:acl"/>
                </ns3:acl>
              </xsl:if>
              <xsl:if test="tns:doesBelongToParent">
                <ns3:doesBelongToParent>
                  <xsl:value-of select="tns:doesBelongToParent"/>
                </ns3:doesBelongToParent>
              </xsl:if>
              <ns3:documentType>
                <xsl:value-of select="tns:mimeType"/>
              </ns3:documentType>
              <ns3:updateBy>
                <xsl:value-of select="tns:id"/>
              </ns3:updateBy>
              <xsl:if test="tns:updatedDate">
                <ns3:updatedDate>
                  <xsl:value-of select="tns:updatedDate"/>
                </ns3:updatedDate>
              </xsl:if>
              <xsl:if test="tns:correlationId">
                <ns3:correlationId>
                  <xsl:value-of select="tns:correlationId"/>
                </ns3:correlationId>
              </xsl:if>
              <xsl:if test="tns:size">
                <ns3:size>
                  <xsl:value-of select="tns:size"/>
                </ns3:size>
              </xsl:if>
              <xsl:if test="tns:description">
                <ns3:description>
                  <xsl:value-of select="tns:description"/>
                </ns3:description>
              </xsl:if>
              <xsl:if test="tns:storageType">
                <ns3:storageType>
                  <xsl:value-of select="tns:storageType"/>
                </ns3:storageType>
              </xsl:if>
              <ns3:ucmDocType>
                <xsl:value-of select="tns:ucmMetadataItem/tns:type"/>
              </ns3:ucmDocType>
              <xsl:if test="tns:securityGroup">
                <ns3:securityGroup>
                  <xsl:value-of select="tns:securityGroup"/>
                </ns3:securityGroup>
              </xsl:if>
              <xsl:if test="tns:account">
                <ns3:account>
                  <xsl:value-of select="tns:account"/>
                </ns3:account>
              </xsl:if>
              <xsl:if test="tns:revision">
                <ns3:revision>
                  <xsl:value-of select="tns:revision"/>
                </ns3:revision>
              </xsl:if>
              <xsl:if test="tns:releaseDate">
                <ns3:releaseDate>
                  <xsl:value-of select="tns:releaseDate"/>
                </ns3:releaseDate>
              </xsl:if>
              <xsl:if test="tns:expirationDate">
                <ns3:expirationDate>
                  <xsl:value-of select="tns:expirationDate"/>
                </ns3:expirationDate>
              </xsl:if>
              <xsl:if test="tns:title">
                <ns3:title>
                  <xsl:value-of select="tns:title"/>
                </ns3:title>
              </xsl:if>
              <xsl:if test="tns:attachmentScope">
                <ns3:attachmentScope>
                  <xsl:value-of select="tns:attachmentScope"/>
                </ns3:attachmentScope>
              </xsl:if>
              <xsl:if test="tns:isContentEncoded">
                <ns3:isContentEncoded>
                  <xsl:value-of select="tns:isContentEncoded"/>
                </ns3:isContentEncoded>
              </xsl:if>
              <xsl:if test="tns:updatedByDisplayName">
                <ns3:updatedByDisplayName>
                  <xsl:value-of select="tns:updatedByDisplayName"/>
                </ns3:updatedByDisplayName>
              </xsl:if>
              <xsl:if test="tns:id">
                <ns3:id>
                  <xsl:value-of select="tns:id"/>
                </ns3:id>
              </xsl:if>
              <xsl:if test="tns:operation">
                <ns3:operation>
                  <xsl:value-of select="tns:operation"/>
                </ns3:operation>
              </xsl:if>
            </ns3:attachments>
          </xsl:if>
        </xsl:for-each>
      </ns3:attachments>
      <ns3:elapsedTime>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:approvalDuration"/>
      </ns3:elapsedTime>
      <ns3:taskNum>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:taskNumber"/>
      </ns3:taskNum>
      <ns3:outcome>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:outcome"/>
      </ns3:outcome>
      <ns3:state>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:systemAttributes/tns:state"/>
      </ns3:state>
      <ns3:taskTitle>
        <xsl:value-of select="$execDataWFLogDO/tns:task/tns:title"/>
      </ns3:taskTitle>
    </ns3:logWorkFlowDetailsRequest>
  </xsl:template>
</xsl:stylesheet>