<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns2="http://xmlns.oracle.com/bpm/bpmobject/Data/PDCRHumanTaskBO" xmlns:inp2="http://assessor.lacounty.gov/amp/type/common/ResponseHeader/v1.0" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:bpmo="http://xmlns.oracle.com/bpm/bpmobject/" xmlns:ns5="http://assessor.lacounty.gov/amp/type/common/RealPropertyInfo/v1.0" xmlns:inp1="http://assessor.lacounty.gov/amp/type/common/RequestHeader/v1.0" xmlns:ns4="http://xmlns.oracle.com/bpm/bpmobject/Data/SortPDCRBO" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://assessor.lacounty.gov/amp/data/ao/UpdateProcessStatus/v1.0" xmlns:ns3="http://xmlns.oracle.com/bpm/bpmobject/Data/AssignToUserOrGroupBO" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns1="http://assessor.lacounty.gov/amp/data/ao/ManagePDCR/v1.0" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns2 inp2 bpmo ns5 inp1 ns4 ns0 ns3 ns1 xsd xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/ao/UpdateProcessStatus.xsd"/>
            <oracle-xsl-mapper:rootElement name="updateProcessStatusRequest" namespace="http://assessor.lacounty.gov/amp/data/ao/UpdateProcessStatus/v1.0"/>
            <oracle-xsl-mapper:param name="ProcessStatusDO"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../businessCatalog/Data/PDCRHumanTaskBO.xsd"/>
            <oracle-xsl-mapper:rootElement name="PDCRHumanTaskBO" namespace="http://xmlns.oracle.com/bpm/bpmobject/Data/PDCRHumanTaskBO"/>
            <oracle-xsl-mapper:param name="HumanTaskPDO"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/ao/ManagePDCR.xsd"/>
            <oracle-xsl-mapper:rootElement name="managePDCRRequest" namespace="http://assessor.lacounty.gov/amp/data/ao/ManagePDCR/v1.0"/>
            <oracle-xsl-mapper:param name="PDCRReqPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/amp/xsd/ao/UpdateProcessStatus.xsd"/>
            <oracle-xsl-mapper:rootElement name="updateProcessStatusRequest" namespace="http://assessor.lacounty.gov/amp/data/ao/UpdateProcessStatus/v1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAR 09 15:05:03 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="HumanTaskPDO"/>
  <xsl:param name="PDCRReqPDO"/>
  <xsl:template match="/">
    <ns0:updateProcessStatusRequest>
      <ns0:ain>
        <xsl:value-of select="$PDCRReqPDO/ns1:managePDCRRequest/ns1:ain"/>
      </ns0:ain>
      <ns0:aoid>
        <xsl:value-of select="$PDCRReqPDO/ns1:managePDCRRequest/ns1:aoid"/>
      </ns0:aoid>
      <ns0:userId>
        <xsl:value-of select="$PDCRReqPDO/ns1:managePDCRRequest/ns1:userId"/>
      </ns0:userId>
      <ns0:processType>
        <xsl:value-of select="$PDCRReqPDO/ns1:managePDCRRequest/ns1:processType"/>
      </ns0:processType>
      <ns0:initiatedBy>
        <xsl:value-of select="/ns0:updateProcessStatusRequest/ns0:initiatedBy"/>
      </ns0:initiatedBy>
      <ns0:initiatedDate>
        <xsl:value-of select="/ns0:updateProcessStatusRequest/ns0:initiatedDate"/>
      </ns0:initiatedDate>
      <ns0:lockStatus>
        <xsl:text disable-output-escaping="no">UNLOCKED</xsl:text>
      </ns0:lockStatus>
      <ns0:lockStatusDate>
        <xsl:value-of select="/ns0:updateProcessStatusRequest/ns0:lockStatusDate"/>
      </ns0:lockStatusDate>
      <ns0:processName>
        <xsl:value-of select="/ns0:updateProcessStatusRequest/ns0:processName"/>
      </ns0:processName>
      <ns0:reviewedBy>
        <xsl:value-of select="/ns0:updateProcessStatusRequest/ns0:reviewedBy"/>
      </ns0:reviewedBy>
      <ns0:reviewedDate>
        <xsl:value-of select="/ns0:updateProcessStatusRequest/ns0:reviewedDate"/>
      </ns0:reviewedDate>
      <ns0:editBy>
        <xsl:value-of select="/ns0:updateProcessStatusRequest/ns0:editBy"/>
      </ns0:editBy>
      <ns0:editDate>
        <xsl:value-of select="/ns0:updateProcessStatusRequest/ns0:editDate"/>
      </ns0:editDate>
      <ns0:editStatus>
        <xsl:value-of select="/ns0:updateProcessStatusRequest/ns0:editStatus"/>
      </ns0:editStatus>
      <ns0:approvedBy>
        <xsl:value-of select="/ns0:updateProcessStatusRequest/ns0:approvedBy"/>
      </ns0:approvedBy>
      <ns0:approvedDate>
        <xsl:value-of select="/ns0:updateProcessStatusRequest/ns0:approvedDate"/>
      </ns0:approvedDate>
      <ns0:processAssignment>
        <xsl:value-of select="/ns0:updateProcessStatusRequest/ns0:processAssignment"/>
      </ns0:processAssignment>
      <xsl:choose>
        <xsl:when test="contains(/ns0:updateProcessStatusRequest/ns0:processStatus,'InvalidSource') or contains(/ns0:updateProcessStatusRequest/ns0:processStatus,'InvalidRole')">
          <ns0:processStatus>
            <xsl:text disable-output-escaping="no">CANCELLED</xsl:text>
          </ns0:processStatus>
        </xsl:when>
        <xsl:when test="contains(/ns0:updateProcessStatusRequest/ns0:processStatus,'ERRORED')">
          <ns0:processStatus>
            <xsl:text disable-output-escaping="no">ERRORED</xsl:text>
          </ns0:processStatus>
        </xsl:when>
        <xsl:otherwise>
          <ns0:processStatus>
            <xsl:text disable-output-escaping="no">COMPLETED</xsl:text>
          </ns0:processStatus>
        </xsl:otherwise>
      </xsl:choose>
      <ns0:processInstanceId>
        <xsl:value-of select="/ns0:updateProcessStatusRequest/ns0:processInstanceId"/>
      </ns0:processInstanceId>
    </ns0:updateProcessStatusRequest>
  </xsl:template>
</xsl:stylesheet>